### ISSUE TITLE
3.0.5 on Ubuntu 18.04 LTS audio 

### ISSUE THREAD

**Issue by jwbruce** [vkohaupt/vokoscreenNG#101]
when recording screen or webcam on 18.04, I basically get no audio recorded.  Just little pops of sound every 3-4 seconds.  I have tried all the audio codecs.  All do the same thing.

BTW, I had the same behavior on vokoscreenNG 3.0.4.  The last non-NG version records audio and video correctly.

**Comment by jwbruce** [comment]
It does appear to work when the framerate is 25 fps.  If the framerate is not 25fps, the audio either does not work from the beginning or will eventually because to drop out.  Most pronounced at 10fps.

**Comment by vkohaupt** [comment]
I was able to reproduce the dropouts by changing the preset to medium, slow, slower or veryslow for x264.
I have therefore built in additional buffers and have no dropouts.
https://github.com/vkohaupt/vokoscreenNG/commit/a09101b22093d3ddc9bc950326b470bbd889936e
Thank you for your hint.

**Comment by vkohaupt** [comment]
Today I will release vokoscreenNG 3.0.6. If this version is available to you, please test it and I would be grateful for your feedback.
