### ISSUE TITLE
bzip2 development package not found

### ISSUE THREAD

**Issue by mchoccac** [vkohaupt/vokoscreenNG#102]
Committed a09101b
Error to generate qmake vokoscreenNG.pro

Updating 'language/zh_TW.qm'...
    Generated 117 translation(s) (117 finished and 0 unfinished)
Project ERROR: bzip2 development package not found

localize:  unix:PKGCONFIG += bzip2

I have the version

pkg-config --version
0.29.1
bzip2 --version
bzip2, a block-sorting file compressor.  Version 1.0.8, 13-Jul-2019.

I already have installed
libbz2-dev

**Comment by vkohaupt** [comment]
libbz2-dev is installed and comes a Project ERROR: bzip2 development package not found?
Hmmm.....
I must show in a virtual machine.
Distribution?

**Comment by stefanhusmann** [comment]
Same here, under Arch Linux, same bzip2 version. Arch Linux does not split into packages and devel-packages, so everythin needed should be there.

**Comment by stefanhusmann** [comment]
This fixes the build for me, but the file README.md would also need adjustment. It mentions bzip2 only in the Windows section.
``` patch
iff --git a/src/vokoscreenNG.pro b/src/vokoscreenNG.pro
index 09158dec..180ab9f5 100644
--- a/src/vokoscreenNG.pro
+++ b/src/vokoscreenNG.pro
@@ -73,8 +73,7 @@ QMAKE_LFLAGS += -Wl,--as-needed
 
 unix:CONFIG += link_pkgconfig
 unix:PKGCONFIG += gstreamer-1.0 libpulse
-unix:LIBS += -lpulse-simple
-unix:PKGCONFIG += bzip2
+unix:LIBS += -lpulse-simple -lbz2
 
 win32:RC_ICONS = vokoscreenNG.ico
```

**Comment by aasril** [comment]
> libbz2-dev is installed and comes a Project ERROR: bzip2 development package not found?
> Hmmm.....
> I must show in a virtual machine.
> Distribution?

I'm getting this error. It's on Ubuntu 20.04.

**Comment by vkohaupt** [comment]
I need bz2 only for Windows and i have changed the code. Please make a new git clone and all is good.

**Comment by stefanhusmann** [comment]
I get still the same error message.

**Comment by vkohaupt** [comment]
Thanks for the hint. It should work again now. Thanks for testing.

**Comment by stefanhusmann** [comment]
Yes, it works now. Thanks!
