### ISSUE TITLE
No Audio Recording Device found, Linux

### ISSUE THREAD

**Issue by goeba** [vkohaupt/vokoscreenNG#106]
Hi,

I'm on Arch linux, have been using Vokoscreen for years without problems. Recently, after some update, I got "no audio recording device found" on the audio-tab.

I'm using kde, which uses pulseaudio anyway, and audio works for other programs. I have testet 3.04 (which is in arch), and build 3.05 and 3.06 from source, same results. I cannot build 3.03 from source, as I get a build error (

egion/QvkRegionButtonArrow.cpp:81:22: Fehler: Aggregat »QPainterPath painterPath« hat unvollständigen Typ und kann nicht definiert werden
   81 |         QPainterPath painterPath;
      |                      ^~~~~~~~~~~
)
Any hints on how to debug this?

Regards,

Andreas

**Comment by llabusch93** [comment]
Hello @vkohaupt 

+1 for me, having the exact same issue as @goeba and I am also on KDE, running in Arch.

Could you help us out?

P.S.
Loving your software!

**Comment by vkohaupt** [comment]
Yes i want to help. I want to look at it myself in virtualbox. But I can only find installation howtos with thousand steps. I need an archlinux.iso which I install in Virtualbox and then want to install vokoscreenNG without further ado. Do you have a download link?

**Comment by vkohaupt** [comment]
@goeba 
You can fix for 3.0.3 with #include <QPainterPath> in src/region/QvkRegionButtonArrow.cpp
Show here
https://github.com/vkohaupt/vokoscreenNG/commit/2fd6901b3c72d58fd444da588381351c21f10cd1

@goeba and @llabusch93 
open a terminal and enter the following
gst-device-monitor-1.0
copy the output and post here

**Comment by llabusch93** [comment]
Hello @vkohaupt 

thanks for your support. For the Arch installation, just go with Manjaro, it's Arch underlying (that is actually what I am on).

https://manjaro.org/downloads/official/kde/

The output is the following, only showing the camera:

```
Probing devices...


Device found:

name  : Integrated_Webcam_HD: Integrate
class : Video/Source
caps  : image/jpeg, width=(int)1280, height=(int)720, framerate=(fraction)30/1;
image/jpeg, width=(int)960, height=(int)540, framerate=(fraction)30/1;
image/jpeg, width=(int)848, height=(int)480, framerate=(fraction)30/1;
image/jpeg, width=(int)640, height=(int)480, framerate=(fraction)30/1;
image/jpeg, width=(int)640, height=(int)360, framerate=(fraction)30/1;
video/x-raw, format=(string)YUY2, width=(int)640, height=(int)480, framerate=(fraction)30/1;
video/x-raw, format=(string)YUY2, width=(int)640, height=(int)360, framerate=(fraction)30/1;
video/x-raw, format=(string)YUY2, width=(int)424, height=(int)240, framerate=(fraction)30/1;
video/x-raw, format=(string)YUY2, width=(int)320, height=(int)240, framerate=(fraction)30/1;
video/x-raw, format=(string)YUY2, width=(int)320, height=(int)180, framerate=(fraction)30/1;
video/x-raw, format=(string)YUY2, width=(int)160, height=(int)120, framerate=(fraction)30/1;
properties:
object.path = v4l2:/dev/video0
device.api = v4l2
media.class = Video/Source
api.v4l2.path = /dev/video0
api.v4l2.cap.driver = uvcvideo
api.v4l2.cap.card = "Integrated_Webcam_HD:\ Integrate"
api.v4l2.cap.bus_info = usb-0000:00:14.0-12
api.v4l2.cap.version = 5.4.60
api.v4l2.cap.capabilities = 84a00001
api.v4l2.cap.device-caps = 04200001
device.id = 34
node.name = api.v4l2.source.v4l2_device.pci-0000:00:14.0-usb-0:12:1.0
node.description = "Integrated_Webcam_HD:\ Integrate"
factory.name = api.v4l2.source
factory.id = 10
client.id = 31
media.role = Camera
node.pause-on-idle = false
node.driver = true
object.id = 41
gst-launch-1.0 pipewiresrc path=41 ! ...

```

**Comment by llabusch93** [comment]
Hello @vkohaupt 

you can close this issue. Manjaro got a big update this morning (just did it) and the issues are gone, audio devices are back. Seems to be a problem of some library, but it's fixed.

![image](https://user-images.githubusercontent.com/38892451/92568724-e2ea5d80-f27f-11ea-81dd-26b23e067e33.png)


@goeba upgrade your system, and enjoy again ;)
