### ISSUE TITLE
[Feature request] Option to display webcam window on all virtual desktops

### ISSUE THREAD

**Issue by luco5826** [vkohaupt/vokoscreenNG#108]
Hi!
I really like VokoscreenNG and it's an awesome tool.
I use a lot the mutliple desktop feature available on almost every major DE and I noticed that when screencasting with webcam, this window does not "follow" the desktop focus.

I think there could be a toggle option  in order to get the webcam either on all desktops or just in one, wyt?

**Comment by vkohaupt** [comment]
OS?
Desktop?

**Comment by luco5826** [comment]
I'm currently on KDE Neon 5.19 with KDE Plasma 5.19.5

**Comment by vkohaupt** [comment]
You have two options for doing this.
![Bild-01](https://user-images.githubusercontent.com/3152567/93379350-ff792d80-f85d-11ea-8e5d-915a876f7efa.png)
![Bild-02](https://user-images.githubusercontent.com/3152567/93379378-09029580-f85e-11ea-8bb4-127676ecfa92.png)

**Comment by luco5826** [comment]
Thank you very much! Didn't know about that!
