### ISSUE TITLE
Frames

### ISSUE THREAD

**Issue by c4tom** [vkohaupt/vokoscreenNG#109]
first, thanks for developing this software, it meets my needs

however, in version 3.0.6 which I installed today, it does not allow configuring frames less than 10, in version 2.x I was able to set 3, which I use to capture screens, and for me this quantity is satisfactory,

Why was it changed? please, can you start at 3 fps ???

**Comment by vkohaupt** [comment]
Such a small frame rate can lead to false colors and audio dropouts. Must not but can. And the file size is just 10% smaller and not 70% as you might think. So I leave it as it is.
Please understand.
