### ISSUE TITLE
[Feature request] Highlight a mouse click

### ISSUE THREAD

**Issue by unreal4u** [vkohaupt/vokoscreenNG#110]
Hi!

I'm using vokoscreenNG lately and wow, it's a very simple, no non-sense, straight to the point software, I really like it!

That being said, I can't find an option to; while recording a screencast; highlight a mouse click so that it is more obvious when you did click. There is an option to record or not the mouse cursor, but that's about it I'm afraid:
![Screenshot_2020-09-23_16-17-36](https://user-images.githubusercontent.com/194999/94024979-4f08ad80-fdb8-11ea-9d3f-4c7a0bc0a003.png)

FWIW: I am using vokoscreenNG v3.0.6 (installed via `dnf`) on a Fedora 32 machine, with XFCE as desktop manager.

Greetings.

**Comment by mikeperalta1** [comment]
+1 This would be cool

**Comment by nalam002** [comment]
@unreal4u In the meantime, you can use a freeware program or extension to highlight the cursor when keeping the option to record cursor on in vokoscreen. I personally use Professor Luc Boisvert's cursor highlighter tool: 
https://sites.google.com/site/boisvertlab/computer-stuff/online-teaching
(I think the mouse clicks aren't animated by default for the tool, you would have to go to setting and turn them on)

**Comment by stillpointx** [comment]
It used to be an option but it was taken out for some reason (not sure why).


![screenshot-2020-12-19-11-23-00](https://user-images.githubusercontent.com/28985314/102695658-b8049380-41f6-11eb-8190-5e45a604dbbb.png)

**Comment by vkohaupt** [comment]
I work on it, as external program.
https://github.com/vkohaupt/vokoShowClick
