### ISSUE TITLE
old release for XP

### ISSUE THREAD

**Issue by andika207** [vkohaupt/vokoscreenNG#112]
hello.
where can I download the last release with support for Windows Vista and XP ?

**Comment by vkohaupt** [comment]
You saved my day :>)

https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.computer-bild.de%2Fimgs%2F7%2F8%2F6%2F4%2F4%2F3%2F9%2FZukunftstaugliche-Software-Basis-658x370-a2aa08fb2796ebc6.jpg&imgrefurl=https%3A%2F%2Fwww.computerbild.de%2Fartikel%2Fcb-Tipps-Software-Windows-Vista-Support-Ende-Updates-15361035.html&tbnid=P0I0qk0B15-QdM&vet=12ahUKEwiVyKbw-5vsAhWL0oUKHR8nBiMQMygAegUIARCiAQ..i&docid=SxBgyiWu1ivZXM&w=658&h=370&q=support%20ende%20xp%20vista&client=firefox-b-d&ved=2ahUKEwiVyKbw-5vsAhWL0oUKHR8nBiMQMygAegUIARCiAQ

**Comment by andika207** [comment]
@vkohaupt where is the link ? I don't know why all the releases are not listed here.

**Comment by tuxmuck** [comment]
Vokoscreen for Vista or XP is not available.

**Comment by andika207** [comment]
@tuxmuck @vkohaupt I know it's not available and because of this I am here requesting a link of the legacy version.

**Comment by vkohaupt** [comment]
Please read here the section History.
https://linuxecke.volkoh.de/vokoscreen/vokoscreen.html

And here the last section.
https://linuxecke.volkoh.de/vokoscreen/vokoscreen-download.html

**Comment by andika207** [comment]
@vkohaupt OK. January 2020. almost a year after XP EOL (April 2019) but there are people that will still be getting updates till 2025

**Comment by andika207** [comment]
@tuxmuck what other similar alternatives do you recommend ?

**Comment by krystian3w** [comment]
What paid updates for XP to 2025?
