### ISSUE TITLE
VokoscreeenNG doesn't detect external microphone

### ISSUE THREAD

**Issue by aarontrom** [vkohaupt/vokoscreenNG#113]
Hello,

first of all, thank you so much for providing this awesome plugin. I want to use it to record my screen, however vokoscreen doesn't detect the audio input from both the webcam and the microphone, despite my computer detecting all these audio inputs successfully. 

Here's a screenshot:
![vokoscreen issue](https://user-images.githubusercontent.com/69819346/95477812-0856ae00-0989-11eb-91eb-e9c7a42fc3f2.png)

You can see that Vokoscreen detects 2 times "8 Series HD Audio Controller Analog Stereo". I guess this is the internal microphone from my computer (which is a 2012 macbook, but the OS is Manjaro), but everytime I recorded with these, no sound got recorded. So today I bought a webcam with a built in microphone and also even an external microphone (both are connected via USB) and my computer detects both of them, but Vokoscreen not...

Edit: Vokoscreen does connect the webcam as a camera, but as I wrote not the built in microphone.
Edit 2: I installed PulseAudio and played a bit with the settings, but the issue remains. 

What can I do?

Any help much appreciated
Aaron

**Comment by vkohaupt** [comment]
First:
open a terminal and enter the following
pactl list short sources
copy the output and post here

second:
open a terminal and enter the following
gst-device-monitor-1.0
copy the output and post here

If the command pactl and gst-device-monitor-1.0 not installed you must install.

**Comment by aarontrom** [comment]
First: 
`[aaron@aaron-pc ~]$ pactl list short sources
1	alsa_input.pci-0000_00_1b.0.analog-stereo	module-alsa-card.c	s16le 2ch 44100Hz	SUSPENDED
5	alsa_output.pci-0000_00_1b.0.analog-stereo.monitor	module-alsa-card.c	s16le 2ch 44100Hz	SUSPENDED
6	alsa_input.usb-046d_0825_7CA0A420-02.mono-fallback	module-alsa-card.c	s16le 1ch 48000Hz	RUNNING
12	rtp.monitor	module-null-sink.c	s16be 2ch 44100Hz	RUNNING`

Second:
`[aaron@aaron-pc ~]$ gst-device-monitor-1.0
Probing devices...

INTEL-MESA: warning: Haswell Vulkan support is incomplete

Device found:

	name  : 8 Series HD Audio Controller Analog Stereo
	class : Audio/Sink
	caps  : audio/x-raw, layout=interleaved, format={ (string)S32LE, (string)S16LE }, rate=[ 32000, 192000 ], channels=2
	properties:
		object.path = alsa:pcm:1:front:1:playback
		api.alsa.path = front:1
		api.alsa.pcm.card = 1
		api.alsa.pcm.stream = playback
		audio.channels = 2
		alsa.resolution_bits = 16
		device.api = alsa
		device.class = sound
		alsa.class = generic
		alsa.subclass = generic-mix
		alsa.name = "CS4208\ Analog"
		alsa.id = "CS4208\ Analog"
		alsa.subdevice = 0
		alsa.subdevice_name = "subdevice\ \#0"
		alsa.device = 0
		alsa.card = 1
		alsa.card_name = "HDA\ Intel\ PCH"
		alsa.long_card_name = "HDA\ Intel\ PCH\ at\ 0xb0a14000\ irq\ 73"
		alsa.driver_name = snd_hda_intel
		device.profile.name = analog-stereo
		device.profile.description = "Analog\ Stereo"
		card.profile.device = 1
		device.id = 34
		factory.name = api.alsa.pcm.sink
		priority.driver = 945
		priority.session = 945
		media.class = Audio/Sink
		node.nick = "HDA\ Intel\ PCH"
		node.name = alsa_card.pci-0000:00:1b.0.playback.0.0
		node.description = "8\ Series\ HD\ Audio\ Controller\ Analog\ Stereo"
		factory.id = 18
		client.id = 31
		node.driver = true
		factory.mode = merge
		audio.adapt.follower = ""
		library.name = audioconvert/libspa-audioconvert
		object.id = 39
	gst-launch-1.0 ... ! pipewiresink path=39


Device found:

	name  : 8 Series HD Audio Controller Analog Stereo
	class : Audio/Source
	caps  : audio/x-raw, layout=interleaved, format={ (string)S32LE, (string)S16LE }, rate=[ 8000, 96000 ], channels=2
	properties:
		object.path = alsa:pcm:1:front:1:capture
		api.alsa.path = front:1
		api.alsa.pcm.card = 1
		api.alsa.pcm.stream = capture
		audio.channels = 2
		alsa.resolution_bits = 16
		device.api = alsa
		device.class = sound
		alsa.class = generic
		alsa.subclass = generic-mix
		alsa.name = "CS4208\ Analog"
		alsa.id = "CS4208\ Analog"
		alsa.subdevice = 0
		alsa.subdevice_name = "subdevice\ \#0"
		alsa.device = 0
		alsa.card = 1
		alsa.card_name = "HDA\ Intel\ PCH"
		alsa.long_card_name = "HDA\ Intel\ PCH\ at\ 0xb0a14000\ irq\ 73"
		alsa.driver_name = snd_hda_intel
		device.profile.name = analog-stereo
		device.profile.description = "Analog\ Stereo"
		card.profile.device = 0
		device.id = 34
		factory.name = api.alsa.pcm.source
		priority.driver = 1945
		priority.session = 1945
		media.class = Audio/Source
		node.nick = "HDA\ Intel\ PCH"
		node.name = alsa_card.pci-0000:00:1b.0.capture.0.0
		node.description = "8\ Series\ HD\ Audio\ Controller\ Analog\ Stereo"
		factory.id = 18
		client.id = 31
		node.driver = true
		factory.mode = split
		audio.adapt.follower = ""
		library.name = audioconvert/libspa-audioconvert
		object.id = 40
	gst-launch-1.0 pipewiresrc path=40 ! ...


Device found:

	name  : Apple Facetime HD
	class : Video/Source
	caps  : video/x-raw, format=YUY2, width=1280, height=720, framerate=30/1
	        video/x-raw, format=YVYU, width=1280, height=720, framerate=30/1
	properties:
		object.path = v4l2:/dev/video0
		device.api = v4l2
		media.class = Video/Source
		api.v4l2.path = /dev/video0
		api.v4l2.cap.driver = facetimehd
		api.v4l2.cap.card = "Apple\ Facetime\ HD"
		api.v4l2.cap.bus_info = PCI:0000:02:00.0
		api.v4l2.cap.version = 5.4.67
		api.v4l2.cap.capabilities = 85200001
		api.v4l2.cap.device-caps = 05200001
		device.id = 35
		node.name = api.v4l2.source.v4l2_device.pci-0000:02:00.0
		node.description = "Apple\ Facetime\ HD"
		factory.name = api.v4l2.source
		factory.id = 10
		client.id = 31
		media.role = Camera
		node.pause-on-idle = false
		node.driver = true
		object.id = 41
	gst-launch-1.0 pipewiresrc path=41 ! ...


Device found:

	name  : UVC Camera (046d:0825)
	class : Video/Source
	caps  : video/x-raw, format=YUY2, width=640, height=480, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        video/x-raw, format=YUY2, width=160, height=120, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        video/x-raw, format=YUY2, width=176, height=144, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        video/x-raw, format=YUY2, width=320, height=176, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        video/x-raw, format=YUY2, width=320, height=240, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        video/x-raw, format=YUY2, width=352, height=288, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        video/x-raw, format=YUY2, width=432, height=240, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        video/x-raw, format=YUY2, width=544, height=288, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        video/x-raw, format=YUY2, width=640, height=360, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        video/x-raw, format=YUY2, width=752, height=416, framerate={ (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        video/x-raw, format=YUY2, width=800, height=448, framerate={ (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        video/x-raw, format=YUY2, width=800, height=600, framerate={ (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        video/x-raw, format=YUY2, width=864, height=480, framerate={ (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        video/x-raw, format=YUY2, width=960, height=544, framerate={ (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        video/x-raw, format=YUY2, width=960, height=720, framerate={ (fraction)10/1, (fraction)5/1 }
	        video/x-raw, format=YUY2, width=1024, height=576, framerate={ (fraction)10/1, (fraction)5/1 }
	        video/x-raw, format=YUY2, width=1184, height=656, framerate={ (fraction)10/1, (fraction)5/1 }
	        video/x-raw, format=YUY2, width=1280, height=720, framerate={ (fraction)15/2, (fraction)5/1 }
	        video/x-raw, format=YUY2, width=1280, height=960, framerate={ (fraction)15/2, (fraction)5/1 }
	        image/jpeg, width=640, height=480, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        image/jpeg, width=160, height=120, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        image/jpeg, width=176, height=144, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        image/jpeg, width=320, height=176, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        image/jpeg, width=320, height=240, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        image/jpeg, width=352, height=288, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        image/jpeg, width=432, height=240, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        image/jpeg, width=544, height=288, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        image/jpeg, width=640, height=360, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        image/jpeg, width=752, height=416, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        image/jpeg, width=800, height=448, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        image/jpeg, width=800, height=600, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        image/jpeg, width=864, height=480, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        image/jpeg, width=960, height=544, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        image/jpeg, width=960, height=720, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        image/jpeg, width=1024, height=576, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        image/jpeg, width=1184, height=656, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        image/jpeg, width=1280, height=720, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	        image/jpeg, width=1280, height=960, framerate={ (fraction)30/1, (fraction)25/1, (fraction)20/1, (fraction)15/1, (fraction)10/1, (fraction)5/1 }
	properties:
		object.path = v4l2:/dev/video1
		device.api = v4l2
		media.class = Video/Source
		api.v4l2.path = /dev/video1
		api.v4l2.cap.driver = uvcvideo
		api.v4l2.cap.card = "UVC\ Camera\ \(046d:0825\)"
		api.v4l2.cap.bus_info = usb-0000:00:14.0-2
		api.v4l2.cap.version = 5.4.67
		api.v4l2.cap.capabilities = 84a00001
		api.v4l2.cap.device-caps = 04200001
		device.id = 52
		node.name = api.v4l2.source.v4l2_device.pci-0000:00:14.0-usb-0:2:1.0
		node.description = "UVC\ Camera\ \(046d:0825\)"
		factory.name = api.v4l2.source
		factory.id = 10
		client.id = 31
		media.role = Camera
		node.pause-on-idle = false
		node.driver = true
		object.id = 49
	gst-launch-1.0 pipewiresrc path=49 ! ...


Device found:

	name  : Intel(R) Iris(R) Graphics 5100 (HSW GT3)
	class : Video/Sink
	caps  : video/x-raw(memory:VulkanImage)
	properties:
		vulkan.name = "Intel\(R\)\ Iris\(R\)\ Graphics\ 5100\ \(HSW\ GT3\)"
		vulkan.type = integrated
		vulkan.api.version = 1.2.131
		vulkan.api.version.major = 1 (0x00000001)
		vulkan.api.version.minor = 2 (0x00000002)
		vulkan.api.version.patch = 131 (0x00000083)
		vulkan.driver.version = 20.1.8
		vulkan.driver.version.major = 20 (0x00000014)
		vulkan.driver.version.minor = 1 (0x00000001)
		vulkan.driver.version.patch = 8 (0x00000008)
		vulkan.vendor.id = 32902 (0x00008086)
		vulkan.device.id = 2606 (0x00000a2e)
		vulkan.memory.n_heaps = 1 (0x00000001)
		vulkan.memory.heaps.0.size = 1610612736
		vulkan.memory.heaps.0.flags = 1 (0x00000001)
		vulkan.memory.heaps.0.flags.str = device-local
		vulkan.memory.n_types = 1 (0x00000001)
		vulkan.memory.types.0.heap = 0 (0x00000000)
		vulkan.memory.types.0.flags = 15 (0x0000000f)
		vulkan.memory.types.0.flags.str = "device-local\|host-visible\|host-coherent\|host-cached"
		vulkan.n_queue_families = 1 (0x00000001)
		vulkan.queue_family.0.n_queues = 1 (0x00000001)
		vulkan.queue_family.0.flags = 7 (0x00000007)
		vulkan.queue_family.0.flags.str = "graphics\|compute\|transfer"
		vulkan.queue_family.0.timestamp_resolution = 36 (0x00000024)
		vulkan.queue_family.0.min_image_transfer_granuality.width = 1 (0x00000001)
		vulkan.queue_family.0.min_image_transfer_granuality.height = 1 (0x00000001)
		vulkan.queue_family.0.min_image_transfer_granuality.depth = 1 (0x00000001)
		is-default = true
	gst-launch-1.0 ... ! vulkansink
`

**Comment by vkohaupt** [comment]
First:
PulseAudio identify your usb microphone alsa_input.usb-046d_0825_7CA0A420-02.mono-fallback

Second:
GStreamer identify not your microphone.
This is where the GStreamer 1.16.x and 1.18 are broken

Hint:
vokoscreenNG 3.0.0  to  3.0.6 identify Audio recording devices over GStreamer.
vokoscreenNG 3.0.7 identify Audio recording devices directly by Pulseaudio.

The best way is you install vokoscreenNG 3.0.7

**Comment by aarontrom** [comment]
I searched in add/remove software in Manjaro, and there is only Version 3.0.4-3 in the official repositories. 
I guess I just need to wait for the updates then. 

![vokoscreen in manjaro repositories](https://user-images.githubusercontent.com/69819346/95502773-a018c400-09aa-11eb-8f6d-b522938dae7b.png)

Thanks for your help @vkohaupt 
I'll write here again if it works after I get the update to 3.0.7 (in case I don't forget to write here :))

**Comment by vkohaupt** [comment]
There is a vokoscreen-git in the picture. Install and reports here.

**Comment by aarontrom** [comment]
Haha too easy! It works! Thanks a lot :)
