### ISSUE TITLE
[Feature request] Record Microphone + Internal Audio together on Windows

### ISSUE THREAD

**Issue by nalam002** [vkohaupt/vokoscreenNG#114]
Forgive me if this is already possible and a problem on my end, but in the Windows release, I can only select my Microphone under Directsound options. Under the WASAPI options, I can select EITHER Microphone OR Speakers (=internal audio), but not both at the same time. 

Is there any way to select both? If not, I'd like to request the feature in a future release.

**Comment by athan01** [comment]
No it's not your end. I have the same issue. I would like to second that request. Also an issue for which I don't open a new thread is that all the info buttons are inactive and the final output file is twice the size of similar applications. Though you might think that the preset of quality at 17 is low it gives a rather large file.

**Comment by vkohaupt** [comment]
The Info buttons are a online-help and this need a functioning network.

Quality:
high 0 <----------------------> 50 low

If i need a smaller file size by same CPU-Load i use quality e.g. 23

If i have a big machine i set the Preset "medium" and quality 23 then i have one more smaller file.

The default settings is a compromise between screen-size, cpu-load, quality and file-size.

**Comment by vkohaupt** [comment]
@nalam002
The problem is known and it is looking for a solution.
