### ISSUE TITLE
Help buttons disabled

### ISSUE THREAD

**Issue by jEsuSdA** [vkohaupt/vokoscreenNG#116]
Hi!

My help buttons (near each option and configuration values) are no functional. No any window is lauched with help when clicked.

Any idea about how to solving this o any link to access all help through web browser?

Thanks!

**Comment by vkohaupt** [comment]
This is an online help. A functioning network connection to the Internet is required. If a network connection exists but the help buttons are deactivated, consult the vokoscreenNG maintainer that all QT packages are provided for this.
