### ISSUE TITLE
Wayland

### ISSUE THREAD

**Issue by vkohaupt** [vkohaupt/vokoscreenNG#118]
Happy news, yesterday I was able to create a smooth video for the first time with my test application. On my machine and a screen of 1920x1080, I got up to 85 fps. All of this without sound and without a mouse cursor.
The minimum requirements are KDE Plasma 5.20.2 and a current pipewire.

**Comment by athan01** [comment]
Hello,
That's good news indeed. About Windows version. Did you read my email? I have to report some more observations if you don't mind. As I told you the first issue was that you couldn't select both speakers and microphone recording to wasapi. In addition to this the first recording after every launch of the program after reboot has a problem with the sound but if you stop recording and start a new one it goes away. I installed it to a different system and there it was crashing when you ask recording from speakers. Microphone recording works with all options availlable. Meaning even if you choose a disconnected microphone sound is going still to be recorded. I hope I don't bother you and if you like I can give you more info on some bugs to windows version. By the way on that second system the info buttons work but still not to the first one.

**Comment by vkohaupt** [comment]
Thank you for the information.
Please create an "issue" for each bug. So that I can concentrate on one task.
1. Description of the bug.
2. Always use the latest version of vokoscreenNG.
3. Basically I need the log from vokoscreenNG after "Start" and "Stop" a recording.
4. Then please describe step by step what leads to the error.

Please Read:
https://www.mediawiki.org/wiki/How_to_report_a_bug

Thank for your help.
