### ISSUE TITLE
Keyboard shortcut override ability

### ISSUE THREAD

**Issue by molokovskikh** [vkohaupt/vokoscreenNG#120]
Hello Volker!
Shortcut hardcoded into QvkGlobalShortcut/QvkGlobalShortcut.cpp now.
I will be apreciate if you can add override keyboard shortcut feature in vokoscreenNG.ini.

**Comment by vkohaupt** [comment]
Global keyboard shortcuts can be changed in the next 3.1.0 Version
For Windows find a pre version here
https://linuxecke.volkoh.de/vokoscreen/vokoscreen-download.html

**Comment by molokovskikh** [comment]
> Global keyboard shortcuts can be changed in the next 3.1.0 Version For Windows find a pre version here https://linuxecke.volkoh.de/vokoscreen/vokoscreen-download.html

Great. Thx friend.
