### ISSUE TITLE
Update Debian package, or a PPA repository

### ISSUE THREAD

**Issue by ralienpp** [vkohaupt/vokoscreenNG#121]
Hi, I was about to report a bug that occurs in dual-screen configurations, but after reading the instructions I understand that there is an intermediate issue.

I am using v3.0.2 installed with `apt install vokoscreen-ng`, per instructions. The bug report template tells me that I should ensure I am running the latest version of the software. Although v3.0.7 is available in principle, the latest one in the Debian repos is still v3.0.2 - so I cannot try the newer one.

Is it possible to set up a PPA where fresher packages will be available? Or as an alternative, perhaps it is possible to ensure the newer versions are available in the standard repositories?

**Comment by vkohaupt** [comment]
Please speak with Debian Maintainer he must make a update to 3.0.7

Sarcasm:
Otherwise I will write in the next version an addition to the GPL "Not vor Debian"

**Comment by vkohaupt** [comment]
You may also be able to install a snap. The 3.0.7 is available there.
