### ISSUE TITLE
Always use all audio inputs per default

### ISSUE THREAD

**Issue by g6094199** [vkohaupt/vokoscreenNG#123]
Hi,

i'm using an Thinkpad laptop with docking station and monitor with external microphone, speakers and webcam. 

![Bildschirmfoto vom 2020-11-17 09-49-21](https://user-images.githubusercontent.com/37833326/99368226-2c2bde80-28bb-11eb-9f07-d2348eb4b777.png)

Thus i have changing audio and video inputs when being docked/undocked. Vokoscreen doesnt honor that atm. Every time i dock in i have to reselect the audio/video channels for recording. Sometimes i miss this step and end up with non audio videos. :-(

Possible solutions:
A: enable all visible audio inputs when VS is started.
B: remember the selected inputs audio/video in the config and do the setting on start when things are visible (i like that most)

sash

**Comment by vkohaupt** [comment]
I ask out of interest, do you really use all 5 recording devices in one session?

**Comment by g6094199** [comment]
No, i dont use all of them in parallel (3 out of 5 ervery time), 

but since i dock on/off several times a day and do several recordings its annoying when the application "forgets" the previous settings.

sash

**Comment by vkohaupt** [comment]
As a workaround, you can create two scripts, one without a doking station and one with a doking station.
First you save the vokoscreenNG.ini without the doking station and then the vokoscreenNG.ini with the doking station. And give them appropriate names.
Then you create two scripts by copying the respective vokoscreenNG.ini into the folder ~ /.config/vokoscreenNG

For example:
```
#!/bin/bash
copy withDoking.ini ~/.config/vokoscreenNG/vokoscreenNG.ini
vokoscreenNG
```

```
#!/bin/bash
copy withOutDoking.ini ~/.config/vokoscreenNG/vokoscreenNG.ini
vokoscreenNG
```

Now place the two scripts on the desktop.
