### ISSUE TITLE
audio equalizer

### ISSUE THREAD

**Issue by mbfakourii** [vkohaupt/vokoscreenNG#124]
hi Please put an audio equalizer in the audio tab to check if the audio is being recorded in the record.
I recorded an important recording without sound! ‌‌ :(

@vkohaupt

**Comment by vkohaupt** [comment]
Equalizer? I think you mean an audio volume meter, like this.
![volume-meter](https://user-images.githubusercontent.com/3152567/100090808-0de25780-2e54-11eb-93d0-424c9fb80719.png)

**Comment by mbfakourii** [comment]
Yes, show the microphones exactly when they are recording, which one they are recording with and whether there is sound or not.

**Comment by dpalic** [comment]
+1

**Comment by dpalic** [comment]
The why behind my query: sadly under linux it is not so obvious to see if you have selected the right channel for recording in vokoscreen. So I have had recordings there the audio was missing :( and all because you do not see the audio level during recording.
No level => no audio

**Comment by vkohaupt** [comment]
To Time i work on vokoShowClick
https://github.com/vkohaupt/vokoShowClick
Thanks for understanding
