### ISSUE TITLE
c922 pro webcam not working

### ISSUE THREAD

**Issue by superJK921** [vkohaupt/vokoscreenNG#125]
my logitech c922 pro webcam is not working as in when I click the check box next to "Webcam" it shows the webcam window but it just shows a black screen and the webcam works on the old vokoscreen but the webcam fotage on the old vokoscreen is very laggy.
[Video.zip](https://github.com/vkohaupt/vokoscreenNG/files/5624010/Video.zip)

**Comment by superJK921** [comment]
It work but on my 1600x900 screen on a gigabyte Geforce GTX 750 TI it lags unless I choose 640x480 even though my monitor supports 1920x1080

**Comment by vkohaupt** [comment]
I can see on your Video nothing.
Mediainfo say: qpmin=50 / qpmax=50

Please reset the settings. Go to the fourth tab and check the box under "Reset all settings on next start". Close vokoscreenNG and start it again and make a new video.

**Comment by superJK921** [comment]
> It work but on my 1600x900 screen on a gigabyte Geforce GTX 750 TI it lags unless I choose 640x480 even though my monitor supports 1920x1080

Will this help with fixing it and it's odd because I just install it

**Comment by vkohaupt** [comment]
I do not understand what you mean. Please tell us step by step your problem.
