### ISSUE TITLE
Missing options of Showkey and Showclick in new versions.

### ISSUE THREAD

**Issue by stillpointx** [vkohaupt/vokoscreenNG#127]
Missing options to Showkey and Showclick in new versions.

PS: I'm running Ubuntu 20.04
![screenshot-2020-12-19-11-23-00](https://user-images.githubusercontent.com/28985314/102694087-c77edf00-41ec-11eb-923d-e80fa0cc406d.png)

**Comment by vkohaupt** [comment]
I have good news, Showclick is coming as an external program in 2021.
https://github.com/vkohaupt/vokoShowClick
https://github.com/vkohaupt/vokoShowClick/blob/main/README.md
