### ISSUE TITLE
Segmentation fault when having intel-vaapi-driver

### ISSUE THREAD

**Issue by trmdi** [vkohaupt/vokoscreenNG#128]
It crashes on start whenever I install `intel-vaapi-driver` on my openSUSE Tumbleweed.
After removing it, voko runs normally.

**Comment by rolandog** [comment]
I was having the same problem (though on Ubuntu 20.10); I resolved it (temporarily) by installing `intel-media-va-driver-non-free` instead of `intel-media-va-driver`.

**Comment by vkohaupt** [comment]
@trmdi 
I have this test on an native Intel Tumbleweed machine, vokoscreenNG starts fine.
But since there is always trouble with it, I have removed all code for VAAPI.
I also lack the know-how to get this under control.
