### ISSUE TITLE
Segmentation fault when install qt5dxcb-plugin

### ISSUE THREAD

**Issue by thiagoandrade01** [vkohaupt/vokoscreenNG#129]
Hi Volker,
A Bug was related on Debian and its affect others OS based on Debian too.
VokoscreenNG is crashing with a segmentation fault when have installed this plugin in the machine: qt5dxcb-plugin.[1]
Debian distribution will go into a freeze period [2] in the coming months for the release of the new version (Debian 11 - bullseye), it would be interesting if possible to be able to upload a new version of vokoscreenNG already fixed.
Thanks

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=979312
[2] https://release.debian.org/bullseye/freeze_policy.html

**Comment by rolandog** [comment]
Could this be related to #128? Maye a dependency on `intel-media-va-driver-non-free` instead of `intel-media-va-driver` for that particular plugin? (Just thought it odd that two segmentation faults were reported hours apart).

**Comment by vkohaupt** [comment]
@andrade87
Please test from default branch.
git clone https://github.com/vkohaupt/vokoscreenNG.git
without the package gstreamer1.0-vaapi and without the package intel-media-va-driver.
Reason, i have VAAPI removed.
