### ISSUE TITLE
Audio recording Cam and Monitor of .. don't work together

### ISSUE THREAD

**Issue by agaida** [vkohaupt/vokoscreenNG#13]
Can only chose Webcam or Monitor of Internes Audio Audio Analog Stereo - if selected both only the webcam is recorded.

Source: Latest Git

**Comment by vkohaupt** [comment]
Six hard day and the bug is out. It was an implementation error, instead of bundling the sources, I had muxed an audio track for each audio source.

**Comment by agaida** [comment]
Cool, thanks a lot :)
