### ISSUE TITLE
Custom area 

### ISSUE THREAD

**Issue by Manssizz** [vkohaupt/vokoscreenNG#132]
i have issue when record in custom area and set maximize window custom height vokoscreen record fullscreen. but if i set height almost maximize height size, vokoscreen work perfectly. previous version work perfect even i set max size of my screen

VokoscreenNG 3.0.7 with Kali linux 2020.02 

https://user-images.githubusercontent.com/23637327/104133239-e9671e00-53b4-11eb-8537-1a596ce25a91.mp4
https://user-images.githubusercontent.com/23637327/104133243-ea984b00-53b4-11eb-9303-8e4414352090.mp4

**Comment by vkohaupt** [comment]
https://linuxecke.volkoh.de/vokoscreen/vokoscreen-changes.html
Area: Removed predefined areas. Reason: Not intuitiv, design is broken and Recording error.
