### ISSUE TITLE
Feature request: preview screen and audio indicator

### ISSUE THREAD

**Issue by aaannndddyyy** [vkohaupt/vokoscreenNG#134]
I have run into he problem of recordings with missing audio and frozen video several times now.
The original video and sound are running fine and not frozen, and vokoscreenNG 3.0.7 says it is recording fine, but it isn't. And I cannot find out until I stop the recording and view the recorded video. 
But then it is too late to start to record again.
Sometimes, it records perfectly fine. Sometimes, the video is fine but there is no sound. Sometimes, even the video freezes and only sound is there, sometimes video and sound have issues. While I hope those issues can be solved, it would be a nice thing to have some indication in vokoscreen itself that helps determine whether everything is working fine, like in obs:

a preview window showing the live video currently recorded 
and a graphic audio indicator that shows the currently recorded audio activity

Thank you.

EDIT: I just corrected my own typos in the edit

**Comment by vkohaupt** [comment]
Thanks for feature request.

**Comment by aaannndddyyy** [comment]
I hope it is something easy and does not involve too much work, and may come soon, as it's really important to me to know whether it is recording fine or not.

Danke für vokoscreenNG!
