### ISSUE TITLE
Redirect old domain and GitHub repo?

### ISSUE THREAD

**Issue by dandv** [vkohaupt/vokoscreenNG#136]
Hi, thanks for making Vokoscreen!

I learned about this software from [this page](https://www.unixmen.com/vokoscreen-a-new-screencasting-tool-for-linux/). It points to http://www.kohaupt-online.de/hp/. Now that's "Server not found". 

Then I saw it mentioned at https://itsfoss.com/vokoscreenng/. That points to https://github.com/vkohaupt/vokoscreen.

All these links are now broken and don't point to NG. To prevent losing users this way, it would help to redirect the old links, at least the old GitHub repo, to the NG one.

**Comment by vkohaupt** [comment]
There is no going back. I don't shed tears. I'm just looking ahead.

**Comment by dandv** [comment]
Um... I'm not suggesting supporting the old versions. Just not making other users shed tears that they can't find the current one.

Maybe the old domain is gone, but the old GitHub repo could have just a README file pointing to this one.

**Comment by vkohaupt** [comment]
https://github.com/vkohaupt/vokoscreen
Thanks for the hint.

**Comment by dandv** [comment]
Thanks for the quick fixes!
