### ISSUE TITLE
New Beta

### ISSUE THREAD

**Issue by vkohaupt** [vkohaupt/vokoscreenNG#14]
After half a year of intensive work, I have today released the 2.9.9 beta. I hope it's the last beta but I can not promise it. Thank you for testing and feedback.

**Comment by eribertomota** [comment]
Hi Volker! Thanks for your nice work again.

After some months in NEW queue, vokoscreenNG was accepted in Debian. I recommend subscribe to the package[1] to receive bugs and news. Please, click over 'logs' link when the page[1] show it to see building issues (Hurd is not building). Or search for vokoscreen-ng here[2].

[1] https://tracker.debian.org/pkg/vokoscreen-ng
[2] https://buildd.debian.org

Some moments ago I sent the 2.9.9~beta version to unstable (Sid). It will be built and shown today.

Here[3] you can see the git repository for packaging. Inside debian/ there are some useful news. I made a manpage (full reviewed for the first upload) and .desktop file and its icons (see debian/menu/).

[3] https://salsa.debian.org/debian/vokoscreen-ng

Cheers,

Eriberto

**Comment by eribertomota** [comment]
Complementing, I will remove the old vokoscreen (ffmpeg) from Debian when #12 is fixed.

**Comment by MurzNN** [comment]
Thanks, this deb package also succesfully installs on Ubuntu 19.10! I test it, and find no serious issues.
