### ISSUE TITLE
How to make install?

### ISSUE THREAD

**Issue by teterkin** [vkohaupt/vokoscreenNG#140]
Hello!
How do I install vokoscreenNG to default Linux locations like /usr/bin/vokoscreenNG?
I have compiled from source on Ubuntu 20.10 using instructions from INSTALL file.

Also I had to install intel-media-va-driver-non-free package to get rid off nasty "Segmentation Fault" error.

Now I have working binary file at $HOME/SRC/vokoscreenNG/src location.
**How do I move it to default permanent location?** (I couldn't find make install target)

Build version is 3.0.9 pre alfa.
By the way, **How do I install stable version from source code?**

Best regards,
Alexander.

**Comment by vkohaupt** [comment]
>  Also I had to install intel-media-va-driver-non-free package to get rid off nasty "Segmentation Fault" error.

Since VAAPI only causes trouble, I removed all VAAPI support.
Reason: In each disribution the packages have different names and it will be the most different packages needed. And there is no plausible connection between the packages.

Please test again. Thanks.

**Comment by teterkin** [comment]
> > Also I had to install intel-media-va-driver-non-free package to get rid off nasty "Segmentation Fault" error.
> 
> Since VAAPI only causes trouble, I removed all VAAPI support.
> Reason: In each disribution the packages have different names and it will be the most different packages needed. And there is no plausible connection between the packages.
> 
> Please test again. Thanks.

I have just pulled the source and recompiled with qmake and make.
After that vokoscreenNG was running fine.
Next, I removed intel-media-va-driver package and tried to run again:
```
$ ./vokoscreenNG 
Segmentation fault (core dumped)
```

**Comment by teterkin** [comment]
> **How do I move it to default permanent location?** (I couldn't find make install target)

Actually I have found that binary file uses libraries at default locations.
So I can manually copy it wherever I like (for example to /usr/bin directory).

The only question left is: **How do compile specific version of software? For example v. 3.0.8.**

**Comment by vkohaupt** [comment]
Make-Install or copy from hand is one of the worst solutions on Linux. Build a package for your distribution. Look at Debian or Ubuntu how it works.

wget https://github.com/vkohaupt/vokoscreenNG/archive/3.0.8.tar.gz

**Comment by teterkin** [comment]
Thank you! :+1:
