### ISSUE TITLE
Help text is invalid under Ubuntu 20.04 for installing x264 codecs

### ISSUE THREAD

**Issue by xandark** [vkohaupt/vokoscreenNG#142]
In vokoscreenNG 3.0.8 running under Ubuntu 20.04, in the audio/video format tab, if I click on the top-right info icon under Tux the penguin, the Help window displays information that isn't valid anymore. It says:

> If the Codec x264 is shown as not available, it can be installed. Open a terminal and enter the following.  `sudo apt install ubuntu‑restricted‑extras`

Well, under Ubuntu 20.04, that package doesn't exist anymore. Verifying this at the Ubuntu Package Search page, the service reports that ubuntu‑restricted‑extras doesn't exist in 20.04 "focal":

https://packages.ubuntu.com/search?searchon=contents&keywords=ubuntu%E2%80%91restricted%E2%80%91extras&mode=exactfilename&suite=focal&arch=any

Which package should be installed (and the text updated to reflect it) for 20.04? 

For example, I notice that the only encoding video format that I can choose is VP8. I have ffmpeg installed, BTW.

**Comment by xandark** [comment]
P.S. this is a great utility!

**Comment by vkohaupt** [comment]
The package exist, but the text was wrong for copy. My mistake.
Please test it again.

**Comment by xandark** [comment]
I'm sorry, I don't understand your reply. If I go to https://packages.ubuntu.com/ and scroll down and type "ubuntu‑restricted‑extras" into the Search package directories field, select "focal" from the Distribution dropdown menu, the result that comes back is that there was no package named ubuntu‑restricted‑extras that was found in Ubuntu 20.04 "focal". 

I also looked in the most recent commit comments past 3.0.8, and I don't see any mention of a change to the help file. Could you point me at the correct commit for me to test? Thank you.

**Comment by vkohaupt** [comment]
You have in your Package Name a wrong character "-"

wrong ubuntu‑restricted‑extras
good ubuntu-restricted-extras

To better understand, copy this two rows into your email client and send this too yourself. And then show into the source code from the mail and you see the difference.

I become this:
wrong ubuntuâ€‘restrictedâ€‘extras
good ubuntu-restricted-extras

If you write with right ASCII characters then you see the package for Ubuntu 20.04 "focal"
https://packages.ubuntu.com/search?keywords=ubuntu-restricted-extras&searchon=names&suite=all&section=all

**Comment by xandark** [comment]
Aha! And yes, I was able to install the package now with the proper hypens.
