### ISSUE TITLE
Please provide support for AAC encoders other than vo-aacenc

### ISSUE THREAD

**Issue by patrakov** [vkohaupt/vokoscreenNG#143]
For some reason, Arch Linux dropped voaacenc from their repository, but there are other AAC encoders. It would be nice if vokoscreenNG could use them.

I am talking specifically about these plugins:

 * fdkaacenc
 * faac
 * avenc_aac

**Comment by patrakov** [comment]
```
[vokoscreenNG] Symbols: + available, - not available
[vokoscreenNG] + matroskamux
[vokoscreenNG] + webmmux
[vokoscreenNG] + avimux
[vokoscreenNG] + mp4mux
[vokoscreenNG] + qtmux
[vokoscreenNG] + x264enc
[vokoscreenNG] - openh264enc
[vokoscreenNG] - vaapih264enc
[vokoscreenNG] - vaapimpeg2enc
[vokoscreenNG] + vp8enc
[vokoscreenNG] + vorbisenc
[vokoscreenNG] + flacenc
[vokoscreenNG] + opusenc
[vokoscreenNG] + lamemp3enc
[vokoscreenNG] - voaacenc

[vokoscreenNG] + ximagesrc
[vokoscreenNG] + pulsesrc
[vokoscreenNG] - pipewiresrc
[vokoscreenNG] + queue
[vokoscreenNG] + capsfilter
[vokoscreenNG] + videoconvert
[vokoscreenNG] + videorate
[vokoscreenNG] + audioconvert
[vokoscreenNG] + audiorate
[vokoscreenNG] + filesink
[vokoscreenNG] + videoscale
[vokoscreenNG] + h264parse
[vokoscreenNG] + audiomixer
[vokoscreenNG] + adder
```

**Comment by vkohaupt** [comment]
I see the packages here.
https://aur.archlinux.org/packages/vo-aacenc/

You need also this packages.
https://aur.archlinux.org/packages/gst-plugins-bad-git/

**Comment by patrakov** [comment]
AUR is not really part of Arch. The point is, there are other AAC encoders and corresponding GStreamer plugins in proper Arch.

**Comment by vkohaupt** [comment]
Where can I see Arch packages?

**Comment by patrakov** [comment]
https://archlinux.org/packages/

**Comment by vkohaupt** [comment]
For linux i have changed to faac. I hope it is for all user so good.

**Comment by patrakov** [comment]
Well, you can't hard-code a single AAC encoder that way. This is bound to have problems on other distributions that care about Free Software, because faac has restrictions that other encoders don't. Please probe for all possible AAC encoders and choose one of them at runtime.

**Comment by vkohaupt** [comment]
For me, the topic of audio encoders is finished. I don't test 100 encoders for their functionality. Finally there are alternatives like Opus, Vorbis, flac and mp3. Every distribution will provide one of them. Same with mkv, webm, avi, mp4 and mov.

**Comment by slrslr** [comment]
Yes, on Arch based Manjaro Linux, i have aac installed:
```
libfdk-aac                                                                                                                                                   [Installed] 2.0.1-2    community 
    Fraunhofer FDK AAC codec library
faac                                                                                                                                                         [Installed] 1.30-2     extra 
    Freeware Advanced Audio Coder
```
yet Vokoscreen 3.0.8 does not detect it. All aac containing packages [here](https://bin.disroot.org/?b85b01d1aae561d5#6eXDpLkoVhEDo2yxfzTKwCgNTCvSK6GwRYqdjvdx2hAA).
If anyone have idea, please comment. Else i am currently using VP8 and Vorbis combination which also seems to be supported on old TV.
