### ISSUE TITLE
Pollutes video with a flicker of the screen capture area's border

### ISSUE THREAD

**Issue by aspiers** [vkohaupt/vokoscreenNG#144]
For example:

![vokoscreenNG-2021-02-25_18-30-04](https://user-images.githubusercontent.com/100738/109199616-91834b80-7797-11eb-88c5-7ffab0f094c8.gif)

This was captured as .webm / VP8 and then converted to .gif using ffmpeg.

**Comment by vkohaupt** [comment]
I have fixed this.
https://github.com/vkohaupt/vokoscreenNG/commit/91123dd6f73141cc4f21ce3c8e1d02d1c3479e14
Thanks for the hint.

**Comment by aspiers** [comment]
Amazing, thank you so much!!
