### ISSUE TITLE
FR: better keyboard shortcut to quit vokoscreenNG

### ISSUE THREAD

**Issue by aspiers** [vkohaupt/vokoscreenNG#146]
It seems that `Alt-F4` is the only shortcut which quits vokoscreenNG.  This is historically a Windows shortcut so not very consistent on Linux, and it's also quite awkward to type.  Perhaps `Control-q` or `Escape` could also be added as an alternative?

**Comment by vkohaupt** [comment]
Can you please show the position in the online help, I couldn't find it in a hurry. Then I can improve or expand it.

**Comment by vkohaupt** [comment]
I see over the source code and the onlinehelp. But i find nothing to Alt-F4.
This shortcut comes from your Desktop KDE, Gnome or other.
https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts#Window_management

**Comment by aspiers** [comment]
Sorry if I wasn't clear.  Please forget I even mentioned Alt-F4, it is not relevant.  I was asking for a "standard" shortcut for closing the app, like Control-q or Control-w or Escape.  As far as I can see, no such shortcut currently exists, forcing a dependency on using the window manager's way of quitting apps, which can result in a more violent way of killing the app than a graceful shutdown.
