### ISSUE TITLE
Mouse clicks visualization [feature]

### ISSUE THREAD

**Issue by zhum** [vkohaupt/vokoscreenNG#148]
Can you add ability to optionally visualize mouse clicks? It is very useful for some kinds of screencasts to indicate left, right clicks or double clicks.

**Comment by vkohaupt** [comment]
I work on it, this come as a external program.
https://github.com/vkohaupt/vokoShowClick

**Comment by tredondo** [comment]
[vokoShowClick](https://github.com/vkohaupt/vokoShowClick) is 404, any plans to implement this feature in NG? 🙏🏻
