### ISSUE TITLE
[typographic errata] Vocal missed in package name

### ISSUE THREAD

**Issue by RafaelLinux** [vkohaupt/vokoscreenNG#151]
Hi. Only a correction. In https://github.com/vkohaupt/vokoscreenNG#run-time-requirements there is a character missed:

gstreamer-plugins-bas   --> gstreamer-plugins-base

I was mad thinking what was my fault, and is only that little typographic error

Thank you for your great work!!!

**Comment by vkohaupt** [comment]
I changed it.
Thanks for the hint.
