### ISSUE TITLE
[Request] AppImage version for all Linux platforms

### ISSUE THREAD

**Issue by RafaelLinux** [vkohaupt/vokoscreenNG#152]
Hi

Usually, my Linux distro is two version behind your releases. However, Windows version is always up to date. It should be great if Linux users could have an AppImage version of vokoscreenNG. I read a [thread about it](https://github.com/vkohaupt/vokoscreenNG/issues/26) , however, I can't find any AppImage available to download in official website.

What about AppImage then?

Regards

**Comment by vkohaupt** [comment]
I close this issue. Maybe there is someone who creates an Appimage.

**Comment by delinuxco** [comment]
You may want to consider creating an official AppImage. I wanted to include VokoscreenNG in my Distro, but can't be done with FlatPak, at least not properly.

I already have a few AppImages as part of my ISO, Joplin, CinelerraGG and will include more.  

I would like to include your application, but without an AppImage, just can't do it.
