### ISSUE TITLE
Recorded volume too low, can not control easily

### ISSUE THREAD

**Issue by slrslr** [vkohaupt/vokoscreenNG#155]
Hello,
5.10.19-1-MANJARO + XFCE desktop, VokoscreenNG 3.0.8
what bothers me is that the recorded audio (recording what is played - system sounds, not microphone) is lower than videos recorded by other software, lets say movies and youtube downloaded videos. When i raise the system playback volume, the recording volume gets better. But then i forget to put volume back and get scared of too loud sounds.
Can you please add volume control (maybe let app to raised it during recording) with the default volume being set reasonably high to match videos from other sources, also remembering last user defined volume?
Thank you

**Comment by vkohaupt** [comment]
You must not play with the Volume that comes over the speakers. The better way is, you install pavucontrol  and start this. In the fourth tab you see the Monitor for the Playback-device(Speaker), set this to 100%.
Then go to the second Tab, it is empty. Start vokoscreenNG and start a record. Now you see in the tab vokoscreenNG, set this to 100%. Is the sound in the video too low set it higher.
These settings are stored independently of the volume.
