### ISSUE TITLE
Sometimes happen that the recorded video start lagging (~2 frames per second)

### ISSUE THREAD

**Issue by slrslr** [vkohaupt/vokoscreenNG#159]
Hello,

numerous times (i would guess maybe 2/5 times) when i have recorded video in vokoscreenNG 3.0.8 and then played it, i have found that after some time it start lagging - the playback is like 2 frames per second. Audio plays without problem.
**Same problem happen also when i record in different software**: https://github.com/MaartenBaert/ssr/issues/873
In both i am using MKV and Vorbis. In Vokoscreen it was mkv, x264, faster, high 4:4:4, quality 28, Vorbis.
I will now try veryfast preset and also VP8..

$ uname -r
`5.10.19-1-MANJARO (Linux)`
[full PC details](https://bin.disroot.org/?d1898b0539c2e4a8#GjRqKsJp8uTqxheHRBJnqFaGPZeFvpNMGowh7TfuGvHE) (password: aa)

[mediainfo](https://bin.disroot.org/?876f628954d19d7a#2YKNaikctvXSppaGYwwqn1LdU7zjrs9XkKTMuhM8zgDV) of the bad file

"vokoscreenNG --help" does not show any debug mode switch, maybe i should run it from command line to display reason for the failure?

**Comment by vkohaupt** [comment]
The RAM is to 80% full from 64GB
The system swapped
Processes: 571

You are work on Large Electron-Positron Collider?

**Comment by slrslr** [comment]
If i understand correctly, my swap is also located in RAM ([it is zswap](https://en.wikipedia.org/wiki/Zswap)) and the free SWAP/RAM figures stays quite constant totaling at least 8GB free and even if there is a spike, i am having NVMe system drive. So i can not believe RAM or system drive (where the video is recorded) can be the issue. Rather i would suspect the external USB HDD bottleneck that cause system to delay, but such delay i would not believe would last more than fraction of the second since most of the time i am watching this drive (this ext. USB drive is SSD) the Disk Performance Monitor shows less than 8% busy time and if i see a spike up to the 100% it is very rare and second fraction. So i do not know why the recording app would not be able to cope with this... or if there is a command that would help discover why the recorded video gets damaged (start recording 2 fps, till the video end, which seems like a bug).

**Comment by vkohaupt** [comment]
Can you provide a video for download?

**Comment by vkohaupt** [comment]
I have become the Video, thanks.
It is not ~2 FPS, it is exactly 1 FPS. After the first analysis, only the key frame will be used.

More analysis:
SSR used libav
vokoscreenNG used GStreamer

https://github.com/MaartenBaert/ssr/issues/873 used VP8
here used x264

I think the software is not the Problem.
Start your Machine without to fill the RAM, a pur Arche linux and test it.

**Comment by slrslr** [comment]
I updated system, reboot, launched web browser, played video and tried to record. Issue appeared again.
When i did the same on my second computer, which has same, updated system, it records without problem (i have recorded numerous times numerous hours of video without problem on this second computer). Where else may be the problem beside hardware kernel modules, can i run some commands during recording that may shed some light on this? and what to look for in the output, if output is large..

**Comment by vkohaupt** [comment]
Open a console and write the following. 
export GST_DEBUG_FILE=warning.txt
export GST_DEBUG=2
vokoscreenNG

Make a record.
Check the video to see if the error occurs.
Then provide the video and the warning.txt for download.

**Comment by slrslr** [comment]
I have tried 3 times to record today, yet the issue does not repeat, i will try again later and update there if the issue happen. Thank you

**Comment by slrslr** [comment]
@vkohaupt It happen again, i have sent you the details via e-mail for privacy reason. Thank you

**Comment by vkohaupt** [comment]
There is nothing noticeable in the log.
In second 4 and second five there are underflow. But nothing from the 20th second that would be important.

As next test you can change your graphics driver from
proprietary to opensource
or
opensource to proprietary

**Comment by vkohaupt** [comment]
I close this issues, as this is a computer specific problem.
