### ISSUE TITLE
Area selector widget can't moved to other screen in multiscreen configuration

### ISSUE THREAD

**Issue by MurzNN** [vkohaupt/vokoscreenNG#16]
in multiscreen configuration when I select Area capture type - selector widget are shown in screen, where Vokoscreen window is located, and can't be moved to other screen. This is not so serious for block near release, but will be good to fix in future.

**Comment by Martii** [comment]
Duplicate of #12

**Comment by MurzNN** [comment]
Yes, duplicate, sorry
