### ISSUE TITLE
Build error under Arch Linux, Qt 5.15.2

### ISSUE THREAD

**Issue by stefanhusmann** [vkohaupt/vokoscreenNG#160]
vokoscreen does not compile under Arch Linux, Qt 5.15.2.
[buildlog.txt](https://github.com/vkohaupt/vokoscreenNG/files/6229280/buildlog.txt)

**Comment by tux93** [comment]
Building with Qt 5.15.2 works fine on openSUSE Tumbleweed,  
are you maybe missing some dependency?

You can check our spec file here:
https://build.opensuse.org/package/view_file/multimedia:apps/vokoscreenNG/vokoscreenNG.spec?expand=1

**Comment by vkohaupt** [comment]
I fixed it. Please test again. Thanks.

**Comment by stefanhusmann** [comment]
Thanks for the quick fix, works fine!
