### ISSUE TITLE
overlay webcam view 

### ISSUE THREAD

**Issue by geofflangenderfer** [vkohaupt/vokoscreenNG#161]
In a previous vokoscreen version, you could overlay the webcam view to the rest of your desktop.

I'm struggling to find this option in the current version. 

Is it available? Was it deprecated?

**Comment by geofflangenderfer** [comment]
you can do this by:
- right click webcam window
- click "Always on Top"

**Comment by vkohaupt** [comment]
I just tested it, the webcam window is always the top window. At least under KDE and Gnome.
