### ISSUE TITLE
GUI not showing

### ISSUE THREAD

**Issue by SisyphusIsntHappy** [vkohaupt/vokoscreenNG#162]
I type in `vokoscreenNG` on terminal and press enter, not gui showing up. I'm on Arch linux. 
using `-h` option results in 

```
Usage: vokoscreenNG [Option] [File or URL]

Options: 
  -h or --help        Print this message
  -v or --version     Print version 

File or Url:
  Play a video
    Example file:
      vokoscreenNG /path/video
```
How to fix it?

**Comment by vkohaupt** [comment]
vokoscreenNG -v

**Comment by vkohaupt** [comment]
I think I found the bug.
The environment variable XDG_SESSION_TYPE is used to determine the platform x11 and Wayland.
If this does not exist, no GUI is displayed.

To work around the problem, open up a terminal and enter the following.
export XDG_SESSION_TYPE=x11 vokoscreenNG

**Comment by vkohaupt** [comment]
I close this issues.
