### ISSUE TITLE
Audio codec changes every time

### ISSUE THREAD

**Issue by frearlv** [vkohaupt/vokoscreenNG#163]
Hi. Thanks very much for the program. It is great.

I've realized that all configuration remain exactly like the last time I used the program but the audio codec config.

In other words, It always stars in "mp3" instead of what I configure the last time I used it, eg. "aac".

It is not a huge problem, but for me, it is better if it remembers all old configuration.

Thanks again, regards.

Fernando.

**Comment by vkohaupt** [comment]
Ok i see it. When saving the settings everything is okay. The error occurs when reading the settings.
I've marked this as a bug.
Thanks for the hint.

**Comment by vkohaupt** [comment]
I fixed the bug.
https://github.com/vkohaupt/vokoscreenNG/commit/95c8c0e59df48e6ad9cb0d628a45617f2945d2f8

**Comment by frearlv** [comment]
Chapeau!!!

Thank you very much.

**Comment by vkohaupt** [comment]
I close this issues.
