### ISSUE TITLE
Record Window option is not available

### ISSUE THREAD

**Issue by adilshoukat** [vkohaupt/vokoscreenNG#164]
I don't see `Record Window` option in 3.0.8 Windows version. But I see it on other's screen in different tutorials and screenshots on google images.
![Screenshot_91](https://user-images.githubusercontent.com/1608798/116124284-84be9d80-a6dd-11eb-9ccb-67e481310736.png)

**Comment by vkohaupt** [comment]
Is to time for Windows not available.

**Comment by adilshoukat** [comment]
@vkohaupt OK. Is it planned for any future releases?

**Comment by vkohaupt** [comment]
Planned yes, but I don't know if I have the necessary know-how.

**Comment by vkohaupt** [comment]
I close this issues.
