### ISSUE TITLE
Announce live stream via DLNA/UPnP?

### ISSUE THREAD

**Issue by pataquets** [vkohaupt/vokoscreenNG#169]
Is this possible?
If not, would it this be an acceptable feature to request?
Thanks.

**Comment by vkohaupt** [comment]
First Point, no.
Second Point, thanks for the hint.

**Comment by pataquets** [comment]
Hi @vkohaupt.

If "second point" means "it would be acceptable", where could anyone track progres/status and get advice in case he/she wants to pick it up?

I've looked at the home page and there's nowhere, nor in this repo wiki or todos. I can prefix this issue title with "Feature request", and with some tagging I hope it will not get in the way of working with issues and would not be too untidy. This way, it can be kept open in case anyone else is interested.
