### ISSUE TITLE
Provide chololatey package

### ISSUE THREAD

**Issue by cazzoo** [vkohaupt/vokoscreenNG#173]
Hello,
I'd first would like to thank you for the work done with Vokoscreen.
The rewrite is what makes this program a gold nugget. Thank you!
I just wonder if you could think about providing a Choco package to the windows chocolatey software library : https://community.chocolatey.org/packages
This is more and more used in these days and this would be a good opportunity to make your program more used by all people.

Kind regards

**Comment by vkohaupt** [comment]
Thanks for the hint.
