### ISSUE TITLE
How to use selection area with I3?

### ISSUE THREAD

**Issue by abbbi** [vkohaupt/vokoscreenNG#174]
hi,

i recently updated to vokoscreen-ng on debian bullseye (buster, before). The selection area was working with i3 window
manager nicely before, it was opened as some overlay selection area which allowed me to select the on screen area
 i want to record.

Now with the recent version, it seems the overlay is not detected anymore and the selection window is opened as an seperate tab/window instance, making i3 catch it. So im not able to select any areas.

Not sure if this is related to I3, i have absolutely no idea, but it worked with the old setup. Attached screenshot shows the issue :)

![foo_001](https://user-images.githubusercontent.com/3919561/120978616-f544e980-c774-11eb-826b-9feff3c56ddf.jpg)

**Comment by vkohaupt** [comment]
If you have desktop problems, please choose a forum of your choice.

**Comment by abbbi** [comment]
hi,

thanks for the response. The feature works with vokoscreen 2.5.0, so who is doing things wrong here? My window manager or vokoscreen? Any advice will help, in case I3 is at fault, i can at least create a meaningful bugreport against my window manager.

**Comment by vkohaupt** [comment]
The problem is the i3. Please consult the i3 team.

**Comment by abbbi** [comment]
hi,

following patch fixes the issue. Not sure if I3 is at fault or vokoscreen, at least, the old vokoscreen version did set the flag.

```
--- vokoscreen-ng-3.0.7.orig/src/region/QvkRegionChoise.cpp
+++ vokoscreen-ng-3.0.7/src/region/QvkRegionChoise.cpp
@@ -71,7 +71,7 @@ QvkRegionChoise::QvkRegionChoise( Ui_for
     setWindowIcon( icon );
 
     // Hint: Qt::WindowStaysOnTopHint is only for X11 and Windows on WayLand not do it
-    setWindowFlags( Qt::FramelessWindowHint | Qt::WindowStaysOnTopHint );
+    setWindowFlags( Qt::FramelessWindowHint | Qt::WindowStaysOnTopHint | Qt::ToolTip );
     setAttribute( Qt::WA_TranslucentBackground, true);
     setMouseTracking( true );
     setFrameColor( Qt::darkGreen );
```

**Comment by vkohaupt** [comment]
Its nice that this run under i3, but what is with the other big desktops, wayland and windows? Have you test this?

**Comment by abbbi** [comment]
> Its nice that this run under i3, but what is with the other big desktops, wayland and windows? Have you test this?

flag was there in older vokoscreen versions, so i assume it worked. Its a solution for me, documented for other tiling window manager users which might run into the same issue. You can commit or not, i dont care. Have a nice day.

**Comment by vkohaupt** [comment]
https://github.com/abbbi/vokoscreenNG/commit/2dcc8260465ec13f3c7ec6192403a6ef2709be4c
Please comment that the cursor key function for resizing and moving will no longer work. Thanks.

**Comment by jaboto** [comment]
Having this issue with Version 3.1.0 and i3 4.20.1. Cannot select area of desktop
![image](https://github.com/vkohaupt/vokoscreenNG/assets/1579754/c21cc7ea-b7fa-4a4c-8cae-14375434c050)

Installing the latest version 4.0.0 fixed the issue although I passed from a system installed app (from apt-get) to a flatpak.
