### ISSUE TITLE
Wayland screen recording not working on KDE Neon 5.22.2

### ISSUE THREAD

**Issue by mara004** [vkohaupt/vokoscreenNG#176]
When I try to start recording the screen on KDE Plasma Wayland, I receive the following error:
```
[vokoscreenNG] Start record
[vokoscreenNG] 111
Warning: Couldn't get reply ((null):0, (null))
Warning: Error:  "No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop" ((null):0, (null))
[vokoscreenNG] 111 reply.value().path(): 
```

I expect this is because Wayland support is highly experimental? Or did I perhaps just miss a dependency?

**Comment by vkohaupt** [comment]
Thanks for testing, but please compile the newest source code.
This answer is with pictures. If your mail client this not show please open
https://github.com/vkohaupt/vokoscreenNG/issues/176

I have install KDE Neon in Virtualbox.
I start vokoscreenNG and get this dialog.
![Bild-02](https://user-images.githubusercontent.com/3152567/123860768-a3802100-d926-11eb-8c45-74ce8bba2f82.png)

Then i want install this package.
![Bild-03](https://user-images.githubusercontent.com/3152567/123861063-07a2e500-d927-11eb-929f-45a99a517430.png)

apt not found the package.
How can I install this package?

I don't know if this package is responsible for your error message. But I cannot continue testing without this package.

Thanks for your help

**Comment by mara004** [comment]
The package is called `gstreamer1.0-pipewire` in Ubuntu / Neon
`sudo apt install gstreamer1.0-pipewire` should do.

I have this package installed, so that can't be the cause of the problem.

I did compile from master branch yesterday (906c7ee), which should be the latest source code, right?

**Comment by vkohaupt** [comment]
> The package is called `gstreamer1.0-pipewire` in Ubuntu / Neon
> `sudo apt install gstreamer1.0-pipewire` should do.

I have installed and i see the GUI and the error.
Gstreamer and pipewire version are ok.
But the package xdg-desktop-portal is to old with 1.6.0 we need minimum 1.7.0
See here
https://github.com/flatpak/xdg-desktop-portal/releases


> I did compile from master branch yesterday ([906c7ee](https://github.com/vkohaupt/vokoscreenNG/commit/906c7eea77a2ca8fb0f1c734bbf140bf88e2fd01)), which should be the latest source code, right?

Yes this is the last commit.

**Comment by mara004** [comment]
> But the package xdg-desktop-portal is to old with 1.6.0 we need minimum 1.7.0

Okay, thanks for the information!
Do you know whether there is any way to update `xdg-desktop-portal`, without breaking other programs?

**Comment by mara004** [comment]
I just built and installed libportal 0.4 and xdg-desktop-portal 1.8.1 from source. Then I rebuilt Vokoscreen, but it still doesn't work. I guess the portal install targets some non-standard location that I need to specify when building Vokoscreen? Or do I need to also update xdg-desktop-portal-kde?

**Comment by mara004** [comment]
Now I also built/installed the latest xdg-desktop-portal-kde and rebuilt Vokoscreen - same problem.

**Comment by vkohaupt** [comment]
Start vokoscreenNG from a terminal and make a record. See you Warning or Errors?

**Comment by mara004** [comment]
It's the ScreenCast interface warning as described above, of course.

**Comment by vkohaupt** [comment]
I develop under opensuse tumbelweed an test also with fedora. I have not install any packages.

Hint:
https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/
If this page works, everything is installed correctly.

**Comment by mara004** [comment]
~~Nice website. Yes, it worked. Vokoscreen doesn't, however.
I just tried with `obs 20210304-git-1`, which is supposed to have Wayland support as well, but it doesn't work either.~~

Oh, wait, no. Only sharing a tab worked, not the screen - so the new portal install is not recognised, apparently. Probably because it landed in a non-standard location, as I said.

**Comment by vkohaupt** [comment]
I found this page.
https://github.com/emersion/xdg-desktop-portal-wlr/wiki/%22It-doesn't-work%22-Troubleshooting-Checklist
This page may help you from point 2 onwards.

**Comment by mara004** [comment]
Thanks. I think for me the most likely issue is that the new xdg portabl build is just not used by the system.
So before I go through this list I'll try installing newer xdg-desktop-portal and xdg-desktop-portal-kde from KDE Neon unstable first (build.neon.kde.org).

**Comment by mara004** [comment]
Finally found the two packages:
https://origin.archive.neon.kde.org/unstable/pool/main/x/xdg-desktop-portal-kde/xdg-desktop-portal-kde_5.22.5+p20.04+tunstable+git20210831.1353-0_amd64.deb
https://origin.archive.neon.kde.org/unstable/pool/main/x/xdg-desktop-portal/xdg-desktop-portal_1.8.1-0xneon+20.04+focal+unstable+build11_amd64.deb

**Comment by mara004** [comment]
I've checked out the instructions and from point 2 onwards everything seems to be ok. I also installed the aforementioned update packages. However, the table of point one provided some meaningful information:
```
Ubuntu lacks support for a lot of the needed libraries. The available xdg-portal-desktop is not compiled with screencast support, there is no xdg-desktop-portal-wlr and only pipewire 0.2 is available
```
This sounds much like it just won't work at all for Ubuntu and derivatives.

**Comment by mara004** [comment]
Moreover, the mentioned Chromium flag `chrome://flags/#enable-webrtc-pipewire-capturer` is not available in my Chromium 92, so these instructions probably target super up-to-date software.
