### ISSUE TITLE
recording a window, time very short to select it before recording starts

### ISSUE THREAD

**Issue by ian204** [vkohaupt/vokoscreenNG#179]
Hello,
I am experiencing problems with recording (Ubuntu 18.04). The app gives a very short time to select it (0.5-1 sec), and it starts the recording. Most of the time I cannot select the window, and the app starts recording an area,  even though I have selected window.
I thought this may be solved by the appropriate setting in vokoscreen.conf.
Thank you for any hist how to solve the issue.
Ian.

**Comment by vkohaupt** [comment]
The bug has been fixed.
https://github.com/vkohaupt/vokoscreenNG/issues/46

Commit:
https://github.com/vkohaupt/vokoscreenNG/commit/4697a94884b895a484bcd3af2f91623c486ee930
