### ISSUE TITLE
Is there any Linux package?

### ISSUE THREAD

**Issue by monkiki** [vkohaupt/vokoscreenNG#18]
Where can I download a Linux compiled package?

Thanks in advance.

**Comment by tux93** [comment]
Hi, I'm maintaining the package for openSUSE, as of the latest snapshot it is in the default repositories of Tumbleweed [1], a request to include it in the next release of Leap is currently pending [2].

[1] https://software.opensuse.org/package/vokoscreenNG
[2] https://build.opensuse.org/request/show/760961

**Comment by monkiki** [comment]
I tried on my Linux Mint, but the compiled can't run due to different Qt5 version.

I will try to compile it on my system.

Thanks!
