### ISSUE TITLE
problems with the installation

### ISSUE THREAD

**Issue by ian204** [vkohaupt/vokoscreenNG#181]
Trying to install the new version. When running qmake I get this complain

qmake: could not find a Qt installation of ''

I am not familiar with all this. Any help is very appreciated (my system is Ubuntu 18.04).

Thank you.

**Comment by vkohaupt** [comment]
From the README

Build requirements
    pkgconfig
    libqt5-devel >= 5.14 (vokoscreenNG >= 3.1.0 pre alpha)
    libqt5-linguist >= 5.14 (vokoscreenNG >= 3.1.0 pre alpha)
    libX11-devel
    gstreamer-devel
    libpulse-devel (vokoscreenNG >= 3.0.7)
    wayland-devel (vokoscreenNG >= 3.0.9)

On Ubuntu these requirements can be satisfied by running sudo apt install libgstreamer1.0-dev qt5-default qttools5-dev-tools libqt5x11extras5-dev qtmultimedia5-dev libqt5multimedia5-plugins libpulse-dev
Build instructions
    Download the source / clone the repo and cd into its directory
    cd src
    qmake
    make

**Comment by ian204** [comment]
Thank you very much!

Trying to install, but when running make I get the following  errors.
Thank you for your comments.
Ian

wayland/mainWindow_wl.cpp:260:23: error: ‘screen’ was not declared in this scope
     QScreen *Screen = screen();
                       ^~~~~~
wayland/mainWindow_wl.cpp:260:23: note: suggested alternative: ‘Screen’
     QScreen *Screen = screen();
                       ^~~~~~
                       Screen
Makefile:1834: recipe for target 'mainWindow_wl.o' failed
make: *** [mainWindow_wl.o] Error 1

**Comment by vkohaupt** [comment]
You need min Qt 5.14
https://doc.qt.io/qt-5/qwidget.html#screen

**Comment by ian204** [comment]
Tried to install it. I couldn't because I am not familiar with the process.
Any hint how to install this package?
Thank you.

**Comment by vkohaupt** [comment]
Copy the binary into your home ~/bin and create a soft link on your desktop. That's all.

**Comment by ian204** [comment]
And where to find the binaries? 
Sorry for my naive questions, but I am not familiar with QT and I dont know where to find these binaries.
