### ISSUE TITLE
Area markers at the end of recording

### ISSUE THREAD

**Issue by stefanct** [vkohaupt/vokoscreenNG#183]
Similarly to the well known issue of recording too early for some animations/fading effects to settle down, I noticed a problem in 3.0.7 on a fairly standard Linux/x11 setup when recording an area: vokoscreen's area markers are visible already at the very end of a recording and thus end up in the last frame(s). Maybe it's enough to flip the actions of stopping the recording and re-showing the markers - or delaying the latter a bit, but it might also be useful in other situations to have a more generic option similar to the seconds wait before recording? I'd also be happy if the area markers could simply be disabled altogether once everything is set up.

**Comment by vkohaupt** [comment]
The bug was fixed in vokoscreenNG 3.0.9 
https://github.com/vkohaupt/vokoscreenNG/issues/144
https://github.com/vkohaupt/vokoscreenNG/commit/91123dd6f73141cc4f21ce3c8e1d02d1c3479e14

Alternatively, you can minimize the area markers in the taskbar.

**Comment by stefanct** [comment]
Oh, sorry for the noise. I did not recognize that the area was a dedicated window. Too many windows, too late ;) Thanks!
