### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by silenx** [vkohaupt/vokoscreenNG#19]
Hello,
in previous version there was a function who highlight mouse click.
Is it possible to have in version 3.X -NG?

**Comment by vkohaupt** [comment]
I think not.

**Comment by marionline** [comment]
This is a real shame.
On KDE desktop it is possible to activate this function on desktop effect menu. Maybe could be possible to hook that function on vokoscreenng? (But it will work only on kde desktop).
