### ISSUE TITLE
Keypresses only received while main windows has focus

### ISSUE THREAD

**Issue by madduck** [vkohaupt/vokoscreenNG#190]
The key shortcuts to start/stop a recording are only received when the main window has focus. It would be very convenient though to be able to stop a recording by key press without first having to open/focus the window, as that might disturb the screencast. The [simplescreenrecorder](https://www.maartenbaert.be/simplescreenrecorder/) tool allows this, so you might want to check out its code base.

**Comment by vkohaupt** [comment]
Go with the mouse on the Start, Stop, Pause button and a tooltip will appear.

**Comment by madduck** [comment]
Yes, I am aware of the key combinations. But they only work while the window is focused. If I minimise it when recording starts, and record a screencast, then at the end of the recording, I have to:

1. bring up the window, hit shift-ctrl-F11
2. or click 'stop' in the window
3. or click 'stop' in the notification bar menu

and then edit the video to remove the last few frames.

My feature request is about listening for the key presses globally, like simplescreenrecorder does. Does this make sense?

**Comment by vkohaupt** [comment]
The global shortcuts work the same as in SSR.
But if another program occupies this, then you have to quit the program or change the key combination there.

More global shortcuts are
Camera shift-ctrl-F8
Magnifying glass shift-ctrl-F9

**Comment by madduck** [comment]
This must be an issue then with my window manager. It works with SSR, but I cannot make it work with vokoscreenNG. Closing, since it seems this is addressed already.
