### ISSUE TITLE
Does not capture window in window mode. 

### ISSUE THREAD

**Issue by capsicumw** [vkohaupt/vokoscreenNG#199]
Set to record "window"  vokoscreen-NG only records in its own window, it will not record any other window that I select. Desktop window focus is set to manual click.  The blue+ disappears when moved over terminal windows. First attempts used mouse only, then attempted focusing on a target window first and using hot key ctl-shift-f10. But with all combinations voko still only records its own window. 
Voko settings delay 3 seconds, 3 second countdown, no magnification, 30 frames per second, no time limit, no audio, no mouse.
Area mode records correctly but can not be moved to second screen.
Debian bullseye, vokoscreen-NG 3.0.7-1, latest from Debian stable repository, Xfce4.16 

[vokoscreenNG] Version: 3.0.7
[vokoscreenNG] Locale: en_US
[vokoscreenNG] Log from: 2022-01-31 18:20:43
[vokoscreenNG] Country: United States
[vokoscreenNG] Qt: 5.15.2
[vokoscreenNG] GStreamer 1.18.4
[vokoscreenNG] Operating system: Debian GNU/Linux 11 (bullseye)
[vokoscreenNG] CPU Architecture: x86_64
[vokoscreenNG] vokoscreenNG running as: xcb client
[vokoscreenNG] vokoscreenNG running on: x11
[vokoscreenNG] Desktop: XFCE
[vokoscreenNG] Icon-Theme: Tango
[vokoscreenNG] Styles: (Windows, Fusion)
[vokoscreenNG] Qt-PluginsPath:      /usr/lib/x86_64-linux-gnu/qt5/plugins
[vokoscreenNG] Qt-TranslationsPath: /usr/share/qt5/translations
[vokoscreenNG] Qt-LibraryPath:      /usr/lib/x86_64-linux-gnu
[vokoscreenNG] Settings: /home/user/.config/vokoscreenNG/vokoscreenNG.ini
[vokoscreenNG] Log: /home/user/.config/vokoscreenNG/log/2022_01_31_18_20_43.log
[vokoscreenNG] Default Videopath: /home/user
[vokoscreenNG] User Videopath: /home/user/.../tempstuff/screen
[vokoscreenNG] CompositingManager running: true

[vokoscreenNG] [Audio] Found: Monitor of Built-in Audio Analog Stereo Device: alsa_output.pci-0000_00_14.2.analog-stereo.monitor
[vokoscreenNG] [Audio] Found: TONOR TC30 Audio Device Mono Device: alsa_input.usb-FuZhou_Kingwayinfo_CO._LTD_TONOR_TC30_Audio_Device_20200707-00.mono-fallback
[vokoscreenNG] [Audio] Found: Monitor of Baffin HDMI/DP Audio [Radeon RX 550 640SP / RX 560/560X] Digital Stereo (HDMI 3) Device: alsa_output.pci-0000_01_00.1.hdmi-stereo-extra2.monitor

[vokoscreenNG] Symbols: + available, - not available
[vokoscreenNG] + matroskamux
[vokoscreenNG] + webmmux
[vokoscreenNG] + avimux
[vokoscreenNG] + mp4mux
[vokoscreenNG] + qtmux
[vokoscreenNG] + x264enc
[vokoscreenNG] - openh264enc
[vokoscreenNG] - vaapih264enc
[vokoscreenNG] - vaapimpeg2enc
[vokoscreenNG] + vp8enc
[vokoscreenNG] + vorbisenc
[vokoscreenNG] + flacenc
[vokoscreenNG] + opusenc
[vokoscreenNG] + lamemp3enc
[vokoscreenNG] + voaacenc

[vokoscreenNG] + ximagesrc
[vokoscreenNG] + pulsesrc
[vokoscreenNG] - pipewiresrc
[vokoscreenNG] + queue
[vokoscreenNG] + capsfilter
[vokoscreenNG] + videoconvert
[vokoscreenNG] + videorate
[vokoscreenNG] + audioconvert
[vokoscreenNG] + audiorate
[vokoscreenNG] + filesink
[vokoscreenNG] + videoscale
[vokoscreenNG] + h264parse
[vokoscreenNG] + audiomixer
[vokoscreenNG] + adder

[vokoscreenNG] Name from screen:  DP-1
[vokoscreenNG] Screen available desktop width : 1920
[vokoscreenNG] Screen available desktop height: 1080
[vokoscreenNG] DevicePixelRatio: 1  (Normal displays is 1, Retina display is 2)
[vokoscreenNG] Vertical refresh rate of the screen in Hz: 60
[vokoscreenNG] Screen orientation Qt::LandscapeOrientation
[vokoscreenNG] Color depth of the screen:  24
[vokoscreenNG] Model from screen:  VA24D-
[vokoscreenNG] Manufactur from screen:  AUS
[vokoscreenNG] SerialNumber from screen:  L5LMQS173859-
[vokoscreenNG] ItemText in Combobox: DP-1 :  1920 x 1080
[vokoscreenNG] ItemData in Combobox: x=0 y=0 with=1920 height=1080

[vokoscreenNG] Name from screen:  HDMI-1
[vokoscreenNG] Screen available desktop width : 1920
[vokoscreenNG] Screen available desktop height: 1080
[vokoscreenNG] DevicePixelRatio: 1  (Normal displays is 1, Retina display is 2)
[vokoscreenNG] Vertical refresh rate of the screen in Hz: 60
[vokoscreenNG] Screen orientation Qt::LandscapeOrientation
[vokoscreenNG] Color depth of the screen:  24
[vokoscreenNG] Model from screen:  24EA53-
[vokoscreenNG] Manufactur from screen:  LG Electronics
[vokoscreenNG] SerialNumber from screen:  -
[vokoscreenNG] ItemText in Combobox: HDMI-1 :  1920 x 1080
[vokoscreenNG] ItemData in Combobox: x=1920 y=0 with=1920 height=1080

[vokoscreenNG] + vp8enc
[vokoscreenNG] + vorbisenc
[vokoscreenNG] + opusenc

[vokoscreenNG] Desktop session is a X11 session

**Comment by capsicumw** [comment]
I found a desktop environment setting that fixes the problem in "Window manager tweaks". Selecting "activate focus stealing prevention" allows Vokoscreen-ng window mode to capture as expected. 
So maybe not a bug but useful information for user help.

**Comment by vkohaupt** [comment]
This is all fixed in the last three bugfix-releases.
You can test it with the current beta.
https://linuxecke.volkoh.de/vokoscreen/vokoscreen-download.html
