### ISSUE TITLE
[feature request] record webcam in separate file to build overlay after recording 

### ISSUE THREAD

**Issue by arthurzenika** [vkohaupt/vokoscreenNG#20]
Wow, new version looks awesome, looking forward to using it. 

For some public presentations that I screencast to republish later it would be nice to have a feature where we could record the webcam in a separate file that can then be edited in for the other publishing. Right now, if I want to have the webcam overlay, the people in the room don't really want to see the webcam image while watching the live presentation. I've tried a workaround by having the webcam on the second screen, but that's not usable when needing a mirror setup between the screen and the presentation screen.

So I guess two options would be awesome :

* record in a separate file for post editing
* position the overlay before recording and when record starts hide the webcam image but insert it in the recorded file

**Comment by vkohaupt** [comment]
Yes that would be an interesting task, but for now I have enough work to fix the many small bugs.

**Comment by obilodeau** [comment]
Either option proposed by @arthurlogilab would be great additions to your tool!
