### ISSUE TITLE
Debian Linux install instructions do not work 

### ISSUE THREAD

**Issue by john-light** [vkohaupt/vokoscreenNG#200]
Getting error when trying to follow [Debian install instructions](https://linuxecke.volkoh.de/vokoscreen/vokoscreen-install.html):

```
sudo apt install vokoscreen-ng
[sudo] password:                     
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package vokoscreen-ng
```

**Comment by vkohaupt** [comment]
Open a terminal and type the following and post the output here. 
lsb_release -a

**Comment by john-light** [comment]
```
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19.3 Tricia
Release:	19.3
Codename:	tricia
```

**Comment by vkohaupt** [comment]
See section Linux Mint 19.3 Cinnamon
https://linuxecke.volkoh.de/vokoscreen/vokoscreen-install.html

**Comment by john-light** [comment]
Somehow missed that when I looked at that page before! Thank you

**Comment by vkohaupt** [comment]
You didn't miss it. I only added this section after testing whether the installer works with Linux Mint 19.3
