### ISSUE TITLE
shortcuts are not visible

### ISSUE THREAD

**Issue by ralf3u** [vkohaupt/vokoscreenNG#209]
Shortcuts are not visible because of the background-color (see picture down below).
Maybe it is because I use a dark mode in Lubuntu 21.10.
vokoscreen-ng: Version: 3.0.7

suggestion for improvement
There should be no background-color. If there is no background-color then the shortcuts would be visible.

![vokoscreen-ng_screenshot](https://user-images.githubusercontent.com/68117017/160258566-946ee1bc-e360-4902-9470-a3b80233e33a.jpg)

**Comment by vkohaupt** [comment]
Thanks for the hint. The English and Germany online help has been updated.

**Comment by ralf3u** [comment]
The issue does not appear any more in vokoscreen-ng 3.1.0.
