### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [vkohaupt/vokoscreenNG#21]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing vokoscreenNG on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by pixelr0** [comment]
yeah, flatpak, snap and appimage

**Comment by vkohaupt** [comment]
If I have a lot of time I'll do it.

**Comment by Mailaender** [comment]
See https://github.com/flathub/flathub/pull/3179

**Comment by vkohaupt** [comment]
Three bugs were found

1. Qt: Session management error: Could not open network socket
This is required for the online help

2. env says KDE is running but SNI unavailable -- check KDE_FULL_SESSION and XDG_CURRENT_DESKTOP
This is required for the Systray

3. - x264enc
This is required for x264 encoding

**Comment by Mailaender** [comment]
1. Should be resolved.
2. Added the environment variable, but it had no effect.
3. This seems to be a runtime problem. I tried installing x264 from VLC which had no effect and `gst-plugins-ugly` also does not help.

**Comment by vkohaupt** [comment]
I build a local package and it is works fine.

1. Online help
add in the finish-args: section
--share=network

2. Systray
remove the env and add in the finish-args: section
--talk-name=org.kde.StatusNotifierWatcher

3. For save pictures
add in the finish-args: section
--filesystem=xdg-pictures

Do a new test run.

**Comment by Mailaender** [comment]
Updated https://github.com/flathub/flathub/pull/3179. Thanks!

For `x264enc` the KDE flatpackers recommended
```yml
add-extensions:
  org.freedesktop.Platform.ffmpeg-full:
    version: '21.08'
    directory: lib/ffmpeg
    add-ld-path: .
```

but it had no effect.

**Comment by vkohaupt** [comment]
I have tested the new update, and it works.

x264enc is not from ffmpeg, it is from GStreamer.

**Comment by vkohaupt** [comment]
Hallo

Das Einbinden von x264 kann man fallen lassen.
Grund der Quellcode ist zwar GPL aber der H.264 Codec ist Patentbehafet.
Und das wird auch der Grund sein, warum auf Flathub nichts dazu zu finden ist.
Auf meiner Website biete ich für Windows auch ein Paket an, dieses beinhaltet aus Lizenz rechtlichen Gründen kein x264.
Ich könnte x264 mitliefern, aber dann wären zusätzliche Arbeits- und Lizenzkosten fällig, sprich vokoscreenNG für Windows könnte man nicht mehr Kostenlos zum Download anbieten.

Wie lange wird die Testphase gehen bzw. wann wird vokoscreenNG regulär zum Download bereitstehen?

**Comment by Mailaender** [comment]
Ich habe https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1425 geöffnet wegen x264. Flatpak hat deutlich mehr Codecs als z.B. @opensuse, aber es könnte tatsächlich eine Patentgeschichte sein.

Das Review bei Flathub ist normalerweise relativ schnell. Nach dem merge dauert es etwa einen Tag bis die Seite neu gebaut wird und die App präsentiert.

**Comment by Mailaender** [comment]
https://flathub.org/apps/details/com.github.vkohaupt.vokoscreenNG

**Comment by Mailaender** [comment]
`x264enc` habe ich gerade nachgelegt. Ist aus Patentgründen nicht im SDK.

**Comment by vkohaupt** [comment]
Hallo Matthias,

Da die App über das Menü nicht gestartet wird, weil in der .desktop der Pfad fix angegeben ist, habe ich ein commit abgesetzt. Flathub meckert dies aber an, sprich der build bricht ab.
Verstehe ich aber nicht da ich dies local ein Dutzenmal getest habe.

Dann wollte ich den commit zurückziehen aber das geht auch nicht -->Protected branch update failed for refs/heads/master.

Dann wollte ich ein Issus schreiben das ging auch nicht.

Ich steh gerade mächtig mit beiden Füßen auf dem Schlauch.

Hier die vollständige Ausgabe von git

vk@cvolker:/Downloads/com.github.vkohaupt.vokoscreenNG> git reset --hard HEAD^
HEAD ist jetzt bei 232ff3c Enable x264enc
vk@cvolker:/Downloads/com.github.vkohaupt.vokoscreenNG> git push origin -f    
Gesamt 0 (Delta 0), Wiederverwendet 0 (Delta 0), Pack wiederverwendet 0
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Cannot force-push to this protected branch
To https://github.com/flathub/com.github.vkohaupt.vokoscreenNG.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: Fehler beim Versenden einiger Referenzen nach 'https://github.com/flathub/com.github.vkohaupt.vokoscreenNG.git'

**Comment by vkohaupt** [comment]
Ok, der Build läuft jetzt durch.
Nachdem ich das Log vom fehlgeschlagenen Build nochmals aufmerksam gelesen habe, hat es geklingelt.
Die Tags müssen strukturiert eingegeben werden, wie unter Python.

**Comment by Mailaender** [comment]
Wenn du einen pull request gestellt hättest, wäre dem CI dein .yml Syntaxfehler vor dem Integrieren aufgefallen.

**Comment by Mailaender** [comment]
Mir ist das nicht aufgefallen, da ich nur mit `flatpak run com.github.vkohaupt.vokoscreenNG` getestet habe.
