### ISSUE TITLE
window problems: no window bar, no memory of last size and position, and too small window

### ISSUE THREAD

**Issue by ralf3u** [vkohaupt/vokoscreenNG#210]
I don't know if those issues are already solved, but in version 3.0.7 in Lubuntu 21.10 it is like this:
- there is no window bar after startup,
- if I let appear the window bar and if I move the window to the center of the display, and if close the window, and then if I reopen vokoscreen, then vokoscreen will not remember the last position of the window,
- if I change the size of the window, then if close the window, and then if I reopen vokoscreen, then vokoscreen will not remember the last size of the window,
- the window is too small from the height because when the different format appears, the last line is not visible (see picture down below), and
- the window is too small from the height because the different vertical symbols on the left side do not appear right away (see picture down below).

![vokoscreen-ng_screenshot_format_2](https://user-images.githubusercontent.com/68117017/160279656-48c4f885-9071-44b0-9b5d-f02ce7bb9e23.jpg)
![vokoscreen-ng_screenshot_format_3](https://user-images.githubusercontent.com/68117017/160279657-7b252e8f-ff21-45cb-b4e1-f9d4a7a77de9.jpg)

**Comment by vkohaupt** [comment]
Your Version is to old. Please test it with the last Beta from here.
https://linuxecke.volkoh.de/vokoscreen/vokoscreen-download.html

**Comment by ralf3u** [comment]
In vokoscreen-ng 3.1.0 there are still two problems:
- if I let appear the window bar and if I move the window to the center of the display, and if close the window, and then if I reopen vokoscreen, then vokoscreen will not remember the last position of the window
- if I change the size of the window, then if close the window, and then if I reopen vokoscreen, then vokoscreen will not remember the last size of the window

**Comment by vkohaupt** [comment]
Thank you for the information.
But I have to tell you that it is not the task of an application to remember the position. This is the task of the window manager or desktop. If your window manager or desktop is not able to do this, please send a bug report to them.
The same applies to the size of the window.
Thanks for your understanding.
