### ISSUE TITLE
flatpak vokoscreenNG 3.3.0 : audio not implemented

### ISSUE THREAD

**Issue by CChalu** [vkohaupt/vokoscreenNG#223]
I installed the flatpak vokoscrenn. The video recording works. But the audio tab is empty with the sentence "audio recording not implemented". 
It's the same with the rpm package from the openSUSE Tumbleweed repository.
What is missing on my system?
20:28:39 [vokoscreenNG] Version: 3.3.0
20:28:39 [vokoscreenNG] Locale: fr_FR
20:28:39 [vokoscreenNG] Log from: 2022-06-25 20:28:39
20:28:39 [vokoscreenNG] Country: France
20:28:39 [vokoscreenNG] Qt: 5.15.5
20:28:39 [vokoscreenNG] GStreamer 1.18.6
20:28:39 [vokoscreenNG] Operating system: KDE Flatpak runtime
20:28:39 [vokoscreenNG] CPU Architecture: x86_64
20:28:39 [vokoscreenNG] Count CPU: 8
20:28:39 [vokoscreenNG] vokoscreenNG running as: wayland client
20:28:39 [vokoscreenNG] vokoscreenNG running on: wayland
20:28:39 [vokoscreenNG] Desktop: KDE
20:28:39 [vokoscreenNG] Icon-Theme: breeze
20:28:39 [vokoscreenNG] Styles: (Breeze, Windows, Fusion)
20:28:39 [vokoscreenNG] Qt-PluginsPath:      /usr/lib/plugins
20:28:39 [vokoscreenNG] Qt-TranslationsPath: /usr/translations
20:28:39 [vokoscreenNG] Qt-LibraryPath:      /usr/lib/x86_64-linux-gnu
20:28:39 [vokoscreenNG] Log: /home/chalu/.var/app/com.github.vkohaupt.vokoscreenNG/config/vokoscreenNG/log/2022-06-25_20-28-39.log
20:28:39 [vokoscreenNG] Default Videopath: /home/chalu/Vidéos

20:28:39 [vokoscreenNG] --- GStreamer elements ---
20:28:39 [vokoscreenNG] + pipewiresrc
20:28:39 [vokoscreenNG] + pulsesrc
20:28:39 [vokoscreenNG] + queue
20:28:39 [vokoscreenNG] + capsfilter
20:28:39 [vokoscreenNG] + videoconvert
20:28:39 [vokoscreenNG] + videorate
20:28:39 [vokoscreenNG] + audioconvert
20:28:39 [vokoscreenNG] + audiorate
20:28:39 [vokoscreenNG] + filesink
20:28:39 [vokoscreenNG] + videoscale
20:28:39 [vokoscreenNG] + h264parse
20:28:39 [vokoscreenNG] + audiomixer
20:28:39 [vokoscreenNG] + videocrop

**Comment by vkohaupt** [comment]
On your system is nothing missing.
That what you see under wayland, is all experimental.
And I'm happy to hear that video recording is working.

vokoscreenNG under wayland is a part of vokoscreeNG but within a completely new development.

Please switch from Wayland to x11 and you have full functionality.

**Comment by CChalu** [comment]
Thanks for your answer, it works with x11. 
I didn't think wayland was involved because the video works.
VokoscreenNG is very good work, I hope you will manage to make it fully functional with wayland.
Thanks for all the work.
