### ISSUE TITLE
the use of "strg" instead of "ctrl" in the English version of the program

### ISSUE THREAD

**Issue by agun214** [vkohaupt/vokoscreenNG#257]
**Describe the bug**

in the Global keyboard shortcuts tab, the word STRG appears beside SHIFT ALT and META instead of CTRL

im on a fresh ubuntu studio 22.04 installation, idk if thats relevant

**Screenshots**
![image](https://user-images.githubusercontent.com/24470767/222916359-39abad9a-2937-42ce-b3e2-9b33eec64250.png)

**Comment by vkohaupt** [comment]
This has been corrected in version 3.4.0

**Comment by vkohaupt** [comment]
See Picture
https://linuxecke.volkoh.de/vokoscreen/vokoscreen-screenshots.html#image0

**Comment by agun214** [comment]
AH my bad sorry. closing with gratitude for your patience.
