### ISSUE TITLE
Cannot compile from source on Ubuntu 20.04.5

### ISSUE THREAD

**Issue by csirmaz** [vkohaupt/vokoscreenNG#259]
**Bug report checklist**
* [N/A] Always send the vokoscreenNG log, after a "Start" and "Stop"
* [X] Have you searched the existing issues to see if this report is a duplicate?
* [X] Are you using the latest version of vokoscreenNG?
* [X] Are you familiar with https://www.mediawiki.org/wiki/How_to_report_a_bug ?

**Describe the bug**
I am trying to compile from source on Ubuntu 20.04.5 LTS following the instructions in the readme on GitHub. I checked out the `3.5.0` tag to try the latest stable version. `qmake` reports `Project ERROR: gsttreamer-video-1.0 development package not found`. `libgstreamer1.0-dev:amd64` is installed.

**Log messages**
Project ERROR: gsttreamer-video-1.0 development package not found

**To Reproduce**
1. Clone codebase from GitHub
2. apt install libgstreamer1.0-dev
3. cd src
4. qmake

**Expected behavior**
qmake to complete without errors

**Comment by vkohaupt** [comment]
An Ubuntu specialist must help here, I set the flag to help wanted.

**Comment by vkohaupt** [comment]
Check or install all libgstreamer-plugins-xxxxx packages
https://packages.ubuntu.com/search?suite=focal-updates&arch=any&searchon=names&keywords=libgstreamer-plugins

**Comment by csirmaz** [comment]
Thank you - I will try.
