### ISSUE TITLE
Setup Travis CI for build AppImage (portable binary package for Linux)

### ISSUE THREAD

**Issue by ghost** [vkohaupt/vokoscreenNG#26]
Setup Travis CI for build *AppImage* (portable package for Linux) as nightly build for each commit.

- AppImage Docs - https://docs.appimage.org/

### TODO

0. [ ] Create `../blob/master/.travis.yml`
1. https://github.com/appimage/AppImageKit
1.1. https://github.com/probonopd/linuxdeployqt
1.2 https://github.com/linuxdeploy
2. https://github.com/probonopd/uploadtool
3. [ ] Enable Travis CI pushing to GitHub releases for this repo.

For example, take a look on *LeoCAD* `.travis.yml` implementation:

- https://github.com/leozide/leocad/blob/master/.travis.yml

And here is how resulted builds would look like:

- https://github.com/leozide/leocad/releases/tag/continuous

For any AppImage packaging questions & support:

- https://docs.appimage.org/user-guide/faq.html#question-where-do-i-get-support

**Comment by probonopd** [comment]
Here is a first draft:
https://github.com/probonopd/vokoscreenNG/blob/patch-1/.travis.yml

But it looks like I need to do more work to make Gstreamer work properly...

**Comment by probonopd** [comment]
The app opens but I get 0 KB files... I think that this may not be enough:

```
[vokoscreenNG] Symbols: + available, - not available
[vokoscreenNG] - matroskamux
[vokoscreenNG] - webmmux
[vokoscreenNG] - avimux
[vokoscreenNG] - mp4mux
[vokoscreenNG] - qtmux
[vokoscreenNG] - ximagesrc
[vokoscreenNG] - pulsesrc
[vokoscreenNG] + queue
[vokoscreenNG] + capsfilter
[vokoscreenNG] - videoconvert
[vokoscreenNG] - videorate
[vokoscreenNG] - audioconvert
[vokoscreenNG] - audiorate
[vokoscreenNG] + filesink
[vokoscreenNG] - videoscale
[vokoscreenNG] - h264parse
[vokoscreenNG] - adder
```

**Comment by ghost** [comment]
Seems like all libs/codecs in this AppImage build missed/not found

**Comment by vkohaupt** [comment]
Hi probonopd,
I think you need the gstreamer environment variable.
Look here in my start script for my upcoming installer.
https://github.com/vkohaupt/vokoscreenIFW/blob/master/linux/packages/root/data/vokoscreenNG.sh

**Comment by probonopd** [comment]
Hi @vkohaupt thanks for your response. Do you know which files are needed to get green checkmarks here? Looks like I am missing some.

![codecs](https://user-images.githubusercontent.com/2480569/72574312-75d52280-38c0-11ea-8b0c-777fa2123548.png)

**Comment by probonopd** [comment]
Looks like I have something that is beginning to work. Check it out:
https://github.com/probonopd/vokoscreenNG/releases/tag/continuous

Now if I knew exactly which GStreamer plugins are needed we could probably bring the size down significantly, because right now I am bundling all I can ;-)

**Comment by tux93** [comment]
> Now if I knew exactly which GStreamer plugins are needed we could probably bring the size down significantly, because right now I am bundling all I can ;-)

From the Readme:

- gstreamer-plugins-base
- gstreamer-plugins-good
- gstreamer-plugins-bad
- gstreamer-plugins-bad-orig-addon (openSUSE Packman)
- gstreamer-plugins-ugly
- gstreamer-plugins-ugly-orig-addon (openSUSE Packman)
- gstreamer-plugins-libav
- gstreamer-plugins-vaapi

**Comment by ghost** [comment]
@probonopd Just tested `vokoscreenNG-17-x86_64.AppImage` to launch under Debian 10.x — it starts (*good*), but in terminal I got next messages:

<details>
    <summary>Terminal log on launch</summary>

```
$ ./vokoscreenNG-17-x86_64.AppImage

(vokoscreenNG:26030): GStreamer-WARNING **: 01:29:56.227: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.
DtsGetHWFeatures: Create File Failed

(vokoscreenNG:26030): GLib-GObject-WARNING **: 01:30:00.417: cannot register existing type 'ClutterGstVideoSink'

(vokoscreenNG:26030): GLib-GObject-CRITICAL **: 01:30:00.417: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(vokoscreenNG:26030): GLib-CRITICAL **: 01:30:00.417: g_once_init_leave: assertion 'result != 0' failed

(vokoscreenNG:26030): GStreamer-CRITICAL **: 01:30:00.417: gst_element_register: assertion 'g_type_is_a (type, GST_TYPE_ELEMENT)' failed
[vokoscreenNG] Version: 3.0.0
[vokoscreenNG] Locale: en_US
[vokoscreenNG] Log from: 2020-01-18 01:30:07
[vokoscreenNG] Country: United States
[vokoscreenNG] Qt: 5.12.6
[vokoscreenNG] GStreamer 1.8.3
[vokoscreenNG] Operating system: Debian GNU/Linux 10 (buster)
[vokoscreenNG] CPU Architecture: x86_64
[vokoscreenNG] vokoscreenNG running as: xcb client
[vokoscreenNG] vokoscreenNG running on: x11
[vokoscreenNG] Desktop: XFCE
[vokoscreenNG] Icon-Theme: Adwaita
[vokoscreenNG] Styles: (Windows, Fusion)
[vokoscreenNG] Qt-PluginsPath:      /tmp/.mount_vokoscvL32v0/usr/opt/qt512/plugins
[vokoscreenNG] Qt-TranslationsPath: /tmp/.mount_vokoscvL32v0/usr/opt/qt512/translations
[vokoscreenNG] Qt-LibraryPath:      /tmp/.mount_vokoscvL32v0/usr/opt/qt512/lib
[vokoscreenNG] Settings: /home/user/.config/vokoscreenNG/vokoscreenNG.ini
[vokoscreenNG] Log: /home/user/.config/vokoscreenNG/log/2020_01_18_01_30_07.log
[vokoscreenNG] CompositingManager running: true


(vokoscreenNG:26030): GStreamer-CRITICAL **: 01:30:07.912: gst_structure_is_equal: assertion 'GST_IS_STRUCTURE (structure1)' failed

(vokoscreenNG:26030): GStreamer-CRITICAL **: 01:30:07.913: gst_structure_to_string: assertion 'structure != NULL' failed

(vokoscreenNG:26030): GStreamer-CRITICAL **: 01:30:07.914: gst_structure_is_equal: assertion 'GST_IS_STRUCTURE (structure1)' failed

(vokoscreenNG:26030): GStreamer-CRITICAL **: 01:30:07.914: gst_structure_to_string: assertion 'structure != NULL' failed
[vokoscreenNG] [PulseAudio] Found: Monitor of Built-in Audio Analog Stereo Device: alsa_output.pci-0000_00_14.2.analog-stereo.monitor
[vokoscreenNG] [PulseAudio] Found: Built-in Audio Analog Stereo Device: alsa_input.pci-0000_00_14.2.analog-stereo

[vokoscreenNG] Symbols: + available, - not available
[vokoscreenNG] + matroskamux
[vokoscreenNG] + webmmux
[vokoscreenNG] + avimux
[vokoscreenNG] + mp4mux
[vokoscreenNG] + qtmux
[vokoscreenNG] + x264enc
[vokoscreenNG] - openh264enc
[vokoscreenNG] + vaapih264enc
[vokoscreenNG] + vaapimpeg2enc
[vokoscreenNG] + vp8enc
[vokoscreenNG] + vorbisenc
[vokoscreenNG] + flacenc
[vokoscreenNG] + opusenc
[vokoscreenNG] + lamemp3enc

[vokoscreenNG] + ximagesrc
[vokoscreenNG] + pulsesrc
[vokoscreenNG] + queue
[vokoscreenNG] + capsfilter
[vokoscreenNG] + videoconvert
[vokoscreenNG] + videorate
[vokoscreenNG] + audioconvert
[vokoscreenNG] + audiorate
[vokoscreenNG] + filesink
[vokoscreenNG] + videoscale
[vokoscreenNG] + h264parse
[vokoscreenNG] + adder

[vokoscreenNG] Name from screen:  LVDS
[vokoscreenNG] Screen available desktop width : 1280
[vokoscreenNG] Screen available desktop height: 800
[vokoscreenNG] DevicePixelRatio: 1  (Normal displays is 1, Retina display is 2)
[vokoscreenNG] Vertical refresh rate of the screen in Hz: 60
[vokoscreenNG] Screen orientation Qt::LandscapeOrientation
[vokoscreenNG] Color depth of the screen:  24
[vokoscreenNG] Model from screen:  
[vokoscreenNG] Manufactur from screen:  Seiko Epson Corporation
[vokoscreenNG] SerialNumber from screen:  
[vokoscreenNG] ItemText in Combobox: LVDS :  1280 x 800
[vokoscreenNG] ItemData in Combobox: x=0 y=0 with=1280 height=800


[vokoscreenNG] ExtensionsPath: /home/user/vokoscreen_extensions/
[vokoscreenNG] No library for extension found
 
[vokoscreenNG] Desktop session is a X11 session
```

</details>

*Is it OK?*

**Comment by probonopd** [comment]
Does it record?

**Comment by vkohaupt** [comment]
I test the AppImage, recording does, but many other things does not.
- Camera crashed application.
- Player crashed application.
- Image format svg in online help does not.
- Dialog for video path only in English.
- Dialog in Player to open a video, only in English.
- Openh264 not found

**Comment by probonopd** [comment]
Thanks for testing @vkohaupt - probably some more things need to be bundled. Let me know if you think you know which ones.

**Comment by probonopd** [comment]
> Image format svg in online help does not

__Update:__ Added `plugins/imageformats/libqsvg.so` by installing `qt512svg` on the build machine. Please retry. SVG should be working now.

> Player crashed application

Was getting

```
[vokoscreenNG] Desktop session is a X11 session
[vokoscreenNG] play video with vokoplayer
[vokoplayer] QMediaPlayer::PlayingState
Segmentation fault
```

on the console. Using `GST_DEBUG=5` I got more useful information.

__Update:__ Added 
* `GST_PLUGIN_SCANNER`
* `GST_PLUGIN_SYSTEM_PATH`
* `GST_PLUGIN_PATH`
and removed `usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstclutter-3.0.so`, `usr/lib/x86_64-linux-gnu/libva-x11.so.1`, and `usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvaapi.so`.

Please retry. Video playback should be working now.

> Dialog for video path only in English.
> Dialog in Player to open a video, only in English.

We are probably not deploying the translation files yet, I need to find out where they live.

> Openh264 not found

Which is the equivalent on Ubuntu xenial for gstreamer-plugins-bad-orig-addon (openSUSE Packman) and gstreamer-plugins-ugly-orig-addon (openSUSE Packman), how can I get Openh264 to work on Ubuntu xenial?
