### ISSUE TITLE
Package naming differ in vaious Linux distros

### ISSUE THREAD

**Issue by ghost** [vkohaupt/vokoscreenNG#28]
Found that package maintainers use different names for *vokoscreenNG* `3.0.0` release packages:

- `vokoscreen-ng` — in Debian, Devuan, Kali Linux, Parrot, PureOS, Raspbian, Ubuntu repositories:
  - https://repology.org/project/vokoscreen-ng/versions
- `vokoscreenng` — in Fedora, OpenSUSE repositories:
  - https://repology.org/project/vokoscreenng/versions
- `vokoscreen` — in AUR, Rosa repositories:
  - https://repology.org/project/vokoscreen/versions

**Comment by tux93** [comment]
Thanks, that reminded me I meant to file delete requests against the old vokoscreen in openSUSE

That being said, Volker has no influence on what name packagers use. 
If differing package names are a problem in your eyes, file bugs against the packages themselves

**Comment by ghost** [comment]
FTR, the biggest issue here is that AUR and Rosa use `vokoscreen` for *vokoscreenNG* `3.0.0`, where both should be different packages

**Comment by tux93** [comment]
Agreed, but once again you need to raise that issue with the packagers directly since I'm not sure they monitor the issues on this project

**Comment by ghost** [comment]
> raise that issue with the packagers directl

Maybe need clarify in the `README.md` which *package name* should be used/preferred by package maintainers?
