### ISSUE TITLE
vokoscreenNG 3.8.0 no record in mp4 format

### ISSUE THREAD

**Issue by texstar** [vkohaupt/vokoscreenNG#285]
I built 3.8.0 but I cannot select mp4 format. It tells me gstreamer packages need to be installed but they are already installed including the development files when I packaged the sourcecode. I am building the Qt5 version. What am I doing wrong?

gstreamer1.0-python3-1.22.6-1pclos2023
gstreamer1.0-tools-1.22.6-1pclos2023
lib64gstvalidate1.0-devel-1.22.6-1pclos2023
lib64gstrtspserver-devel-1.22.6-1pclos2023
lib64gstreamer1.0_0-1.22.6-1pclos2023
gstreamer1.0-devtools-1.22.6-1pclos2023
gstreamer1.0-omx-1.22.6-1pclos2023
lib64ges1.0_0-1.22.6-1pclos2023
gstreamer1.0-validate-scenarios-1.22.6-1pclos2023
lib64gstvalidate1.0_0-1.22.6-1pclos2023
gstreamer1.0-editing-services-1.22.6-1pclos2023
gstreamer1.0-plugins-good-1.22.6-1pclos2023
gstreamer1.0-plugins-bad-1.22.6-1pclos2023
gstreamer1.0-plugins-bad-bluez-1.22.6-1pclos2023
lib64gstrtspserver1.0_0-1.22.6-1pclos2023
lib64gstreamer1.0-devel-1.22.6-1pclos2023
gstreamer1.0-plugins-base-1.22.6-1pclos2023
gstreamer1.0-plugins-bad-qt5-1.22.6-1pclos2023
lib64gstreamer-plugins-base1.0_0-1.22.6-1pclos2023
lib64gstreamer-plugins-bad1.0-devel-1.22.6-1pclos2023
lib64gstreamer-plugins-base1.0-devel-1.22.6-1pclos2023
lib64ges1.0-devel-1.22.6-1pclos2023
gstreamer1.0-plugins-ugly-1.22.6-1pclos2023
gstreamer1.0-libav-1.22.6-1pclos2023
gstreamer1.0-vaapi-1.22.6-1pclos2023

**Comment by vkohaupt** [comment]
The codec openh264 and or x264 is installed?

**Comment by texstar** [comment]
Yes.

lib64x264_164-1.164-3pclos2023
x264-1.164-3pclos2023
lib64x264-devel-1.164-3pclos2023

Maybe we need a newer version of x264?

**Comment by vkohaupt** [comment]
Start vokoscreenNG from the console and post the log here.

**Comment by texstar** [comment]
[tex@pclinuxosHQ SPECS]$ vokoscreenNG
[vokoscreenNG] Desktop session is a X11 session
03:24:28 [vokoscreenNG] Version: 3.8.0
03:24:28 [vokoscreenNG] Locale: en_US
03:24:28 [vokoscreenNG] Log from: 2023-10-10 03:24:28
03:24:28 [vokoscreenNG] Country: United States
03:24:28 [vokoscreenNG] Qt: 5.15.6
03:24:28 [vokoscreenNG] GStreamer 1.22.6
03:24:28 [vokoscreenNG] PulseAudio library version: 16.1.0
03:24:28 [vokoscreenNG] Virtual Maschine: systemd-detect-virt not found
03:24:28 [vokoscreenNG] Operating system: PCLinuxOS 2023
03:24:28 [vokoscreenNG] KernelVersion: 6.5.6-pclos1
03:24:28 [vokoscreenNG] CPU Architecture: x86_64
03:24:28 [vokoscreenNG] Count CPU: 16
03:24:28 [vokoscreenNG] vokoscreenNG running as: xcb client
03:24:28 [vokoscreenNG] vokoscreenNG running on: x11
03:24:28 [vokoscreenNG] Desktop: KDE
03:24:28 [vokoscreenNG] Icon-Theme: breeze-dark
03:24:28 [vokoscreenNG] Styles: QStyleSheetStyle
03:24:28 [vokoscreenNG] ExecutablePath:      /usr/bin
03:24:28 [vokoscreenNG] Qt-PluginsPath:      /usr/lib64/qt5/plugins
03:24:28 [vokoscreenNG] Qt-TranslationsPath: /usr/share/qt5/translations
03:24:28 [vokoscreenNG] Qt-LibraryPath:      /usr/lib64
03:24:28 [vokoscreenNG] Settings: /home/tex/.config/vokoscreenNG/vokoscreenNG.ini
03:24:28 [vokoscreenNG] Log: /home/tex/.config/vokoscreenNG/log/2023-10-10_03-24-28.log
03:24:28 [vokoscreenNG] Default Videopath: /home/tex/Videos
03:24:28 [vokoscreenNG] User Videopath: /home/tex/Videos

03:24:28 [vokoscreenNG] [Audio] Found: Monitor of Family 17h/19h HD Audio Controller Analog Stereo Device: alsa_output.pci-0000_0d_00.6.analog-stereo.monitor
03:24:28 [vokoscreenNG] [Audio] Found: Family 17h/19h HD Audio Controller Analog Stereo Device: alsa_input.1.analog-stereo

03:24:28 [vokoscreenNG] Pictures permission: Can write in /home/tex/Pictures

03:24:29 [vokoscreenNG] Symbols: + available, - not available
03:24:29 [vokoscreenNG] + ximagesrc
03:24:29 [vokoscreenNG] + pulsesrc
03:24:29 [vokoscreenNG] + queue
03:24:29 [vokoscreenNG] + appsrc
03:24:29 [vokoscreenNG] + capsfilter
03:24:29 [vokoscreenNG] + videoconvert
03:24:29 [vokoscreenNG] + videorate
03:24:29 [vokoscreenNG] + videoscale
03:24:29 [vokoscreenNG] + h264parse
03:24:29 [vokoscreenNG] + audioconvert
03:24:29 [vokoscreenNG] + audiorate
03:24:29 [vokoscreenNG] + audiomixer
03:24:29 [vokoscreenNG] + audioresample
03:24:29 [vokoscreenNG] + filesink

03:24:29 [vokoscreenNG] Formats, video- and audio codec are only for record, not for the player
03:24:29 [vokoscreenNG] Video formats:
03:24:29 [vokoscreenNG] + matroskamux (mkv)
03:24:29 [vokoscreenNG] - gifenc (gif)
03:24:29 [vokoscreenNG] + mp4mux (mp4)
03:24:29 [vokoscreenNG] + webmmux (webm)
03:24:29 [vokoscreenNG] + avimux (avi)
03:24:29 [vokoscreenNG] + qtmux (mov)

03:24:29 [vokoscreenNG] Format was changed, codecs are inserted:
03:24:29 [vokoscreenNG] + vp8enc

03:24:29 [vokoscreenNG] Video encoder:
03:24:29 [vokoscreenNG] - openh264enc
03:24:29 [vokoscreenNG] + vp8enc
03:24:29 [vokoscreenNG] - x264enc
03:24:29 [vokoscreenNG] - gifenc

03:24:29 [vokoscreenNG] Audio encoder:
03:24:29 [vokoscreenNG] + vorbisenc
03:24:29 [vokoscreenNG] + flacenc
03:24:29 [vokoscreenNG] + opusenc
03:24:29 [vokoscreenNG] + lamemp3enc

03:24:29 [vokoscreenNG] This screen is the primary screen:  HDMI-A-0
03:24:29 [vokoscreenNG] Name from screen:  HDMI-A-0
03:24:29 [vokoscreenNG] Screen available desktop width : 1920
03:24:29 [vokoscreenNG] Screen available desktop height: 1080
03:24:29 [vokoscreenNG] DevicePixelRatio: 1  (Normal displays is 1, Retina display is 2)
03:24:29 [vokoscreenNG] Vertical refresh rate of the screen in Hz: 60
03:24:29 [vokoscreenNG] Screen orientation Qt::LandscapeOrientation
03:24:29 [vokoscreenNG] Color depth of the screen:  24
03:24:29 [vokoscreenNG] Model from screen:  SA230-
03:24:29 [vokoscreenNG] Manufactur from screen:  Acer Technologies
03:24:29 [vokoscreenNG] SerialNumber from screen:  T91AA0022420-
03:24:29 [vokoscreenNG] ItemText in Combobox: HDMI-A-0 :  1920 x 1080
03:24:29 [vokoscreenNG] ItemData in Combobox: x=0 y=0 with=1920 height=1080

03:24:29 [vokoscreenNG] Language changed to: English  ( United States )  ( en_US ) :/language/en_US.qm

03:24:29 [vokoscreenNG] Format was changed, codecs are inserted:

03:24:29 [vokoscreenNG] [Composite] true

**Comment by vkohaupt** [comment]
For GIF install the package:
 - gstreamer-plugins-rs 

For H.264
 - gstreamer-X.XX-plugin-openh264
 - libopenh264

For x264
 - libx264-XXX
 - gstreamer-plugins-ugly-codecs

**Comment by texstar** [comment]
Ahh, it appears my gstreamer-plugins-ugly is not finding the libx264 development files to build  the encoder for the package. Now I know why vokoscreenNG doesn't work for us in mp4 format.

When compiling gstreamer-plugins-ugly:
Dependency x264 skipped: feature x264 disabled

Thanks.
