### ISSUE TITLE
Detect and use "x264" encoder (if installed)

### ISSUE THREAD

**Issue by ghost** [vkohaupt/vokoscreenNG#31]
Could *vokoscreenNG* detect and use `x264` encoder (if installed)?

- http://www.videolan.org/developers/x264.html
  - https://repology.org/project/x264/versions

Maybe, should it be added as suggested/recommended dependency by package maintainers?

**Comment by vkohaupt** [comment]
Yes, show at the sixth tab. All supported formats and encoders are listed here. Either the maintainer adds all the packages added, and if not then the user has to do.

We need two libs libgstx264.so and libx264.so
The first lib is in package gstreamer-plugins-ugly
The second lib in package libx264
