### ISSUE TITLE
Got just High 4:4:4 profile for mp4 video

### ISSUE THREAD

**Issue by elvecio** [vkohaupt/vokoscreenNG#32]
unfortunately the High 4:4:4 profile is not supported by many android software and also by firefox (at least in my debian it is not), for the files created with your software using Gstreamer's h264...
so all the mp4s created are not seen and/or present errors in a lot of situations.

is it possible to default a "lighter" profile?
ps: the simple High Profile ( not the 4:4:4) for example is supported today by  a lot of software...

**Comment by vkohaupt** [comment]
I take this as a bug and I fixed it.
Firefox 72.0.1 play now the video.
And mediainfo shows a Chroma subsampling 4: 2: 0

**Comment by elvecio** [comment]
Perfect, thanks ;)
