### ISSUE TITLE
Area Recording Overlap on Top Edge

### ISSUE THREAD

**Issue by indivisualvj** [vkohaupt/vokoscreenNG#337]
I will not append a log because it contains paths that would expose my username.
Logs do not say anything that helpful, though.

**Wayland on Linux is experimental**
![image](https://github.com/user-attachments/assets/a365eabd-71dd-467b-b259-95a5f91a183d)

**Describe the bug**
When recording a video or screenshot of an area of my screen, i can see the top edge of my selected area toggle.
Recording starts way above the selected area.

**Log messages**
no helpful information expect my username that i will not expose here.

**To Reproduce**
1. Select Area
2. configure Area
3. hit on screenshot or record screen

**Expected behavior**
Id expect to not see the top edge of my area select handle.

**Additional context**

**Screenshots**
![vokoscreenNG-2024-11-21_11-32-46 018](https://github.com/user-attachments/assets/5f5890fe-09d7-4714-896d-fe9d75123e4c)

**Comment by indivisualvj** [comment]
Used Version is that one from FLATPAK 4.3.0

**Comment by vkohaupt** [comment]
I have install linuxmint-21.2-cinnamon-64bit.iso on VirtualBox but i can not switch to Wayland, see image.
What can i do?

![Screenshot_20241121_131632](https://github.com/user-attachments/assets/d28186b5-bcdf-484c-9652-e066ee08247c)

**Comment by indivisualvj** [comment]
I think i didn't make that clear enough: As far as i know, cinnamon is not based on wayland but gnome shell.

**Comment by vkohaupt** [comment]
I see no Bug. Show the Video

https://github.com/user-attachments/assets/f1ae5a3f-2557-4ecb-aa0d-11f5504014d7

**Comment by vkohaupt** [comment]
Any questions or is it done?

**Comment by indivisualvj** [comment]
> Any questions or is it done?

well. you told me you see no bug and didn't ask any further questions. so i uninstalled vokoscreenNG due to uselessness.

**Comment by vkohaupt** [comment]
Have you even watched my video? What kind of questions should I ask? Does the bug occur during a full moon or a half moon? How many thousands of questions should I ask?

Only you know how, where and when the bug occurs.
I am not prepared to try to drag this out of the user piece by piece.
