### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by inukaze** [vkohaupt/vokoscreenNG#38]
HI there look i try to download & compile with the follow commands : 

 ```
cd /tmp
 git clone https://github.com/vkohaupt/vokoscreenNG
 cd vokoscreenNG/
 ./preparing.sh 
 cd src/
 export {C,CXX}FLAGS='-O2 -fPIC -march=native -mtune=native -pipe'
 export OPTFLAGS='-O2 -fPIC -march=native -mtune=native -pipe'
 qmake-qt5 VOKOSCREEN_INSTALL_PREFIX=/usr QMAKE_CXXFLAGS="$OPTFLAGS" vokoscreenNG.pro 
 make
 ./vokoscreenNG
```

All distros i use, i ever purge SystemD, PulseAudio & Avahi, because became my PC extremely slowpoke, and well, i don't see how i can record with ALSA, i try the old version VokoScreen 2.5.0 and i select ALSA but don't record Audio System :'(

![VokoScreenNG](https://user-images.githubusercontent.com/1647332/74073988-b0733c00-49e2-11ea-99e7-5ce281700da3.png)

After i saw this sad thing vokoscreen & ssr must need "PulseAudio" like the another sound system don't exist, like "ALSA", "Jack", "RoarAudio", etc . . .

**Comment by vkohaupt** [comment]
Please install Pulseaudo and everything will be fin.

**Comment by inukaze** [comment]
> Please install Pulseaudo and everything will be fin.

No, like i say before i ever purge it. Progress and improvements are based on offering options, not eliminating them

i am user GNU/Linux because i prefer use my freedom, to choose & adapt the thing i can to my needs, I do not like the software that they want to impose what they say, if so, I would continue to use Microsoft Windows.

I will not look for alternatives like Vokoscreen or SimpleScreenRecorder
