### ISSUE TITLE
Support VP9 and H.265/x265 encoders

### ISSUE THREAD

**Issue by ghost** [vkohaupt/vokoscreenNG#39]
Add support for VP9 and H.265 encoders.

**Comment by vkohaupt** [comment]
The best thing is to ask again later, because I have a lot to do at the moment.

**Comment by vkohaupt** [comment]
For licensing reasons, there will be no further expansion of patented codecs.

Openh264 is provided for Windows and Flatpak.

For Linux distributions currently also x264.

In the long term, the plan is to only use the openh264 binary provided by CISCO.

And yes, I know, in the European Union software patents are not considered valid. But I would also like to travel outside the European Union and don't feel like extending my stay unnecessarily. I think you understand what I mean by that.
