### ISSUE TITLE
How to cut produced video files and keep the output small?

### ISSUE THREAD

**Issue by tvogel** [vkohaupt/vokoscreenNG#41]
Sorry, this is more a question than an issue, plus, it refers to vokoscreenPrevGen. But still: vokoscreen produces tiny MKV files which is great. When there is basically no motion, it takes basically no stream bandwidth (apart from audio maybe). However, when I cut the MKV with openshot and produce a corresponding MP4 using x264 and the same resolution, the file is huge - easily ten times bigger. Is there a good cutting tool that will help me keep the output small? Or specific parameters, I could tweak in openshot?

**Comment by vkohaupt** [comment]
With ffmpeg you can make small files.
ffmpeg -i inputfile.mp4 outputfile.mp4
