### ISSUE TITLE
Does it work on Ubuntu 16.04?

### ISSUE THREAD

**Issue by ramesh901** [vkohaupt/vokoscreenNG#42]
While using vokoscreen, If I simply start and stop it works fine.If I pause the video in  the middle, then video not getting saved in mkv version.  so I moved to VokoscreenNG. I see redcross in the second tab. If I record the video , audio from speaker not getting recorded. Please provide steps to rectify it.
Thanks!

**Comment by vkohaupt** [comment]
I have expanded the online help, please read it.

**Comment by ramesh901** [comment]
In VokoscreenNG, Audio list is empty. I don't see anything in that list to choose.
In vokoscreen I didn't see this problem. There is always some options available in audio tab

**Comment by vkohaupt** [comment]
Click on the left side on the last tab and send the complete report to me.

**Comment by ramesh901** [comment]
[vokoscreenNG] Version: 3.0.1

[vokoscreenNG] Locale: en_IN

[vokoscreenNG] Log from: 2020-02-17 14:44:19

[vokoscreenNG] Country: India

[vokoscreenNG] Qt: 5.9.5

[vokoscreenNG] GStreamer 1.14.5

[vokoscreenNG] Operating system: Ubuntu Core 18

[vokoscreenNG] CPU Architecture: x86_64

[vokoscreenNG] vokoscreenNG running as: xcb client

[vokoscreenNG] vokoscreenNG running on: x11

[vokoscreenNG] Desktop: Unity

[vokoscreenNG] Icon-Theme: Adwaita

[vokoscreenNG] Styles: (Windows, Fusion)

[vokoscreenNG] Qt-PluginsPath: /usr/lib/x86_64-linux-gnu/qt5/plugins

[vokoscreenNG] Qt-TranslationsPath: /usr/share/qt5/translations

[vokoscreenNG] Qt-LibraryPath: /usr/lib/x86_64-linux-gnu

[vokoscreenNG] Settings:
/home/hduser/snap/vokoscreen-ng/33/.config/vokoscreenNG/vokoscreenNG.ini

[vokoscreenNG] Log:
/home/hduser/snap/vokoscreen-ng/33/.config/vokoscreenNG/log/2020_02_17_14_44_16.log

[vokoscreenNG] CompositingManager running: true


[vokoscreenNG] Symbols: + available, - not available

[vokoscreenNG] + matroskamux

[vokoscreenNG] + webmmux

[vokoscreenNG] + avimux

[vokoscreenNG] + mp4mux

[vokoscreenNG] + qtmux

[vokoscreenNG] + x264enc

[vokoscreenNG] - openh264enc

[vokoscreenNG] - vaapih264enc

[vokoscreenNG] - vaapimpeg2enc

[vokoscreenNG] + vp8enc

[vokoscreenNG] + vorbisenc

[vokoscreenNG] + flacenc

[vokoscreenNG] + opusenc

[vokoscreenNG] + lamemp3enc


[vokoscreenNG] + ximagesrc

[vokoscreenNG] + pulsesrc

[vokoscreenNG] + queue

[vokoscreenNG] + capsfilter

[vokoscreenNG] + videoconvert

[vokoscreenNG] + videorate

[vokoscreenNG] + audioconvert

[vokoscreenNG] + audiorate

[vokoscreenNG] + filesink

[vokoscreenNG] + videoscale

[vokoscreenNG] + h264parse

[vokoscreenNG] + adder


[vokoscreenNG] Name from screen: eDP-1

[vokoscreenNG] Screen available desktop width : 1920

[vokoscreenNG] Screen available desktop height: 1080

[vokoscreenNG] DevicePixelRatio: 1 (Normal displays is 1, Retina display is
2)

[vokoscreenNG] Vertical refresh rate of the screen in Hz: 60

[vokoscreenNG] Screen orientation
Qt::ScreenOrientation(LandscapeOrientation)

[vokoscreenNG] Color depth of the screen: 24

[vokoscreenNG] Model from screen:

[vokoscreenNG] Manufactur from screen:

[vokoscreenNG] SerialNumber from screen:

[vokoscreenNG] ItemText in Combobox: eDP-1 : 1920 x 1080

[vokoscreenNG] ItemData in Combobox: x=0 y=0 with=1920 height=1080


[vokoscreenNG] [Camera] Found: Integrated_Webcam_HD: Integrate Device:
video0


[vokoscreenNG] ExtensionsPath:
/home/hduser/snap/vokoscreen-ng/33/vokoscreen_extensions/

[vokoscreenNG] No library for extension found

[vokoscreenNG] Desktop session is a X11 session

QIODevice::write (QTcpSocket): device not open

QIODevice::write (QTcpSocket): device not open

radioButtonScreencastFullscreen=true

radioButtonScreencastWindow=false

radioButtonScreencastArea=false

checkBoxCameraOnOff=false

checkBoxCameraMirrorVertical=false

checkBoxCameraMirrorHorizontal=false

checkBoxCameraInvert=false

checkBoxCameraGray=false

checkBoxCameraMono=false

checkBoxCameraWindowFrame=false

checkBoxShowInSystray=true

checkBoxShowInSystrayAlternative=true

checkBoxMinimizedWhenRecordingStarts=false

checkBoxStartsMinimized=false

checkBoxResetAtNextStart=false

checkBoxLookForUpdates=true

checkBoxMouseCursorOnOff=false

checkBoxScale=false

checkBoxMagnifier=false

comboBoxCamera=Integrated_Webcam_HD: Integrate

comboBoxFormat=mkv

comboBoxVideoCodec=x264

comboBoxx264Preset=superfast

comboBoxAudioCodec=vorbis

comboBoxOnlineHelp=Automatically

comboBoxAreaSize=320 x 200 CGA 16 : 10

comboBoxScale=320 x 200 CGA 16 : 10

comboBoxScreencastScreen=eDP-1 : 1920 x 1080

sliderVolume=70

sliderVideo=0

sliderCameraWindowSize=2

sliderHour=0

sliderMinute=0

sliderStopRecordingAfterHouers=0

sliderStopRecordingAfterMinutes=0

sliderStopRecordingAfterSeconds=15

sliderLimitOfFreeDiskSpace=250

sliderShowInSystrayAlternative=48

sliderSecondWaitBeforeRecording=1

sliderX264=17

sliderOpenh264=23

sliderFrames=25

sliderScreencastCountDown=0

sliderMagnification=2

lineEditVideoPath=/home/hduser/Videos

[vokoscreenNG] Start record with: ximagesrc display-name=:1
use-damage=false show-pointer=true startx=0 starty=0 endx=1919 endy=1079 !
capsfilter caps=video/x-raw,framerate=25/1 ! videoconvert ! videorate !
x264enc qp-min=17 qp-max=17 speed-preset=superfast threads=4 !
video/x-h264, profile=baseline ! matroskamux name=mux
writing-app=vokoscreenNG_3.0.1 ! filesink
location=/home/hduser/Videos/vokoscreenNG-2020-02-17_14-46-09.mkv

gst-launch-1.0 -e \

ximagesrc display-name=:1 use-damage=false show-pointer=true startx=0
starty=0 endx=1919 endy=1079 \

! capsfilter caps=video/x-raw,framerate=25/1 \

! videoconvert \

! videorate \

! x264enc qp-min=17 qp-max=17 speed-preset=superfast threads=4 \

! video/x-h264, profile=baseline \

! matroskamux name=mux writing-app=vokoscreenNG_3.0.1 \

! filesink location=/home/hduser/Videos/vokoscreenNG-2020-02-17_14-46-09.mkv


[vokoscreenNG] Stop record

[vokoscreenNG] play video with vokoplayer

[vokoplayer] QMediaPlayer::PlayingState

Warning: "Failed to connect: Connection refused"

[vokoplayer] QMediaPlayer::StoppedState

radioButtonScreencastFullscreen=true

radioButtonScreencastWindow=false

radioButtonScreencastArea=false

checkBoxCameraOnOff=false

checkBoxCameraMirrorVertical=false

checkBoxCameraMirrorHorizontal=false

checkBoxCameraInvert=false

checkBoxCameraGray=false

checkBoxCameraMono=false

checkBoxCameraWindowFrame=false

checkBoxShowInSystray=true

checkBoxShowInSystrayAlternative=true

checkBoxMinimizedWhenRecordingStarts=false

checkBoxStartsMinimized=false

checkBoxResetAtNextStart=false

checkBoxLookForUpdates=true

checkBoxMouseCursorOnOff=false

checkBoxScale=false

checkBoxMagnifier=false

comboBoxCamera=Integrated_Webcam_HD: Integrate

comboBoxFormat=mkv

comboBoxVideoCodec=x264

comboBoxx264Preset=superfast

comboBoxAudioCodec=vorbis

comboBoxOnlineHelp=Automatically

comboBoxAreaSize=320 x 200 CGA 16 : 10

comboBoxScale=320 x 200 CGA 16 : 10

comboBoxScreencastScreen=eDP-1 : 1920 x 1080

sliderCameraWindowSize=2

sliderVolume=70

sliderVideo=0

sliderHour=0

sliderMinute=0

sliderStopRecordingAfterHouers=0

sliderStopRecordingAfterMinutes=0

sliderStopRecordingAfterSeconds=15

sliderLimitOfFreeDiskSpace=250

sliderShowInSystrayAlternative=48

sliderSecondWaitBeforeRecording=1

sliderX264=17

sliderOpenh264=23

sliderFrames=25

sliderScreencastCountDown=0

sliderMagnification=2

lineEditVideoPath=/home/hduser/Videos

[vokoscreenNG] Start record with: ximagesrc display-name=:1
use-damage=false show-pointer=true startx=0 starty=0 endx=1919 endy=1079 !
capsfilter caps=video/x-raw,framerate=25/1 ! videoconvert ! videorate !
x264enc qp-min=17 qp-max=17 speed-preset=superfast threads=4 !
video/x-h264, profile=baseline ! matroskamux name=mux
writing-app=vokoscreenNG_3.0.1 ! filesink
location=/home/hduser/Videos/vokoscreenNG-2020-02-17_14-47-08.mkv

gst-launch-1.0 -e \

ximagesrc display-name=:1 use-damage=false show-pointer=true startx=0
starty=0 endx=1919 endy=1079 \

! capsfilter caps=video/x-raw,framerate=25/1 \

! videoconvert \

! videorate \

! x264enc qp-min=17 qp-max=17 speed-preset=superfast threads=4 \

! video/x-h264, profile=baseline \

! matroskamux name=mux writing-app=vokoscreenNG_3.0.1 \

! filesink location=/home/hduser/Videos/vokoscreenNG-2020-02-17_14-47-08.mkv


[vokoscreenNG] Stop record

[vokoscreenNG] play video with vokoplayer

[vokoplayer] QMediaPlayer::PlayingState

Warning: "Failed to connect: Connection refused"

[vokoplayer] QMediaPlayer::StoppedState

**Comment by vkohaupt** [comment]
The log say "Operating system: Ubuntu Core 18"
The issue title say "Does it work on Ubuntu 16.04"

Have you installed "Ubuntu Core 18" as snap in a Ubuntu 16.04?

**Comment by ramesh901** [comment]
**hduser@ubuntu:~$ snap list --all**
Name           Version    Rev   Tracking  Publisher     Notes
core           16-2.42.5  8268  stable    canonical*    core,disabled
core           16-2.43.2  8592  stable    canonical*    core
core18         20200124   1668  stable    canonical*    base
gitlptools     dc528fc    29    stable    sparkiegeek   disabled,classic
gitlptools     b9b9618    35    stable    sparkiegeek   disabled,classic
gitlptools     b9b9618    36    stable    sparkiegeek   classic
postman        7.13.0     97    stable    postman-inc*  disabled
postman        7.18.0     98    stable    postman-inc*  -
vlc            3.0.8      1397  stable    videolan*     -
vokoscreen-ng  3.0.1      33    stable    popey         -
**hduser@ubuntu:~$ lsb_release -a**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

Shall I remove core 18 and check whether vokoscreenNG is working?

**Comment by vkohaupt** [comment]
Ok, i see vokoscreenNG is build as snap.
Please go to snapcraft forum and speak with Alan Pope.
https://snapcraft.io/vokoscreen-ng
I can't help. Sorry.

**Comment by esclapes** [comment]
@ramesh901 I had the same issue and I was able to solve it by installing the pulseaudio snap:

```
snap install pulseaudio
```

Note that this snap is meant to be used in Ubuntu only.

By the way, a more descriptive title of this issue could help find the issue: something like "Unbuntu snap requires pulseaudio to record sound"
