### ISSUE TITLE
Preparing script

### ISSUE THREAD

**Issue by blackPantherOS** [vkohaupt/vokoscreenNG#43]
Hello,
The preparing script cannot use because transifex reject language downloading with follow error:

```
Verifying token...
tx INFO: Updating /***/.transifexrc file...
tx INFO: New translations found for the following languages:es, it_IT, de_CH, de_DE, id, fr_FR, ca, zh_TW, nl_NL, lt, de_AT, pt, ru, no, sv_SE, hu, cs_CZ, fi_FI, uk_UA, tr_TR, zh_CN
tx INFO: Pulling new translations for resource vokoscreen.vokoscreen-version-3 (source: None)
tx WARNING:  -> es: language/es.ts
tx ERROR: Forbidden
tx ERROR: 
Error: Authentication failed. Please make sure your credentials are valid.
For more information, visit:
https://docs.transifex.com/client/client-configuration#-transifexrc.

```
Please built translations into source in future, for easy distro packaging.

**Comment by tux93** [comment]
I don't know what you're trying to do but the translations already are in the source, see [src/language](/vkohaupt/vokoscreenNG/tree/3.0/src/language)

The preparing.sh script is meant to only run by the dev for new releases from what I can tell

**Comment by blackPantherOS** [comment]
Yep, I see it already. Sorry for false report...
If you have free time,. please add "custom hotkey" to settings into future release instead these:

"STRG + SHIFT + F10  Starts a recording. 
 STRG + SHIFT + F11  Stops a recording. 
 STRG + SHIFT + F12  Pauses recording. "

**Comment by vkohaupt** [comment]
Custom hotkeys do not work under Wayland, so I want to wait and see how they develop.
