### ISSUE TITLE
Window selector uses focus change instead of click, making it impossible to select with "focus follows mouse" (Window selector gives less than 1 sec to select)

### ISSUE THREAD

**Issue by grinapo** [vkohaupt/vokoscreenNG#46]
v3.0.2 from debian package.

Selecting "Window" as area does not let me select anything.
Pressing "Start" gives a blue crosshair for about 700 milliseconds then selects the window where the crosshair is. It requires long training and good skills to target a smaller window, it's kind of a good action shooter.
I would still prefer less skills required. :-) Like, having a button next to "Window" as "Select window", and start would already use that window.

(This cannot seem to be possible to circumvent by countdown or delayed start, either.)

**Comment by vkohaupt** [comment]
Please press with **one** mouse click on Start and you have all time this world.
But if you want vokoscreenNG as action shooter then make a double click :>)

**Comment by grinapo** [comment]
It is an understandable assumption but no, I do not generally double-click on buttons, and haven't this time either. 

I do not see any sign on the console about selection so I can't really tell why it believes it was clicked, or, actually, how the _click_ on the button seem to end up on the crosshair _as well_. If you have any idea how to debug it, go on.

This is Xfce4, by the way, so anything may happen....

**Comment by tux93** [comment]
I can reproduce this behaviour on openSUSE Tumbleweed, Xfce 4.14

**Comment by tux93** [comment]
Update:
It seems to be connected to vokoscreen loosing focus, when setting xfwm from "Focus follows mouse" to "Click to focus" the issue vanishes

**Comment by vkohaupt** [comment]
Is it, as tux 93 writes, that the windows automatically get the focus?

**Comment by grinapo** [comment]
Yes, windows automatically get focus as the mouse wanders by and lose it as the rodent goes to the next. No clicking was involved.

(And indeed, focus delay is about 250 ms. Wow I'm fast. :-))

**Comment by vkohaupt** [comment]
Thanks for your help. I included the problem in the online help.

**Comment by grinapo** [comment]
You mean you won't or can't fix the bug? :eyes: 
You probably don't expect people to reconfigure their desktop for a program?

I guess the problem is that you should wait for a Click instead of a GetFocus, or actually it'd be even better to do this before starting (but that's only my opinion).

My problem is that window mode would be The mode I'd use but right now it's useless. Apart from joking it's not really usable to try to select focus in a quarter of second or record a wrong window, even without any visual indication of which window is being recorded. It is extremely frustrating, I just tried to stay positive.

**Comment by vkohaupt** [comment]
For example, the situation is the same as for audio. Only 1.6% of users use pure Alsa. That is why vokoscreenNG only supports pulseaudio. With the problem addressed here, the user group will be much smaller, and therefore there is no budget for such unusual things.
Thank you for your help and please understand.

**Comment by grinapo** [comment]
Sure, it's your decision. 

Just a sidenote: lot of professionals use follow focus since it makes possible to work on non-top windows in parallel or let you choose focus without window order change. I cannot provide you with usage numbers, but my guess would be that your guess is pretty wrong and it's more common than you think. (Also I would say using focus change instead of a direct selection [click] is a mistake, but that's your choice as well.)

**Comment by vkohaupt** [comment]
It was a year and a half ago, but I haven't forgotten it. I have now built in a function that is also used in "Showclick". I tested it under KDE Plasma, and yes it works very well.
