### ISSUE TITLE
[FR] "Screenkey" and "mouse clicks" capture

### ISSUE THREAD

**Issue by RafaelLinux** [vkohaupt/vokoscreenNG#48]
I used "previous" Vokoscreen version cause it implemented an awesome way to show user keystrokes (screenkey) and mouse clicks (but this last feature, was incomplete cause there was no way to distinguish clicked buttons).

Will vokoscreenNG support this features?

Thank you

**Comment by vkohaupt** [comment]
In the next time not.

**Comment by RafaelLinux** [comment]
It's a pity, cause those features make Vokoscreen better than other screen recorders.

Thank you

**Comment by candideu** [comment]
Hello, is this feature still being considered?

**Comment by vkohaupt** [comment]
A Windows version for testing is available here. 
https://linuxecke.volkoh.de/vokoscreen/vokoscreen-download.html

![Bild-01](https://user-images.githubusercontent.com/3152567/134809076-4c2360d1-9c08-44fe-aafe-faa50fc07034.png)

**Comment by RafaelLinux** [comment]
I'm sorry, can't check cause I don't use Windows. Will it include keystrokes recording?

**Comment by candideu** [comment]
> I'm sorry, can't check cause I don't use Windows. Will it include keystrokes recording?

I checked and it appears like no. For Linux though, I'd look into Screenkey: https://gitlab.com/screenkey/screenkey

https://www.thregr.org/~wavexx/software/screenkey/

**Comment by RafaelLinux** [comment]
Thank you candideu, I know Screenkey, but I would like an AIO application like  vokoscreenNG can be.
