### ISSUE TITLE
no audio 8.1

### ISSUE THREAD

**Issue by luke2136** [vkohaupt/vokoscreenNG#49]
Windows 8.1 everything works except audio - greyed out and blank with red 'x' on microphone. Looking to clarify on the instruction given on main page (it is not real clear) for Windows 10 where it says "build requires" - and lists three downloads; also says needs a codec pack:

1. This computer has the latest K-lite codec pack. Is that good? 

2. Downloading and installing the three downloads "required" - is this to make the audio work? - for 8.1?

just wanting to check - at least one of those files is very large - thanks

**Comment by vkohaupt** [comment]
I am a little confused. Do you want to build vokoscreenNG from the sources or do you have a problem with the microphone?

**Comment by luke2136** [comment]
Thanks for the reply. 

No not wanting to build. I installed vokoscreenNG on a Windows 8.1 machine and am not able to get the audio to work. It is greyed out on the video-type screen (mp4, avi, etc.), and the audio-source screen is blank, and the microphone icon on the gui has a red ‘x’ 

Video records nicely but no audio. Trying to figure out to make it work. Thanks again

**Comment by vkohaupt** [comment]
Click on the left side of the last Tab and copy and paste the full log here. Then we'll see.

**Comment by luke2136** [comment]
Here it is - thanks:

[vokoscreenNG] Version: 3.0.2
[vokoscreenNG] Locale: en_US
[vokoscreenNG] Log from: 2020-03-03 07:58:49
[vokoscreenNG] Country: UnitedStates
[vokoscreenNG] Qt: 5.9.4
[vokoscreenNG] GStreamer 1.14.4
[vokoscreenNG] Operating system: Windows 8.1 (6.3)
[vokoscreenNG] CPU Architecture: x86_64
[vokoscreenNG] vokoscreenNG running as: windows client
[vokoscreenNG] Desktop: 
[vokoscreenNG] Icon-Theme: 
[vokoscreenNG] Styles: (Windows, WindowsXP, WindowsVista, Fusion)
[vokoscreenNG] Qt-PluginsPath:      C:/Program Files (x86)/vokoscreenNG
[vokoscreenNG] Qt-TranslationsPath: C:/Program Files (x86)/vokoscreenNG/translations
[vokoscreenNG] Qt-LibraryPath:      C:/Program Files (x86)/vokoscreenNG
[vokoscreenNG] Settings: C:/Users/Owner/AppData/Roaming/vokoscreenNG/vokoscreenNG.ini
[vokoscreenNG] Log: C:/Users/Owner/AppData/Local/vokoscreenNG/log/2020_03_03_07_58_45.log

[vokoscreenNG] Symbols: + available, - not available
[vokoscreenNG] + matroskamux
[vokoscreenNG] + webmmux
[vokoscreenNG] + avimux
[vokoscreenNG] + mp4mux
[vokoscreenNG] + qtmux
[vokoscreenNG] + x264enc
[vokoscreenNG] + vp8enc
[vokoscreenNG] + vorbisenc
[vokoscreenNG] + flacenc
[vokoscreenNG] + opusenc
[vokoscreenNG] + lamemp3enc

[vokoscreenNG] + gdiscreencapsrc
[vokoscreenNG] + queue
[vokoscreenNG] + capsfilter
[vokoscreenNG] + videoconvert
[vokoscreenNG] + videorate
[vokoscreenNG] + audioconvert
[vokoscreenNG] + audiorate
[vokoscreenNG] + filesink
[vokoscreenNG] + videoscale
[vokoscreenNG] - h264parse
[vokoscreenNG] + adder

[vokoscreenNG] Name from screen:  \\.\DISPLAY1
[vokoscreenNG] Screen available desktop width : 1920
[vokoscreenNG] Screen available desktop height: 1080
[vokoscreenNG] DevicePixelRatio: 1  (Normal displays is 1, Retina display is 2)
[vokoscreenNG] Vertical refresh rate of the screen in Hz: 60
[vokoscreenNG] Screen orientation Qt::ScreenOrientation(LandscapeOrientation)
[vokoscreenNG] Color depth of the screen:  32
[vokoscreenNG] Model from screen:  
[vokoscreenNG] Manufactur from screen:  
[vokoscreenNG] SerialNumber from screen:  
[vokoscreenNG] ItemText in Combobox: \\.\DISPLAY1 :  1920 x 1080
[vokoscreenNG] ItemData in Combobox: x=0 y=0 with=1920 height=1080

[vokoscreenNG] ExtensionsPath: C:/Users/Owner\vokoscreen_extensions\
[vokoscreenNG] No library for extension found
 
[vokoscreenNG] + x264enc
[vokoscreenNG] + lamemp3enc
[vokoscreenNG] + opusenc

**Comment by luke2136** [comment]
vkohaupt,

Hey just digging around a bit more and found 'stereo-mix' had been disabled and hidden on this 8.1 machine. Enabled it and it showed up on the VokoscreenNg audio-source screen (stereo mix only - nothing else). Clicked it on, everything lit up, then tried a quick video record and the audio is now working perfectly.

Did not think of that before. Anyway thanks for your help - and for VokoscreenNg - it is very nice.

tm
