### ISSUE TITLE
Codecs missing in Ubuntu 18.04

### ISSUE THREAD

**Issue by ccaprani** [vkohaupt/vokoscreenNG#50]
I had been using v2.5 with no problems, and so installed v3.02 NG. Unfortunately it does not offer me these formats which are listed as "Not Available":
- X264
- openh264
- H.264 (Intel GPU)
- MPEG-2 (Intel GPU)
I can use libx264 and mpeg4 through v2.5 no problem. I wish I could help more, but that's it!

**Comment by vkohaupt** [comment]
For x264 open a terminal and type:
sudo apt install ubuntu-restricted-extras

For the other codecs i have no hint.

**Comment by ccaprani** [comment]
Thank you @vkohaupt. That has indeed installed x264 for v3.02. I'm interested to know what is the difference between how v3.02 pulls the available codecs and how v2.5 managed to pull libx264. Any quick comment, or shall I dig into the code? Thank you.

**Comment by vkohaupt** [comment]
I honestly don't know. And I don't know Ubuntu's package dependencies.
https://wiki.ubuntuusers.de/ubuntu-restricted-extras/
Hmm ... actually you should also have ubuntu-restricted-extras installation for v2.5.
For over 20 years I have only used Linux openSUSE, not Windows. But package management on Linux is an impenetrable jungle. It is important that it works. It doesn't matter how it works.
