### ISSUE TITLE
Cannot record screen in Wayland

### ISSUE THREAD

**Issue by probonopd** [vkohaupt/vokoscreenNG#51]
On Fedora, getting

> To time Wayland is not supported. A screencast show a black screen. Please logout and start a X11 Desktop session

Will this ever be fixed?

Reference:
https://gitlab.freedesktop.org/wayland/wayland/issues/150

**Comment by probonopd** [comment]
According to https://fedoraproject.org/wiki/ScreenCasting#Green-recorder

> Green Recorder is the first desktop program to support Wayland display server on GNOME session. (...) Built using Python, GTK+ 3 and ffmpeg.

Could vokoscreenNG use the same ffmpeg method to achieve this, too?

**Comment by vkohaupt** [comment]
> On Fedora, getting
> 
> > To time Wayland is not supported. A screencast show a black screen. Please logout and start a X11 Desktop session
> 
> Will this ever be fixed?

I currently have a playground https://github.com/vkohaupt/wayland to see what is possible.
With KDE, I can now record a fullscreen without a cursor via xdg-portal, but the video is very bad because Pipewire or pipewiresrc currently do not provide a time stamp.
I definitely stay tuned, but it takes time.

**Comment by vkohaupt** [comment]
> According to https://fedoraproject.org/wiki/ScreenCasting#Green-recorder
> 
> > Green Recorder is the first desktop program to support Wayland display server on GNOME session. (...) Built using Python, GTK+ 3 and ffmpeg.

Green-recorder has stopped development. I can understand that, Wayland is a hard thing.
https://github.com/mhsabbagh/green-recorder

**Comment by probonopd** [comment]
> Wayland is a hard thing.

Thanks for your response @vkohaupt.
Can you describe what about Wayland makes it so hard, and what Wayland could do to make it as easy (and as "it just works") as Xorg?

I am increasingly fed up with Wayland because nothing works: no screen recorders, no screen sharing tools, no screen casting tools. And it has been like this for years. Because of this, I generally avoid Wayland altogether.

**Comment by probonopd** [comment]
To create a screencast in Fedora, one can use the key-combination Ctrl + Shift + Alt +R to start your recording. Couldn't the same technology they are using to implement that feature be used here?

**Comment by probonopd** [comment]
A developer from the TeamViewer team neatly summarized the situation years ago:

https://community.teamviewer.com/t5/Linux/State-of-Wayland-amp-TeamViewer/td-p/26340

> By design, Wayland does not provide an interface to do remote control (screen capturing, mouse and keyboard emulation). This is to keep the Wayland core lean. The idea is that the compositor provides these interfaces, which could mean that TeamViewer would have to implement different interfaces for every desktop environment we want to support. This is unfortunate, but it's even more unsatisfying that these interfaces are not available yet.

Over at https://gitlab.freedesktop.org/wayland/wayland/issues/150 they are describing https://github.com/flatpak/xdg-desktop-portal as a solution; is it? If not, why not? It would probably be helpful for the Wayland team to hear from developers that have to fight with this firsthand, so maybe you'd like to join the discussion over there.

**Comment by vkohaupt** [comment]
I have now decided that there will be no Wayland support for the time being. Reason, there is no budget for it. Let's see how it looks in a year or two.

**Comment by ebrensi** [comment]
If there is any way I can help, I would love to see native Wayland support.   If you want to charge a fee for that then I will pay it.

**Comment by vkohaupt** [comment]
How much would you donate to the development?

**Comment by ebrensi** [comment]
I'd pay U.S. $50.

**Comment by ebrensi** [comment]
I did pay, by the way.  I actually paid 50 euro.

**Comment by Username23453** [comment]
Has there been any update with vokoscreen & wayland?

**Comment by probonopd** [comment]
Seems to me like Wayland is [broken by design](https://gist.github.com/probonopd/9feb7c20257af5dd915e3a9f2d1f2277). At least, it happily breaks existing software like vokoscreenNG. Reason for me to avoid Wayland.

**Comment by Username23453** [comment]
@probonopd , Thank you, I use ZorinOS & at every login I can choose between X11 & wayland, I must choose wayland sometimes when i want to use an android emulator called waydroid. I was just wondering how i could screen capture waydroid. I guess i can install an android app that screen captures. Or use a video camera to record the screen(poor quality).

**Comment by rriemann** [comment]
On KDE, the on-board tool [Spectacle](https://apps.kde.org/en-gb/spectacle/) for screenshots can also handle recording windows including on Wayland. Though it seems to be a bit buggy yet. Worth a try!

**Comment by the-real-i9** [comment]
As of this writing, the latest version of Vokoscreen 4.5.2 now supports Wayland. Although there are no advanced settings, I love my experience.
