### ISSUE TITLE
Missing dependency for camera

### ISSUE THREAD

**Issue by dfok** [vkohaupt/vokoscreenNG#53]
To make the camera work an additional package is needed under linux. To make things work I needed to install `libqt5multimedia5-plugins` additionally to the already recommended packages. For future users it may be useful to add this package to the list in README.md.

Best, Dennis

PS. Great work on a nice and easy to use tool!

**Comment by vkohaupt** [comment]
This is a Problem. Not all Distributions have by name this Package.

**Comment by TomGranot** [comment]
Can confirm installing the `libqt5multimedia5-plugins` package solved the camera not working issue for me on Ubuntu 19.10.

**Comment by vkohaupt** [comment]
Test under Ubuntu 19.10 in Virtualbox.
Installation Guide: https://linuxecke.volkoh.de/vokoscreen/vokoscreen-install.html
Show this Picture:
![Bild-02](https://user-images.githubusercontent.com/3152567/80325026-d4049080-8833-11ea-9adc-1d898fa2a061.png)
How did you do the installation? Please step by step.

**Comment by TomGranot** [comment]
One step - `sudo apt-get install libqt5multimedia5-plugins`.
Before - no camera (greyed out in voko).
Afterwards -camera detected on startup and available in voko.

**Comment by vkohaupt** [comment]
That is not from interesting. I want to know how you installed vokoscreenNG.
Finally, I have no influence on how the districts name the packages and what is packed into the package.

**Comment by dfok** [comment]
To add to my original comment: I compiled things from source and installed the packages mentioned in the README: 

> On Ubuntu these requirements can be satisfied by running sudo apt install libgstreamer1.0-dev qt5-default qttools5-dev-tools libqt5x11extras5-dev qtmultimedia5-dev. 

Perhaps just add `libqt5multimedia5-plugins` to this list? I'm also running Ubuntu 19.10.

**Comment by vkohaupt** [comment]
Done!
