### ISSUE TITLE
Camera quitting

### ISSUE THREAD

**Issue by dfok** [vkohaupt/vokoscreenNG#54]
In the latest version of the code the camera fails a couple of seconds after activating it. In the 3.0.2 release this problem does not occur. Perhaps my log is helpful to help solve this:

[vokoscreenNG] Version: 3.0.2
[vokoscreenNG] Locale: en_US
[vokoscreenNG] Log from: 2020-03-18 11:58:35
[vokoscreenNG] Country: United States
[vokoscreenNG] Qt: 5.12.4
[vokoscreenNG] GStreamer 1.16.1
[vokoscreenNG] Operating system: Ubuntu 19.10
[vokoscreenNG] CPU Architecture: x86_64
[vokoscreenNG] vokoscreenNG running as: xcb client
[vokoscreenNG] vokoscreenNG running on: x11
[vokoscreenNG] Desktop: ubuntu:GNOME
[vokoscreenNG] Icon-Theme: Adwaita
[vokoscreenNG] Styles: (Windows, Fusion)
[vokoscreenNG] Qt-PluginsPath:      /usr/lib/x86_64-linux-gnu/qt5/plugins
[vokoscreenNG] Qt-TranslationsPath: /usr/share/qt5/translations
[vokoscreenNG] Qt-LibraryPath:      /usr/lib/x86_64-linux-gnu
[vokoscreenNG] Settings: /home/xxxx/.config/vokoscreenNG/vokoscreenNG.ini
[vokoscreenNG] Log: /home/xxxx/.config/vokoscreenNG/log/2020_03_18_11_58_35.log
[vokoscreenNG] CompositingManager running: true

[vokoscreenNG] [PulseAudio] Found: Monitor of Built-in Audio Analog Stereo Device: alsa_output.pci-0000_00_1b.0.analog-stereo.monitor
[vokoscreenNG] [PulseAudio] Found: Built-in Audio Analog Stereo Device: alsa_input.pci-0000_00_1b.0.analog-stereo

[vokoscreenNG] Symbols: + available, - not available
[vokoscreenNG] + matroskamux
[vokoscreenNG] + webmmux
[vokoscreenNG] + avimux
[vokoscreenNG] + mp4mux
[vokoscreenNG] + qtmux
[vokoscreenNG] + x264enc
[vokoscreenNG] - openh264enc
[vokoscreenNG] - vaapih264enc
[vokoscreenNG] - vaapimpeg2enc
[vokoscreenNG] + vp8enc
[vokoscreenNG] + vorbisenc
[vokoscreenNG] + flacenc
[vokoscreenNG] + opusenc
[vokoscreenNG] + lamemp3enc

[vokoscreenNG] + ximagesrc
[vokoscreenNG] + pulsesrc
[vokoscreenNG] - pipewiresrc
[vokoscreenNG] + queue
[vokoscreenNG] + capsfilter
[vokoscreenNG] + videoconvert
[vokoscreenNG] + videorate
[vokoscreenNG] + audioconvert
[vokoscreenNG] + audiorate
[vokoscreenNG] + filesink
[vokoscreenNG] + videoscale
[vokoscreenNG] + h264parse
[vokoscreenNG] + adder

[vokoscreenNG] Name from screen:  eDP-1
[vokoscreenNG] Screen available desktop width : 3840
[vokoscreenNG] Screen available desktop height: 2160
[vokoscreenNG] DevicePixelRatio: 2  (Normal displays is 1, Retina display is 2)
[vokoscreenNG] Vertical refresh rate of the screen in Hz: 59
[vokoscreenNG] Screen orientation Qt::LandscapeOrientation
[vokoscreenNG] Color depth of the screen:  24
[vokoscreenNG] Model from screen:  
[vokoscreenNG] Manufactur from screen:  Sharp Corporation
[vokoscreenNG] SerialNumber from screen:  
[vokoscreenNG] ItemText in Combobox: eDP-1 :  3840 x 2160
[vokoscreenNG] ItemData in Combobox: x=0 y=0 with=3840 height=2160

[vokoscreenNG] ExtensionsPath: /home/dfok/vokoscreen_extensions/
[vokoscreenNG] No library for extension found
 
[vokoscreenNG] Desktop session is a X11 session
[vokoscreenNG] QCamera::LoadingStatus
[vokoscreenNG] QCamera::LoadedState
[vokoscreenNG] QCamera::LoadedStatus
[vokoscreenNG] QCamera::StartingStatus
[vokoscreenNG] QCamera::ActiveState
[vokoscreenNG] QCamera::ActiveStatus
Removed Camera "/dev/video0"
[vokoscreenNG] QCamera::LoadingStatus
[vokoscreenNG] QCamera::LoadedState
[vokoscreenNG] QCamera::LoadedStatus
[vokoscreenNG] QCamera::StartingStatus
[vokoscreenNG] QCamera::ActiveState
[vokoscreenNG] QCamera::ActiveStatus
Removed Camera "/dev/video0"

**Comment by vkohaupt** [comment]
Thanks for the hint. Since to day work on it. The mistake crept in here in the current master. https://github.com/vkohaupt/vokoscreenNG/commit/059ef74d45c19e67b018491a8f724b33ee6dff0b
I have merged the Linux and Windows code. So I have only one code base.

**Comment by vkohaupt** [comment]
I fixed the problem. About feedback I would be happy.

**Comment by dfok** [comment]
Problem solved! Thanks for the quick fix.
