### ISSUE TITLE
Qt: Session Management Error In Manjaro Snap Package

### ISSUE THREAD

**Issue by masterplayer30** [vkohaupt/vokoscreenNG#57]
I get this every time I launch the app.

[bobby@bobby-celes ~]$ vokoscreen-ng
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
Fontconfig warning: FcPattern object weight does not accept value [40 210)
Segmentation fault (core dumped)

Any fixes?

**Comment by vkohaupt** [comment]
Please consult the Manjaro maintainer, he has to fix that. I can not do anything.
