### ISSUE TITLE
Make this application available as flatpak on FlatHub [packaging]

### ISSUE THREAD

**Issue by Nokia808** [vkohaupt/vokoscreenNG#58]
Hi. 1st of all, I would to say thank you too much for creation & developing this very excellent application.

I would like to suggest on you making this application available as a flatpak on FlatHub. Flatpak is much better than snap from both security & compatibility points of view.

**Comment by vkohaupt** [comment]
Yes that will come. Please wait. I make all Step by Step.

**Comment by Nokia808** [comment]
@vkohaupt 
Thank you very much. 
Only one question. Being a developer & expert, I would like to ask: if I have flatpak package & .rpm package (I'm a Fedora user) for an application & both of same version, which is better in your opinion to be used, .rpm or flatpack ? I'm very confusing about this. Shotcut in their official page recommend to use flatpak/snap but I test flatpak of shotcut since 2 days & it is buggy while same version is existing as .rpm in RPMFusion repositories (semi-official Fedora repositories) did not show me such buggy behaviour though I use .rpm package since many years. From other side, I use Telegram & Ferdi messengers & LibreOffice as flatpak without problem !

**Comment by Mailaender** [comment]
See https://github.com/flathub/flathub/pull/3179
