### ISSUE TITLE
Where can I found extensions for vokoscreen? [Question]

### ISSUE THREAD

**Issue by Nokia808** [vkohaupt/vokoscreenNG#59]
As the title saying, where can I find them?

**Comment by vkohaupt** [comment]
That was for me, to testing. I have deactivate. Thanks for the hint.

**Comment by Nokia808** [comment]
@vkohaupt 
I have to inform you that when I wrote this issue, & was installed "vokoscreen" from RPMFusion repositories because I did not notice that "vokoscreenNG" available in official Fedora repositories.
Today, at morning, I noticed your instruction for installation on Fedora "sudo dnf install vokoscreenNG" & I saw the screenshot for your new version on GitHub, so I remove vokoscreen (old version) & install vokoscreenNG (new version 3.0.2). Indeed the new version do not contain tab for extensions opposite to old version. This what made me asking about extensions. Sorry for that confusion. You are indeed already deactivate "extension tab" in new version.
