### ISSUE TITLE
having "gstreamer-plugin-pipewire" installed is causing crashes

### ISSUE THREAD

**Issue by ahjolinna** [vkohaupt/vokoscreenNG#6]
I just installed git version of vokoscreenNG on openSUSE tumbleweed, and It seems to crash everytime if you have "gstreamer-plugin-pipewire" installed but works just fine if you uninstall that pkgs...

[crash log file](https://pastebin.com/raw/vGsGytzH)

**Comment by vkohaupt** [comment]
Your log say:
can't load /usr/lib64/spa/support/libspa-support.so: /usr/lib64/spa/support/libspa-support.so: cannot open shared object file: No such file or directory

libspa-support.so is in the package pipewire-spa-plugins
Please install pipewire-spa-plugins

Please open a bug on Tumbelweed:
gstreamer-plugin-pipewire require package pipewire-spa-plugins.
The gstreamer-plugin-pipewire can not work without pipewire package.
