### ISSUE TITLE
Where is changelog for new versions?

### ISSUE THREAD

**Issue by MurzNN** [vkohaupt/vokoscreenNG#62]
Thanks for releasing new versions of so useful program! But where can we read changelog with list of fixes and new features, implemented in each release? Before, as I remember, there are was CHANGELOG.md in git repo, but now can't find it.

**Comment by MurzNN** [comment]
Found it in your website https://linuxecke.volkoh.de/vokoscreen/vokoscreen-changes.html - will be good to include it into git repository too.

**Comment by tux93** [comment]
I agree that the changes should be listed on the release tags

**Comment by vkohaupt** [comment]
I have added a CHANGELOG.md with this content.

The changelog found here:
https://linuxecke.volkoh.de/vokoscreen/vokoscreen-changes.html

This is for me the best practice. Not all User find the way to github.
Thanks.
