### ISSUE TITLE
Security warning in Windows installation

### ISSUE THREAD

**Issue by be-nice-do-better** [vkohaupt/vokoscreenNG#65]
Is it possible to remove/disable the Windows security warning when trying to install in Windows 10?
Also, anti virus software giving other warning from other users' feedback.

![image](https://user-images.githubusercontent.com/12386794/78237327-a891cd00-7537-11ea-8ae4-217dce200f67.png)
![image](https://user-images.githubusercontent.com/12386794/78237341-ac255400-7537-11ea-922d-676e5352597f.png)
![image](https://user-images.githubusercontent.com/12386794/78237548-f6a6d080-7537-11ea-8225-be9927e61741.png)

**Comment by vkohaupt** [comment]
The installer has no certificate, that's all.
