### ISSUE TITLE
Huge difference in file size between vokoscreenNG & vokoscreen (old) on Fedora Linux

### ISSUE THREAD

**Issue by Nokia808** [vkohaupt/vokoscreenNG#66]
Hi. On my Fedora Linux there are 2 packages of your application: vokoscreenNG (the new version 3.0.2 from official Fedora repositories) & vokoscreen (old version 2.5.8 beta from RPMFusion repositories).

I tried both of them, & unfortunately, I return back to old version 2.5.8 beta from RPMFusion because the huge size on new version for same time record of same content with same format & codecs selection ! The difference is as much as 5 times !

I record video lecture of 60 minutes by old version using .mkv with libx264 for video & libvorbis for audio. The result was just about 97 MB. But same record (lecture) I repeated with new version using .mkv & x264 for video & vorbis for audio gave me 500 MB ! I tried various combinations of format & codecs but without hope ! So, I removed vokoscreenNG & return to vokoscreen (old version) ..... !

Why this huge difference ? New version seem to be non-practical .......

Can you fix this please. I installed on my system all available Gstreamer codecs from GNOME software center & tried all of them but without benefit !

**Comment by vkohaupt** [comment]
The content of the two videos is definitely not the same. The file size suggests that there is a lot of additional motion in the video.

Default settings of h264
vokoscreen: preset = veryfast and quality = 23
vokoscreenNG: preset = veryfast and quality = 17

If you want to compare, then please with exactly the same requirements and exactly the same video content.

**Comment by vkohaupt** [comment]
Correction:
vokoscreen: preset = superfast and quality = 23

**Comment by Nokia808** [comment]
@vkohaupt 
Thank you for response. 
Regarding the contents, they are exactly the same (99%)

On my system vokoscreenNG preset = superfast (not very fast) & quality = 17 with default setting of X264

So, I have to do other test with vokoscreenNG with maintain superfast (default on my system) & changing quality from 17 to 23. Okay, but please could you more clear about "h264": is it the same of X264 or not ? I have the following codecs options for video .mkv format:
- X264 (the default)
- openh264
- VP8
what you mean by h264? Do you mean openh264? If yes, then I have to change from X264 (default) to openh264

I'm waiting your kind replay.

**Comment by vkohaupt** [comment]
> @vkohaupt
> Thank you for response.
> Regarding the contents, they are exactly the same (99%)

No, it's less.
You can easily get a video of 130MB in a minute by quickly changing the picture. Record a black picture and the video is smaller than 500KB.

>Okay, but please could you more clear about "h264": is it the same of X264 or not ?

X264 is an encoder from Videolan and saves the video in H.264 / MPEG-4 AVC format.
Openh264 is from cisco and also saves the video in H.264 / MPEG-4 AVC format.

The licenses from X264 and openh264 are different.
But to be able to say something about it, you almost have to write a doctoral thesis.

**Comment by Nokia808** [comment]
@vkohaupt 
Okay, but which I have to use, X264 or openh264 to achieve the smallest possible size?

**Comment by Nokia808** [comment]
@vkohaupt 
Hi. I tested new version (vokoscreenNG) using .mkv with X264, superfast, quality=23. There was an improvement in size of output file. But I think quality should be reduced to 25 (not 23) to achieve size slightly larger that that of vocoscreen (old version). I did not tried openh264 .....

Please keep this issue opened for few days, because I will perform more accurate examination to be sure 100% that quality should be setted at 25 not 23 .....

But I discovered bug in old version: can not record beyond 1 hr & 6 minutes ! It apparently seem to be recording but after finishing record I discovered that it record only 1 hr & 6 minutes not more ! I tried 2 occasions: 1st for 2 hrs & 2nd for 1&1/2 hrs & in both cases it recorded only 1 hr & 6 minutes. I wish this error not existing in new version that is now only version on my system.

**Comment by Nokia808** [comment]
@vkohaupt 
Hi dear. Yet, I finished recording of a lecture when I spook for 1 hr & 20 minutes. I used new version "VokoscreenNG version 3.0.2" with .mkv (X264 for video + vorbis for audio), superfast & quality = 25
This setting gave me 212.5 MB, while when I recorded 1 hr & 28 minutes using old version "vokoscreen" with .mkv using it's default setting, it gave me file size only 200.9 MB ! So, indeed VokoscreenNG generate bigger file size !

**Comment by Nokia808** [comment]
@vkohaupt 
By the way, the new version (VokoscreenNG) can record beyond 1 hr & 6 minutes limit without interruption, so it fortunately not suffer from bug in old version which prevent it from recording beyond this limit.

Please notice that when I said in my previous comment that [while when I recorded 1 hr & 28 minutes using old version "vokoscreen" .....] the old version stop from recording beyond 1 hr & 6 minutes & I used to complete lecture by 2nd session of recording & then I joined 2 output files, 1st & 2nd using a program perform this without re-encoding or transcoding so that joining process not resulted in enlargement in size of final united file beyond algebraic summation of sizes of 2 original files.
