### ISSUE TITLE
Command line options?

### ISSUE THREAD

**Issue by DanitiKain** [vkohaupt/vokoscreenNG#67]
I wasn't able to find out what the command line options were using the help option. Can you please share those in the readme file?

**Comment by vkohaupt** [comment]
I have revised the command line option. This now looks like this.

./vokoscreenNG -h

Usage: vokoscreenNG [Option] [File or URL]

Options: 
  -h or --help        Print this message
  -v or --version     Print version 

File or Url:
  Play a video
    Example file:
      vokoscreenNG /path/video

    Exsample URL:
      vokoscreenNG http://www.rapconverter.com/SampleDownload/Sample320.mp4
      vokoscreenNG http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_normal.mp4

**Comment by DanitiKain** [comment]
There use to be command line options for starting a recording and setting the option. This allowed me to setup shortcut keys to start a recording which was helpful. Are there any plans to bring back these options. It would be nice to have command line options for all the gui interface options.

**Comment by DanitiKain** [comment]
Setup Vokoscreen Shortcuts:

a. vokoscreen --startrecord --setFullScreen --setAudioOn

b. vokoscreen --stoprecord

c. vokoscreen --startrecord --setFullScreen --setAudioOn --setWebcamOn

d. vokoscreen --quit


Example these were really handy with older version I believe c would not work but the rest did. Can these be implemented back into NG?

**Comment by vkohaupt** [comment]
Let's see what can be done. But it doesn't have a high priority. Other tasks are more important to me at the moment. Please ask again in one or two years.

**Comment by EWouters** [comment]
Just shortcut a. and d. would be very useful so I can start recording at boot and stop before shutdown.

**Comment by elig0n** [comment]
Command line arguments or signals (i.e. SIGUSR1/2) to start and stop recording can come handy for scripting, cron jobs etc... Would you consider implementing them today?

**Comment by vkohaupt** [comment]
Yes, I'll do it today and it'll be ready in two hours.
You can then pick it up with a certificate and a pink ribbon.

Hey guys, this isn't a pizza delivery place.

**Comment by elig0n** [comment]
I can wait just 5 more minutes  😂 just kidding ...
Now seriously you said to ask  again in a few years.

**Comment by vkohaupt** [comment]
Porting to Qt6 has been in progress for over two months. This will also take a few months.
What comes next is written in the stars.
Possibly Wayland will be tackled and large parts of it will have to be rewritten. But this requires a 100% functional distribution and a 100% functional Wayland desktop. Estimated development time 1 to 2 years until all functions are implemented. It will start at the earliest when KDE Plasma 6 is delivered with Wayland as standard.

For information to all, donations are urgently needed.
If someone needs a function and can pay the hours please contact me. Special functions are given preferential treatment.

**Comment by inoculator** [comment]
Hi.
just new to vokoscreenNG.
Have installed it on Mint using Flatpak. Missing command line options for scripting. Any progress on this matter here?
