### ISSUE TITLE
Area capture shows top border

### ISSUE THREAD

**Issue by brewerja** [vkohaupt/vokoscreenNG#68]
Rather than recording only the area within the green rectangle, the width of the top adjustment icon is also include on top.

https://youtu.be/t3s_X8EsqtE

Compiling from source on Ubuntu 18.04.4

**Comment by vkohaupt** [comment]
I have tested with GNOME, but GNOME is not ubuntu:GNOME
The bug is fixed, please test it.
Thanks for the hint.

**Comment by brewerja** [comment]
Looks good. Thanks for the quick work!
