### ISSUE TITLE
Hidden Camera

### ISSUE THREAD

**Issue by goparklubanic** [vkohaupt/vokoscreenNG#69]
I am trying to create presentation with inset camera using vokoscreen-ng on debian linux installed via snap. When LibreOffice Impress opened, the camera window of vokoscreen-ng still  "on top layer", but when the presentation started, the camera window moved to behind the presentation layer.
I have set it ( camera window ) to be "Keep Above Others" via context menu, but it didn't work.

The video demo is on https://youtu.be/lS_UCf7uumQ
Hope this issue will be solved. Thanks.

**Comment by vkohaupt** [comment]
I see you have vokoscreenNG 3.0.1. The last Bug-Fix Release is 3.0.3
https://linuxecke.volkoh.de/vokoscreen/vokoscreen-changes.html

All who read here, please consult the Snap Maintainer that he will import the latest bugfix release in the near future.

I make Bugfix on Bugfix but she comes not to the user.

I see only opensuse and Fedora very quickly. Thanks to the opensuse and Fedora maintainers.

On Debian i see unstable and testing has 3.0.3. Thanks to the Debian Maintainer.
But why is 3.0.1 in Buster-Backports and not 3.0.3

**Comment by vkohaupt** [comment]
If snapcraft has imported the latest bugfix release, I will fix it. Please inform me.
