### ISSUE TITLE
Audio only recording via vokoscreen without video stream in Linux

### ISSUE THREAD

**Issue by MurzNN** [vkohaupt/vokoscreenNG#7]
I try to find easy tool (eg for my grandma) to simple audio call recording in Linux (eg for record Skype call with my and remote side voice), but find nothing!

I need simple tool with one large button "Start" like `vokoscreen`, that can save several streams simultaneously (eg speaker and microphone).

We have `Gnome Sound Recorder` and `KWave` tools, but none of them can save both channels simultaneously - I can save only my voice, or remote voice, not both!

We have `Audacious`, but it have too many functions and look like professional tool, and regular users will afraid to use it.

And we have `vokoscreen` tool, that can easy record sound from two audio sources simultaneously via simple "Start" button, but it need to record video too, so if I want to save audio only, I must select small part of screen to make record with not large size. 

So, can you make saving video not obligatory, for give users simple tool for audio-only recording? In interface we can simply add checkbox "Video" like in audio tab, and that's all!

If this is not too hard to implement, can you add option to make recording without video, in next coming versions? Thanks!

**Comment by vkohaupt** [comment]
Klinkt Intressant, ist aber nicht so einfac einzubauen.
