### ISSUE TITLE
vokoscreenNG snap pulseaudio breaks system (linux Mint 18.3) pulseaudio

### ISSUE THREAD

**Issue by tshann** [vkohaupt/vokoscreenNG#70]
I LOVE vokoscreenNG! When starting it, I had the big red X under audio and read your fix - installing the snap version of pulseaudio. Certainly this may NOT be your issue, but I'm not sure where else to put it. Anyway, on to the issue. Once I installed the snap pulseaudio, I immediately lost system pulseaudio. I went through the common process of purging pulseaudio and re-installing it and that worked. Only to find on every reboot, I had to do similar workarounds to get both to work. Finally I took out the snap pulseaudio, purged the system's pulseaudio, re-installed it and rebooted. Problem solved ... except now vokoscreenNG has NO audio. So not a real fix. Any solution, workaround, fix so I can have both awesome programs working?

**Comment by vkohaupt** [comment]
The best way is, go to a Linux Mint forum.

**Comment by tshann** [comment]
Hi Volker,
   Thanks for the input. I did poke around on their forum, which gave me an
idea. The workaround (I'm sure there's a better solution) so far is to
simply put "pulseaudio -D" in the xfce startup group. So far, seems to
solve the problem - I get your great program AND the system's pulseaudio
works like normal too. Thanks!

Peace

Tim Shannon, ND
205 Clark Place SE
Tumwater, WA 98501
office: 360-570-0401
fax:     360-570-2060
drtim@heartofwellness.org
www.heartofwellness.org

**Comment by tshann** [comment]
I found that simply putting pulseauido -D in the xfce startup file gave me both - pulseaudio for the awesome vokoscreenNG AND systemwide pulseaudio working a treat too.

Thanks again for the awesome software!
