### ISSUE TITLE
Show mouse click

### ISSUE THREAD

**Issue by hugorn** [vkohaupt/vokoscreenNG#71]
Hello everyone.
I was unable to locate the option to highlight the mouse click as I had in previous versions. Has this feature been removed?

**Comment by vkohaupt** [comment]
No i have not removed. The old code was so bad that I couldn't get it installed. I must write new.

**Comment by vitovt** [comment]
I need this feature. Still use Vokoscreen (without NG) just because of mouse click highlighting.
