### ISSUE TITLE
.desktop file and manpage

### ISSUE THREAD

**Issue by eribertomota** [vkohaupt/vokoscreenNG#72]
Hi @vkohaupt,

Debian has a .desktop file[1] and a basic manpage[2] for vokoscreenNG. Feel free to use it if you want it. Otherwise, please, close this bug.

[1] https://salsa.debian.org/debian/vokoscreen-ng/-/blob/debian/master/debian/vokoscreenNG.desktop
[2] https://salsa.debian.org/debian/vokoscreen-ng/-/tree/debian/master/debian%2Fmanpage

Cheers,

Eriberto

**Comment by vkohaupt** [comment]
I replace my .desktop file with your .desktop file. Yours makes a better impression.

https://salsa.debian.org/debian/vokoscreen-ng/-/commit/02692272e2f970c97ef88f9c7513256e846684bd
Need you the vokoscreenNG.xpm for other things or can delete?

**Comment by eribertomota** [comment]
Yes, you can delete. Thanks!
