### ISSUE TITLE
Screen is green when tried to play the recorded video using the Play button

### ISSUE THREAD

**Issue by asarkar2** [vkohaupt/vokoscreenNG#74]
Thanks for the vokoscreen-ng. I am using it for the time being.
However, I found that the Play button doesn't play the video - it only shows a green screen. Audio, however, is fine. Playing the recorded video via smplayer/vlc however, works just fine.

After some googling on the internet, I found that a workaround. Removed the gstreamer1.0-vaapi package and now the video plays fine using the Play button.

Is there are a better way to resolve this issue?

**Comment by vkohaupt** [comment]
I need more Info from CPU and Graphic card.
Start vokoscreenNG from a terminal. Click Play. Copy the complete output and and show it here.

**Comment by asarkar2** [comment]
The following is the terminal output. 

[vokoscreenNG] Version: 3.0.2
[vokoscreenNG] Locale: en_US
[vokoscreenNG] Log from: 2020-04-23 09:44:29
[vokoscreenNG] Country: UnitedStates
[vokoscreenNG] Qt: 5.9.5
[vokoscreenNG] GStreamer 1.14.5
[vokoscreenNG] Operating system: Ubuntu 18.04.4 LTS
[vokoscreenNG] CPU Architecture: x86_64
[vokoscreenNG] vokoscreenNG running as: xcb client
[vokoscreenNG] vokoscreenNG running on: x11
[vokoscreenNG] Desktop: XFCE
[vokoscreenNG] Icon-Theme: Adwaita
[vokoscreenNG] Styles: (Windows, Fusion)
[vokoscreenNG] Qt-PluginsPath:      /usr/lib/x86_64-linux-gnu/qt5/plugins
[vokoscreenNG] Qt-TranslationsPath: /usr/share/qt5/translations
[vokoscreenNG] Qt-LibraryPath:      /usr/lib/x86_64-linux-gnu
[vokoscreenNG] Settings: /home/anjishnu/.config/vokoscreenNG/vokoscreenNG.ini
[vokoscreenNG] Log: /home/anjishnu/.config/vokoscreenNG/log/2020_04_23_09_44_29.log
[vokoscreenNG] CompositingManager running: false

[vokoscreenNG] [PulseAudio] Found: Monitor of Built-in Audio Analog Stereo Device: alsa_output.pci-0000_00_1b.0.analog-stereo.monitor
[vokoscreenNG] [PulseAudio] Found: Built-in Audio Analog Stereo Device: alsa_input.pci-0000_00_1b.0.analog-stereo

[vokoscreenNG] Symbols: + available, - not available
[vokoscreenNG] + matroskamux
[vokoscreenNG] + webmmux
[vokoscreenNG] + avimux
[vokoscreenNG] + mp4mux
[vokoscreenNG] + qtmux
[vokoscreenNG] + x264enc
[vokoscreenNG] - openh264enc
[vokoscreenNG] - vaapih264enc
[vokoscreenNG] - vaapimpeg2enc
[vokoscreenNG] + vp8enc
[vokoscreenNG] + vorbisenc
[vokoscreenNG] + flacenc
[vokoscreenNG] + opusenc
[vokoscreenNG] + lamemp3enc

[vokoscreenNG] + ximagesrc
[vokoscreenNG] + pulsesrc
[vokoscreenNG] + queue
[vokoscreenNG] + capsfilter
[vokoscreenNG] + videoconvert
[vokoscreenNG] + videorate
[vokoscreenNG] + audioconvert
[vokoscreenNG] + audiorate
[vokoscreenNG] + filesink
[vokoscreenNG] + videoscale
[vokoscreenNG] + h264parse
[vokoscreenNG] + adder

[vokoscreenNG] Name from screen:  LVDS-1
[vokoscreenNG] Screen available desktop width : 1280
[vokoscreenNG] Screen available desktop height: 800
[vokoscreenNG] DevicePixelRatio: 1  (Normal displays is 1, Retina display is 2)
[vokoscreenNG] Vertical refresh rate of the screen in Hz: 60
[vokoscreenNG] Screen orientation Qt::ScreenOrientation(LandscapeOrientation)
[vokoscreenNG] Color depth of the screen:  24
[vokoscreenNG] Model from screen:  
[vokoscreenNG] Manufactur from screen:  
[vokoscreenNG] SerialNumber from screen:  
[vokoscreenNG] ItemText in Combobox: LVDS-1 :  1280 x 800
[vokoscreenNG] ItemData in Combobox: x=0 y=0 with=1280 height=800

[vokoscreenNG] [Camera] Found: HP Webcam: HP Webcam Device: video0

[vokoscreenNG] ExtensionsPath: /home/anjishnu/vokoscreen_extensions/
[vokoscreenNG] No library for extension found
 
[vokoscreenNG] Desktop session is a X11 session
radioButtonScreencastFullscreen=false
radioButtonScreencastWindow=true
radioButtonScreencastArea=false
checkBoxCameraOnOff=false
checkBoxCameraMirrorVertical=false
checkBoxCameraMirrorHorizontal=true
checkBoxCameraInvert=false
checkBoxCameraGray=false
checkBoxCameraMono=false
checkBoxCameraWindowFrame=false
checkBoxShowInSystray=true
checkBoxShowInSystrayAlternative=true
checkBoxMinimizedWhenRecordingStarts=false
checkBoxStartsMinimized=false
checkBoxResetAtNextStart=false
checkBoxLookForUpdates=true
checkBoxMouseCursorOnOff=false
checkboxAudioDevice-0=false
checkboxAudioDevice-1=true
checkBoxMagnifier=false
comboBoxCamera=HP Webcam: HP Webcam
comboBoxOnlineHelp=Automatically
comboBoxFormat=mkv
comboBoxVideoCodec=x264
comboBoxx264Preset=superfast
comboBoxAudioCodec=vorbis
comboBoxAreaSize=320 x 200 CGA 16 : 10
comboBoxScreencastScreen=LVDS-1 :  1280 x 800
sliderVolume=70
sliderVideo=0
sliderCameraWindowSize=2
sliderHour=0
sliderMinute=0
sliderStopRecordingAfterHouers=0
sliderStopRecordingAfterMinutes=0
sliderStopRecordingAfterSeconds=15
sliderLimitOfFreeDiskSpace=250
sliderShowInSystrayAlternative=48
sliderSecondWaitBeforeRecording=0
sliderX264=17
sliderOpenh264=23
sliderFrames=25
sliderScreencastCountDown=3
sliderMagnification=2
lineEditVideoPath=/home/anjishnu/Videos
[vokoscreenNG] Start record with: ximagesrc display-name=:0.0 use-damage=false show-pointer=true xid=79691786 ! video/x-raw, framerate=25/1 ! videoconvert ! videorate ! videoscale ! video/x-raw, width=938, height=750 ! x264enc qp-min=17 qp-max=17 speed-preset=superfast threads=4 ! video/x-h264, profile=baseline ! queue ! mux. pulsesrc device=alsa_input.pci-0000_00_1b.0.analog-stereo ! audio/x-raw, channels=2 ! audioconvert ! audiorate ! vorbisenc ! queue ! mux. matroskamux name=mux writing-app=vokoscreenNG_3.0.2 ! filesink location=/home/anjishnu/Videos/vokoscreenNG-2020-04-23_09-44-43.mkv
 
gst-launch-1.0 -e \
    ximagesrc display-name=:0.0 use-damage=false show-pointer=true xid=79691786 \
        ! video/x-raw, framerate=25/1 \
        ! videoconvert \
        ! videorate \
        ! videoscale \
        ! video/x-raw, width=938, height=750 \
        ! x264enc qp-min=17 qp-max=17 speed-preset=superfast threads=4 \
        ! video/x-h264, profile=baseline \
        ! queue \
        ! mux. \
    pulsesrc device=alsa_input.pci-0000_00_1b.0.analog-stereo \
        ! audio/x-raw, channels=2 \
        ! audioconvert \
        ! audiorate \
        ! vorbisenc \
        ! queue \
        ! mux. \
    matroskamux name=mux writing-app=vokoscreenNG_3.0.2 \
        ! filesink location=/home/anjishnu/Videos/vokoscreenNG-2020-04-23_09-44-43.mkv

[vokoscreenNG] Stop record
[vokoplayer] QMediaPlayer::PlayingState
[vokoplayer] QMediaPlayer::StoppedState

**Comment by asarkar2** [comment]
Given below is the terminal output. Let me know if you need any more information or not.

[vokoscreenNG] Version: 3.0.2
[vokoscreenNG] Locale: en_US
[vokoscreenNG] Log from: 2020-04-23 09:44:29
[vokoscreenNG] Country: UnitedStates
[vokoscreenNG] Qt: 5.9.5
[vokoscreenNG] GStreamer 1.14.5
[vokoscreenNG] Operating system: Ubuntu 18.04.4 LTS
[vokoscreenNG] CPU Architecture: x86_64
[vokoscreenNG] vokoscreenNG running as: xcb client
[vokoscreenNG] vokoscreenNG running on: x11
[vokoscreenNG] Desktop: XFCE
[vokoscreenNG] Icon-Theme: Adwaita
[vokoscreenNG] Styles: (Windows, Fusion)
[vokoscreenNG] Qt-PluginsPath:      /usr/lib/x86_64-linux-gnu/qt5/plugins
[vokoscreenNG] Qt-TranslationsPath: /usr/share/qt5/translations
[vokoscreenNG] Qt-LibraryPath:      /usr/lib/x86_64-linux-gnu
[vokoscreenNG] Settings: /home/xxxxxx/.config/vokoscreenNG/vokoscreenNG.ini
[vokoscreenNG] Log: /home/xxxxxx/.config/vokoscreenNG/log/2020_04_23_09_44_29.log
[vokoscreenNG] CompositingManager running: false

[vokoscreenNG] [PulseAudio] Found: Monitor of Built-in Audio Analog Stereo Device: alsa_output.pci-0000_00_1b.0.analog-stereo.monitor
[vokoscreenNG] [PulseAudio] Found: Built-in Audio Analog Stereo Device: alsa_input.pci-0000_00_1b.0.analog-stereo

[vokoscreenNG] Symbols: + available, - not available
[vokoscreenNG] + matroskamux
[vokoscreenNG] + webmmux
[vokoscreenNG] + avimux
[vokoscreenNG] + mp4mux
[vokoscreenNG] + qtmux
[vokoscreenNG] + x264enc
[vokoscreenNG] - openh264enc
[vokoscreenNG] - vaapih264enc
[vokoscreenNG] - vaapimpeg2enc
[vokoscreenNG] + vp8enc
[vokoscreenNG] + vorbisenc
[vokoscreenNG] + flacenc
[vokoscreenNG] + opusenc
[vokoscreenNG] + lamemp3enc

[vokoscreenNG] + ximagesrc
[vokoscreenNG] + pulsesrc
[vokoscreenNG] + queue
[vokoscreenNG] + capsfilter
[vokoscreenNG] + videoconvert
[vokoscreenNG] + videorate
[vokoscreenNG] + audioconvert
[vokoscreenNG] + audiorate
[vokoscreenNG] + filesink
[vokoscreenNG] + videoscale
[vokoscreenNG] + h264parse
[vokoscreenNG] + adder

[vokoscreenNG] Name from screen:  LVDS-1
[vokoscreenNG] Screen available desktop width : 1280
[vokoscreenNG] Screen available desktop height: 800
[vokoscreenNG] DevicePixelRatio: 1  (Normal displays is 1, Retina display is 2)
[vokoscreenNG] Vertical refresh rate of the screen in Hz: 60
[vokoscreenNG] Screen orientation Qt::ScreenOrientation(LandscapeOrientation)
[vokoscreenNG] Color depth of the screen:  24
[vokoscreenNG] Model from screen:  
[vokoscreenNG] Manufactur from screen:  
[vokoscreenNG] SerialNumber from screen:  
[vokoscreenNG] ItemText in Combobox: LVDS-1 :  1280 x 800
[vokoscreenNG] ItemData in Combobox: x=0 y=0 with=1280 height=800

[vokoscreenNG] [Camera] Found: HP Webcam: HP Webcam Device: video0

[vokoscreenNG] ExtensionsPath: /home/xxxxxx/vokoscreen_extensions/
[vokoscreenNG] No library for extension found
 
[vokoscreenNG] Desktop session is a X11 session
radioButtonScreencastFullscreen=false
radioButtonScreencastWindow=true
radioButtonScreencastArea=false
checkBoxCameraOnOff=false
checkBoxCameraMirrorVertical=false
checkBoxCameraMirrorHorizontal=true
checkBoxCameraInvert=false
checkBoxCameraGray=false
checkBoxCameraMono=false
checkBoxCameraWindowFrame=false
checkBoxShowInSystray=true
checkBoxShowInSystrayAlternative=true
checkBoxMinimizedWhenRecordingStarts=false
checkBoxStartsMinimized=false
checkBoxResetAtNextStart=false
checkBoxLookForUpdates=true
checkBoxMouseCursorOnOff=false
checkboxAudioDevice-0=false
checkboxAudioDevice-1=true
checkBoxMagnifier=false
comboBoxCamera=HP Webcam: HP Webcam
comboBoxOnlineHelp=Automatically
comboBoxFormat=mkv
comboBoxVideoCodec=x264
comboBoxx264Preset=superfast
comboBoxAudioCodec=vorbis
comboBoxAreaSize=320 x 200 CGA 16 : 10
comboBoxScreencastScreen=LVDS-1 :  1280 x 800
sliderVolume=70
sliderVideo=0
sliderCameraWindowSize=2
sliderHour=0
sliderMinute=0
sliderStopRecordingAfterHouers=0
sliderStopRecordingAfterMinutes=0
sliderStopRecordingAfterSeconds=15
sliderLimitOfFreeDiskSpace=250
sliderShowInSystrayAlternative=48
sliderSecondWaitBeforeRecording=0
sliderX264=17
sliderOpenh264=23
sliderFrames=25
sliderScreencastCountDown=3
sliderMagnification=2
lineEditVideoPath=/home/xxxxxx/Videos
[vokoscreenNG] Start record with: ximagesrc display-name=:0.0 use-damage=false show-pointer=true xid=79691786 ! video/x-raw, framerate=25/1 ! videoconvert ! videorate ! videoscale ! video/x-raw, width=938, height=750 ! x264enc qp-min=17 qp-max=17 speed-preset=superfast threads=4 ! video/x-h264, profile=baseline ! queue ! mux. pulsesrc device=alsa_input.pci-0000_00_1b.0.analog-stereo ! audio/x-raw, channels=2 ! audioconvert ! audiorate ! vorbisenc ! queue ! mux. matroskamux name=mux writing-app=vokoscreenNG_3.0.2 ! filesink location=/home/xxxxxx/Videos/vokoscreenNG-2020-04-23_09-44-43.mkv
 
gst-launch-1.0 -e \
    ximagesrc display-name=:0.0 use-damage=false show-pointer=true xid=79691786 \
        ! video/x-raw, framerate=25/1 \
        ! videoconvert \
        ! videorate \
        ! videoscale \
        ! video/x-raw, width=938, height=750 \
        ! x264enc qp-min=17 qp-max=17 speed-preset=superfast threads=4 \
        ! video/x-h264, profile=baseline \
        ! queue \
        ! mux. \
    pulsesrc device=alsa_input.pci-0000_00_1b.0.analog-stereo \
        ! audio/x-raw, channels=2 \
        ! audioconvert \
        ! audiorate \
        ! vorbisenc \
        ! queue \
        ! mux. \
    matroskamux name=mux writing-app=vokoscreenNG_3.0.2 \
        ! filesink location=/home/xxxxxx/Videos/vokoscreenNG-2020-04-23_09-44-43.mkv

[vokoscreenNG] Stop record
[vokoplayer] QMediaPlayer::PlayingState
[vokoplayer] QMediaPlayer::StoppedState

**Comment by vkohaupt** [comment]
> Given below is the terminal output. Let me know if you need any more information or not.

CPU:
Graphic card:

**Comment by vkohaupt** [comment]
I think I have found a solution.
https://linuxecke.volkoh.de/vokoscreen/vokoscreen-download.html
-- Download the *.tar.gz
-- Extract the *.tar.gz
-- Install vokoscreenNG
-- Install gstreamer1.0-vaapi 
-- Start vokoscreenNG and check if it is the 3.0.3 version.

**Comment by asarkar2** [comment]
I will try out your solution by tonight. In the meantime, the information that you requested is given below.

I am on Ubuntu 18.04.

Output of lscpu:

Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               37
Model name:          Intel(R) Core(TM) i3 CPU       U 380  @ 1.33GHz
Stepping:            5
CPU MHz:             1043.980
CPU max MHz:         1333.0000
CPU min MHz:         666.0000
BogoMIPS:            2666.70
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            3072K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm arat flush_l1d


Output of lscpi -v (Only relevant part showing Graphics Card):

00:02.0 VGA compatible controller: Intel Corporation Core Processor Integrated Graphics Controller (rev 02) (prog-if 00 [VGA controller])
	Subsystem: Hewlett-Packard Company Core Processor Integrated Graphics Controller
	Flags: bus master, fast devsel, latency 0, IRQ 27
	Memory at b0000000 (64-bit, non-prefetchable) [size=4M]
	Memory at a0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at 3050 [size=8]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: [90] MSI: Enable+ Count=1/1 Maskable- 64bit-
	Capabilities: [d0] Power Management version 2
	Capabilities: [a4] PCI Advanced Features
	Kernel driver in use: i915
	Kernel modules: i915

**Comment by asarkar2** [comment]
Followed your instructions (including installing gstreamer1.0-vaapi) and installed version vokoscreen 3.0.3. Then I recorded a video and tried to play it using the Play button. However, the got the following message in the terminal:

`[vokoplayer] QMediaPlayer::PlayingState`
`Warning: QPainterPath::arcTo: Adding arc where a parameter is NaN, results are undefined ((null):0, (null))`
`Warning: QImage::scaled: Image is a null image ((null):0, (null))`
`[vokoplayer] QMediaPlayer::StoppedState`

The line `Warning: QImage::scaled: Image is a null image ((null):0, (null))` got repeated a lot of times. However, video now is a black screen (audio is fine) when using the Play button. 

Note that the video plays fine when I play it using an external video player.

**Comment by vkohaupt** [comment]
Hmm....
Works an recording with the video codec H.264 (Intel GPU)?
Are you sure that the CPU hardware decoding can?
What other software uses the packet gstreamer1.0-VAAPI?

**Comment by vkohaupt** [comment]
Have you installed the packet intel-vaapi-driver? Without this i have a black screen.

**Comment by asarkar2** [comment]
There is no intel-vaapi-driver package on ubuntu 18.04 in the repository.

However, there are two packages called `i965-va-driver` and `i965-va-driver-shaders` in the repository both of whose summary reads: `VAAPI driver for Intel G45 & HD Graphics family`.
These two packages are conflicting packages (installing one removes the other).

I installed both of them one by one, but I still get a black screen in both cases.

**Comment by asarkar2** [comment]
> Works an recording with the video codec H.264 (Intel GPU)?

My system cannot use the following video codecs: `H.264 (Intel GPU)`, `MPGE-2 (Intel GPU)`, `openh264`.
It can use the x264 video codec. All audio codecs are functional.

> What other software uses the packet gstreamer1.0-VAAPI?

I am not sure. I think I installed the `gstreamer1.0-vaapi` only for vokoscreenNG.

**Comment by asarkar2** [comment]
As a workaround, can vokoscreenNG have the option to play the video using external video players like vlc/mplayer if the inbuilt video player does not work?

**Comment by vkohaupt** [comment]
Indirectly yes. Use the Folder button.
