### ISSUE TITLE
"sudo make install" not working when installing version 3.0.3 from source

### ISSUE THREAD

**Issue by asarkar2** [vkohaupt/vokoscreenNG#75]
I was trying to compile and install vokoscreen-ng (version 3.0.3) from the source. 

The compilation was okay. However, when I tried to install by running the command `sudo make install` it said `make: Nothing to be done for 'install'`. I can run the software from the src directory via the command `./vokoscreenNG &`.

Shouldn't the Makefile support `make install`?

Note: I did finally install it via the repo `ppa:ubuntuhandbook1/apps`.

**Comment by vkohaupt** [comment]
> Shouldn't the Makefile support `make install`?

That's right. vokoscreenNG does not support "make install". The distributions with your package manager do it much better than I can ever do.
