### ISSUE TITLE
Windows Defender claims the linked codec pack contains a virus

### ISSUE THREAD

**Issue by lahvak** [vkohaupt/vokoscreenNG#77]
I installed Vokoscreen on a Windows 10 computer.  It works beautifully except not being to play back recorded movies.  I tried to install the codec pack linked from the github readme file, but windows defender refused to install it, claiming that there is a virus.  At about the same time, Defender reports removing a "coinminer" malware.  There seems to be a report about windows10codecpack at this website: https://any.run/report/7bbf4e545c077feee534aa9da4bf8bd89232875fe8658d8e136c1b6192fc5b7f/4ea273f4-4b6b-4277-bc59-8b7ec587e9f5

I must admit I know nothing about Windows, the laptop I installed it on was not mine, and I am now worried I did something bad.

**Comment by vkohaupt** [comment]
I'm sorry. I have withdrawn my recommendation and will not give any more in the future.

**Comment by lahvak** [comment]
No problem, I just wanted to warn you about this.  I love Vokoscreen and have been using in on Linux for years.  I think it is pretty brave of you to provide a version for Windows.  I have been dealing with Windows extensively last few days and it is nothing but pain in the ...

**Comment by vkohaupt** [comment]
Only Linux has been used here in the house since around 2002. My last Windows was a Windows 98. Only for vokoscreenNG I have a Windows in the Virtualbox.
Windows also has advantages, making packages is very easy. The absolute horror under Linux.
