### ISSUE TITLE
Man page should be updated to reflect the new version

### ISSUE THREAD

**Issue by tux93** [vkohaupt/vokoscreenNG#8]
Currently the man pages are still referring to vokoscreen:
- should be renamed to vokoscreenNG.1
- all occurrences of vokoscreen within the manpages should be updated
- the vokoscreen.log is now named with a timestamp of the start of the program, so the manpage should refer to that

Just putting this as an issue so it won't be forgotten before release ^^

**Comment by tux93** [comment]
Maybe it'd also make sense to ask for bug reports as Github issues instead of mails?

**Comment by vkohaupt** [comment]
Thanks for the hint, but i will completely remove the manpage, vokoscreenNG comes with an online help and documentation in different places I would like to avoid.

**Comment by tux93** [comment]
Alright, closing this and the PR then

**Comment by vkohaupt** [comment]
Ask for bug reports as Github issues instead of mails is a good idea, but i see no a easy way for the user.

**Comment by tux93** [comment]
The easiest one probably would be to add a button next to the "Send Report" one that opens
https://github.com/vkohaupt/vokoscreenNG/issues
in the users default browser
