### ISSUE TITLE
error while clicking folder button

### ISSUE THREAD

**Issue by mancoeg** [vkohaupt/vokoscreenNG#81]
### Error while clicking "folder" button

> No filemanager found.
> Please install a file manager.

VokoscreenNG 3.0.2
OS: windows 10

**Comment by vkohaupt** [comment]
The bug is fixed.
https://linuxecke.volkoh.de/vokoscreen/vokoscreen-changes.html
The next Bugfix-Release comes on 31.Apr.2020
