### ISSUE TITLE
How to Get Most Clear Screen Recording?

### ISSUE THREAD

**Issue by in2Rafi** [vkohaupt/vokoscreenNG#82]
Please see the recordings. This is recorded by Filmora https://streamable.com/8siqzw. Here you can see very crisp and clear video. Look at those windows 10 tiles please.
This one is recorded using Vokiscreen https://streamable.com/tdqrn9. Please look at the tiles. You will see little bit blurry images. 
The settings you can see from the videos. Ultrafast and Quality 0. And format is MKV.

Is there any settings I can tweak and get the crystal clear screen recording using Voko like Filmora?

**Comment by vkohaupt** [comment]
My-Video 1366x768
vokoscreenNG 1368x768
The vokoscreen Video is 2 Pixel larger in the width. This results in a blur. I fixed the bug and hope that so right. The next bugfix-release comes in three days.
Thanks for hint.

**Comment by in2Rafi** [comment]
Do I need to download windows installer from Vokoscreen website or I can update from inside of the app?

**Comment by vkohaupt** [comment]
Currently only by download, but is on the todo list. I am currently working on a Linux installer.
