### ISSUE TITLE
snap install on 18.04: KO

### ISSUE THREAD

**Issue by ComputingFroggy** [vkohaupt/vokoscreenNG#85]
Hello,
I am running Ubuntu 18.04 (from elementary Os).
I was trying vokoscreen (v. 2.5.0), which works fine, when I came across this NG version.
I tried the NG version.
I could not installed it from the repository packages, I had to use snap. When the videos recorded, produced zero size file. So basicaly, It's not usable for me ... luckily I can fall back to version 2.5.0 ! ;-)

On a side note, I regret there's no more the options Showkey and Showclick, in the NG version (although I can see quite a few interesting new features, e.g. presize capture frame, webcam size ...).

Thanks for producing a great software (it's going to replace SimpleScreenRecoder for me).

**Comment by vkohaupt** [comment]
I have tested under elementary Os. Without audio i can recording. With audio not. I make a debugging but i not see what is wrong.
I'm sorry, but after  three Hour intensive search don't know what is wrong with elementary Os.

I'm sorry, but after three Hour don't know what is wrong with elementary Os.
