### ISSUE TITLE
Some users cry about a bug with QT 5.15

### ISSUE THREAD

**Issue by Elrondo46** [vkohaupt/vokoscreenNG#86]
Can you fix this ?

https://pastebin.com/GYXzJ3cB

**Comment by vkohaupt** [comment]
Where is Qt 5.15?
https://download.qt.io/archive/qt/

**Comment by Elrondo46** [comment]
This is an unstable version I think

**Comment by Elrondo46** [comment]
https://download.qt.io/development_releases/qt/5.15/

**Comment by vkohaupt** [comment]
I see in your log:
../vokoscreenNG-3.0.4/src/region/QvkRegionButtonArrow.cpp:81:22: error: aggregate ‘QPainterPath painterPath’ has incomplete type and cannot be defined
   81 |         QPainterPath painterPath;

As far as i know QPainterPath is in qt < 5.15 not deprecated.
Is your Qt Installation correct?

**Comment by Elrondo46** [comment]
Don't know this is not my bug. I'm just the vokoscreen AUR packager, and this is not my business to solve bugs in devel branch of QT version for vokoscreen. Vokoscreen builds correctly to the stable version. The URL to answer to the user is: https://aur.archlinux.org/packages/vokoscreen/

**Comment by vkohaupt** [comment]
Thanks for the hint. The best way is we are waiting for the official release of Qt 5.15.
I close this issue, thanks for your work.
Volker
