### ISSUE TITLE
AAC audio codec in vokoscreenNG

### ISSUE THREAD

**Issue by wunderlich** [vkohaupt/vokoscreenNG#87]
Hello!

First of all, thank you very much for that great piece of software. I started creating educational videos and it works perfect!

At the moment, I'm using version 2.5.0 from the Ubuntu-PPA an did not know about vokoscreenNG, which I found recently. I just installed it from the ubuntuhandbook1-PPA and saw, that there is no possibility of choosing the AAC audio codec.

The following combination is the only one I found which is working directly at browsers for videos at webservers at Firefox, Chrome/Chromium AND Safari. With other audio codecs, there was no audio playback at Safari:

Format: mp4
Videocodec: libx264
Audiocodec: aac

I there a possibility to use this combination at vokoscreenNG? Or maybe there is another setup which works on mostly all systems at browsers (I am new at creating this kind of video)?

Thanks and kind regards!

**Comment by vkohaupt** [comment]
ubuntuhandbook1-PPA has vokoscreenNG 3.0.2
Audio codec AAC is supported from vokoscreenNG 3.0.4
Please tell the ubuntuhandbook1-PPA maintainer that he would like to update to 3.0.4.
Thanks Volker

**Comment by wunderlich** [comment]
Thank you for the quick support @vkohaupt!

The maintainer updated the package very fast, so I'm running vokoscreenNG 3.0.4 now. But I'm still not able to select the aac codec:

![image](https://user-images.githubusercontent.com/4471366/82222644-dd0feb80-9921-11ea-8c45-64af5de67704.png)

The package `ubuntu-restricted-extras` is already installed:

```
sudo apt-get install ubuntu-restricted-extras 
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
ubuntu-restricted-extras ist schon die neueste Version (66).
```
I have the same problem using the Windows version of vokoscreenNG, a friend of mine also.

**Comment by vkohaupt** [comment]
Unter Linux werden zusätzlich noch die Pakete faac und libfaac0 benötigt, so zumindestens mal hier mit der openSUSE 15.1. Unter Ubuntu sollten die Pakete vom Namen her gleich heißen.

Und unter Windows wird AAC wohl erst mit dem nächsten update funktioniern.
Das Problem ist das es mehrer ACC Implementierungen unter Linux gibt fdkaac, libav_aac, voaac, faac und ich vorschnell auf faac gesetzt habe, dies aber von GStreamer für Windows nicht bereitgestellt wird. Ein gemeinsamer Nenner für Windows und LInux wird wohl voaac sein, aber da heißt es erstmal testen, testen, testen.

**Comment by wunderlich** [comment]
Vielen, vielen Dank für die schnelle Antwort! Ich habe `faac` und `libfaac0` nachinstalliert (ja, sie heißen beide auch unter Ubuntu so). Leider immer noch Fehlanzeige in vokoscreenNG.

Es existiert auch die Binary `/usr/bin/faac`, also das Programm scheint richtig installiert worden zu sein.

```
/usr/bin/faac -h
Freeware Advanced Audio Coder
FAAC 1.29.7.7

Usage: faac [options] infile

Help options:
	-h		Short help on using FAAC
	-H		Description of all options for FAAC.
…
```

Ich habe schon geahnt, dass es an der Umstellung auf GStreamer liegen könnte, da es unter 2.5 ja problemlos läuft. Bei der Recherche konnte ich nichts finden und stecke auch nicht so tief in der Materie.

Ich beteilige mich gerne an weiteren Tests.
