### ISSUE TITLE
Magnification fails on multiple monitors with different resolution

### ISSUE THREAD

**Issue by tugrulduran** [vkohaupt/vokoscreenNG#88]
My primary display is HD (Laptop screen) and the second one is 2K HDMI.
I'm trying to record a video on full screen mode on 2K one.
Magnification is only working in 1920x1080 range starting 0x0 on selected display. Outside this range, recording is working with no problems but magnification box stucks at the range line. Both horizontal and vertical limits have the same behaviour.

**Comment by tugrulduran** [comment]
I just noticed I was using vokoscreen, not NG one.
With vokoscreen, the situation is what I said at earlier post.
With vokoscreen-ng, its magnifying completely wrong screen. In magnification box, I'm seeing the image on my primary screen at mouse coordinates.

Thanks.

**Comment by vkohaupt** [comment]
Now the Magnification is working on multiple monitors.
If you can self build vokoscreenNG then you can test it.
I close this issues.
