### ISSUE TITLE
Doesn't work vokocreenNG v3.0.4 in Ubuntu 20.04

### ISSUE THREAD

**Issue by afrizal423** [vkohaupt/vokoscreenNG#89]
Well, I've tried vokoscreenNG v3.0.4 apparently can't record the screen on Ubuntu 20.04, I finally uninstalled it, then I followed the installation method on [readme](https://github.com/vkohaupt/vokoscreenNG/blob/3.0/README.md). It seems to work well, no problem.

not being able to record means that when I press the start button, the video size always remains 0KB.

please fix the latest version.

**Comment by khinch** [comment]
I have noticed the same in Ubuntu 18.04, but for me the 0byte files only happen when audio recording is enabled. If audio is disabled I can record fine (MKV and MP4 tested, x264, superfast, 17). I don't see any signs of errors in the logs. 

Combinations which all result in 0byte files:

- mp4 & x264:
  - mp3
  - opus 
- mkv & x264:
  - vorbis
  - flac
  - opus
  - mp3
- mkv & vp8:
  - vorbis
  - flac
  - opus
  - mp3
- webm & vp8:
  - vorbis
  - opus
- avi & x264:
  - mp3

I don't have time to test any further combos right now, but it looks quite consistent that any audio recording is causing the encoding to fail to write to disk. 

**VokoscreenNG version:** 3.0.4
**OS:** Ubuntu 18.04
**Kernel:** 5.3.0-51-generic
**Sound card:** Asus Xonar SE
**Gfx card:** Radeon RX590

Edit: forgot to mention installed via snap package

**Comment by vkohaupt** [comment]
@Khinch and @afrizal423
Installed as snap?

**Comment by afrizal423** [comment]
im installed via ```apt install```

**Comment by khinch** [comment]
Yes, I installed via snap.

**Comment by vkohaupt** [comment]
@afrizal423

> Well, I've tried vokoscreenNG v3.0.4 apparently can't record the screen on Ubuntu 20.04, I finally uninstalled it, then I followed the installation method on [readme](https://github.com/vkohaupt/vokoscreenNG/blob/3.0/README.md). It seems to work well, no problem.

The first install was a snap?

**Comment by afrizal423** [comment]
> @afrizal423
> 
> > Well, I've tried vokoscreenNG v3.0.4 apparently can't record the screen on Ubuntu 20.04, I finally uninstalled it, then I followed the installation method on [readme](https://github.com/vkohaupt/vokoscreenNG/blob/3.0/README.md). It seems to work well, no problem.
> 
> The first install was a snap?

no sir, I did the first installation using apt install

**Comment by vkohaupt** [comment]
@afrizal423

> Well, I've tried vokoscreenNG v3.0.4 apparently can't record the screen on Ubuntu 20.04, I finally uninstalled it, then I followed the installation method on [readme](https://github.com/vkohaupt/vokoscreenNG/blob/3.0/README.md). It seems to work well, no problem.

The first install was a snap?

**Comment by khinch** [comment]
I'm not sure if this helps, but I notice the permissions for the Snap package don't mention the audio system. Could the Snap package be misconfigured or doesn't the audio system require its own permission?

![image](https://user-images.githubusercontent.com/13088378/82707726-89303a00-9c74-11ea-8823-22e1a224d736.png)

Out of interest I decided to try apt. There is no installation candidate in the default 18.04 apt repositories, so I installed 3.0.4 from the ubuntuhandbook repository and all works fine (apart from a few missing icons, strangely). So, it certainly seems like the Snap package is at fault in my case.

**Comment by sebbaum** [comment]
@vkohaupt 
I can confirm. Installation via Snap doesn't work.
Adding the PPA and installing it via apt works fine. (Ubuntu 18.04 LTS)

That's the best tool that I found. Keep up the good work.

Cheers

**Comment by cmatsuoka** [comment]
The snap version is not working because it uses the [audio-record interface](https://snapcraft.io/docs/audio-record-interface) and it's not connected automatically. To connect manually, use the command:
```
$ snap connect vokoscreen-ng:audio-record
```
and audio recording should work properly. However, given the nature of this application, I think @popey should request auto-connect for this interface.

**Comment by pixelr0** [comment]
works fine for me on Ubuntu 20.04. the snap runs fine, records fine (without sound).

**Comment by finalclass** [comment]
Same for me. I'm on arch linux and installed the package using `pacman`. 
When I try to install it using `snap` I get the error:
```
$ sudo snap install vokoscreen-ng
error: cannot perform the following tasks:
- Mount snap "vokoscreen-ng" (86) (app description field 'command' contains illegal "bin/desktop-launch $SNAP/vokoscreenNG" (legal: '^[A-Za-z0-9/. _#:-]*$'))
```

**Comment by popey** [comment]
@finalclass oh dear, looks like a possible bug in snapd on arch. What do you get from `snap version`?

**Comment by finalclass** [comment]
```
$ snap version
snap    unknown
snapd   unknown
series  16
arch    unknown
kernel  5.8.5-arch1-1
```

Indeed it might be the case. I'm updating it...

```
$ snap --version
snap    2.46.1-1
snapd   unknown
series  16
arch    unknown
kernel  5.8.5-arch1-1
```

And unfortunately this hasn't helped

```
$ sudo snap install vokoscreen-ng
error: cannot perform the following tasks:
- Mount snap "vokoscreen-ng" (86) (app description field 'command' contains illegal "bin/desktop-launch $SNAP/vokoscreenNG" (legal: '^[A-Za-z0-9/. _#:-]*$'))
```

**Comment by finalclass** [comment]
:facepalm: apparently the install has not reloaded my snapd

```
$ sudo systemctl restart snapd
$ sudo snap install vokoscreen-ng
vokoscreen-ng 3.0.6 from Alan Pope (popey) installed
```

This time it does not start
```
$ vokoscreen-ng
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
Fontconfig warning: FcPattern object weight does not accept value [40 210)
Segmentation fault (core dumped)
```
