### ISSUE TITLE
Use system icon in Systray 

### ISSUE THREAD

**Issue by jEsuSdA** [vkohaupt/vokoscreenNG#90]
Hi!

VokoscreenNG still using hardcoded icon in Systray.
It would be great using system ones cause a lot of icon themes has vokoscreen-ng icons.

Maybe you can check if system icon exists and fallback to hardcoded one if does not.

Thanks!

**Comment by vkohaupt** [comment]
Oh nice? Where can you look at them.

**Comment by jEsuSdA** [comment]
Hi @vkohaupt !

First at all, I want to thank you for your great work making vokoscreen possible! Thanks!!!

Talking about the systray icon, I use Papirus icon theme. 
I submit a request to add vokoscreen and vokoscreen-ng icons and they did the work.

https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/2159

They made the icons in some different sizes and they named them as vokoscreen.svg and vokoscreenNG.svg

Maybe you can try to load vokoscreenNG system icon or maybe it would be a great solution trying to load a "symbolic" version to allow vokoscreenng systry icon to be more consistent.

I can subbmit a new request to the Papirus people to ask them for a symbolic vokoscreen icon version.

What do you think?

**Comment by vkohaupt** [comment]
Yes, that looks good and I'm interested in it.
But I have to rewrite and test some of the code that takes time.
I will take a closer look at this in the next few months, but I cannot promise anything.

To time three states are displayed.
Norecord:
![screencast-01](https://user-images.githubusercontent.com/3152567/82340778-e9627a00-99ef-11ea-9ba9-078ac2ceb7cb.png)

Record:
![screencast-02](https://user-images.githubusercontent.com/3152567/82340817-f54e3c00-99ef-11ea-987a-9be83b1ec562.png)

Pause:
![screencast-03](https://user-images.githubusercontent.com/3152567/82340827-f97a5980-99ef-11ea-9f81-bac4f9ea3d3b.png)

**Comment by jEsuSdA** [comment]
And what are the names of the icons for each state?

Thanks!

**Comment by vkohaupt** [comment]
https://github.com/vkohaupt/vokoscreenNG/tree/3.0/src/pictures/systray

**Comment by jEsuSdA** [comment]
In order to use the stock system icons, it will be interesting rename icons as a more specific names:

systray = vokoscreenng
pause = vokoscreenng-pause
record = vokoscreenng-record

so, you can try to load the stock icon named as needed and if this does not exist you can load your own.

;)

I can open an issue into Papirus icon theme to ask they for vokoscreenng systray icons support, but I think it will be needed to provide a more specific name to each one. ;)

Thanks a lot, @vkohaupt !!!

**Comment by vkohaupt** [comment]
I installed the Papirus theme. It would be nicer if the recognition value of the symbol were higher. The vokoscreenNG symbol should / must contain a film roll and a speaker.
