### ISSUE TITLE
vokoscreen 2 and NG, does not save the screen 

### ISSUE THREAD

**Issue by Diallomm** [vkohaupt/vokoscreenNG#91]
I have a problem with vokoscreen (version 2 as with the new version 3), when I launch the recording, all goes well but when the recording is finished that I leave to play the video, I see a black screen all the length of the video, and what is strange the mouse appears in the recording, but we do not see the windows all is black, the sound comes well too, I installed this on 2 different linux debian machines but already the same problem. 

OS : Debian 10 (buster) with Gnome 3.30.2
Ram: 8GO
Processor: intel I5 

some screenshot on my drive
https://drive.google.com/file/d/17OrW73uszKacdvbdL4k4yvAGKcbj20GH/view?usp=sharing
https://drive.google.com/file/d/15MYn0E5hh6BRWAC9786-2muri1xkGHHg/view?usp=sharing

**Comment by Diallomm** [comment]
So, i find a problem, 
"To time Wayland is not supported. A screencast show a black screen. Please logout and start a X11 Desktop session" 
I try to use x11 for recording

**Comment by vkohaupt** [comment]
You want report a bug?
Start vokoscreenNG, comes a dialog? If yes, then read this. If no then is this a bug.

**Comment by vkohaupt** [comment]
Ok you found the dialog

**Comment by Diallomm** [comment]
vokoscreen 2 don't show any dialog, it's when I completed version 3 (NG) that I saw the message and I understood the problem, now it works fine thanks
