### ISSUE TITLE
Build fails with Qt 5.15

### ISSUE THREAD

**Issue by tux93** [vkohaupt/vokoscreenNG#92]
Yesterdays openSUSE Tumbleweed snapshot brought GCC 10 and Qt 5.15 which broke vokoscreenNG builds:
https://build.opensuse.org/package/show/multimedia:apps/vokoscreenNG

[vokoscreenNG_openSUSE-Tumbleweed_log.txt](https://github.com/vkohaupt/vokoscreenNG/files/4734779/vokoscreenNG_openSUSE-Tumbleweed_log.txt)

**Comment by mthw0** [comment]
Qt5 is now available on Arch Linux and it is also broken there. Log shows the same error.

**Comment by tux93** [comment]
924edeccfaaddf483959b8cf140f13ef64420378 fixes it,  
leaving the Issue open until @vkohaupt makes a new release

**Comment by vkohaupt** [comment]
vokoscreenNG 3.0.5 will be released at the end of this month and a compilation no longer makes mistakes under Qt 5.15.0.
I close ths issues.
