### ISSUE TITLE
vokoscreenNG has no AppStream metadata

### ISSUE THREAD

**Issue by tux93** [vkohaupt/vokoscreenNG#93]
Originally reported here:  
https://bugzilla.opensuse.org/show_bug.cgi?id=1172620  
> $ appstreamcli search vokoscreen
> Unable to find component matching vokoscreen!
>
> As a result, the app cannot be found using graphical software center apps such as KDE Discover and GNOME Software.

AppStream Spec:  
https://www.freedesktop.org/software/appstream/docs/

**Comment by thiagoandrade01** [comment]
Hi @vkohaupt,

Debian has now a AppStream metadata [1] for vokoscreenNG. Feel free to use it if you want it. Otherwise, please, close this bug.

[1] https://salsa.debian.org/debian/vokoscreen-ng/-/blob/debian/master/debian/upstream/de.volkoh.linuxecke.vokoscreen_ng.metainfo.xml

**Comment by tux93** [comment]
There is also #94 which would introduce AppStream metadata too

**Comment by vkohaupt** [comment]
> Hi @vkohaupt,
> 
> Debian has now a AppStream metadata [1] for vokoscreenNG. Feel free to use it if you want it. Otherwise, please, close this bug.
> 
> [1] https://salsa.debian.org/debian/vokoscreen-ng/-/blob/debian/master/debian/upstream/de.volkoh.linuxecke.vokoscreen_ng.metainfo.xml

Thanks for the information. But honestly, I don't know what to do with the metadata.
I close this issues.
