### ISSUE TITLE
How do I get a lossless recording?

### ISSUE THREAD

**Issue by airbete** [vkohaupt/vokoscreenNG#97]
How do I get a visual lossless recording ?

For the sake of the demonstration, I recorded a static image with vokoscreenNG (x264, quality 0). I extracted a screenshot of the .mkv file :
![vokoscreenNG x264_q0](https://user-images.githubusercontent.com/10148399/89130515-9c148580-d4d3-11ea-95ce-955f665fd84a.png)

Here is a direct screenshot of the static image : 
![original](https://user-images.githubusercontent.com/10148399/89130548-bd757180-d4d3-11ea-991e-0bb0008c3419.png)

Finally, I also recorded the image with ffmpeg (-c:v libx264rgb -crf 0) and extracted a screenshot for comparison : 
![ffmpeg x264rgb](https://user-images.githubusercontent.com/10148399/89130557-d3833200-d4d3-11ea-91c4-187bfe5b7c1f.png)

The recording with vokoscreenNG shows muddy colors and artifacts which don't show up with ffmpeg. Is there any way I get an equivalent quality with vokoscreenNG ?

Thank you.

**Comment by vkohaupt** [comment]
I could find out who caused it. It is the profile=baseline
Without this, the colors are ok.
Can you please provide the complete ffmpeg command for a better comparison.
Thanks.

**Comment by airbete** [comment]
The command is
`ffmpeg -f x11grab -s 480x300 -r 30 -i :0.0 -c:v libx264rgb -crf 0 ffmpeg.x264rgb.mkv`

I have also tried with huffyuv which gives a visually identical result as libx264rgb but with much bigger file size:
`ffmpeg -f x11grab -s 480x300 -r 30 -i :0.0 -c:v huffyuv -crf 0 ffmpeg.huffyuv.avi`

**Comment by vkohaupt** [comment]
I added a combo box with the profiles "baseline" and "high-4:4:4". "Baseline" is good for older video players and devices, but have a color sub-sampling from 4:2:0 and shows muddy colors. The "high-4:4:4" profile reproduces all colors very well, but the video player or device must support it. Vlc, mpv etc. support this.
![screencast-02](https://user-images.githubusercontent.com/3152567/90321788-546b1080-df4d-11ea-98cd-37088437d025.png)

**Comment by airbete** [comment]
Very nice! Colors look perfect now. Thank you so much.

**Comment by airbete** [comment]
I noticed today there is still something wrong.

I recorded the same static image as above with x264 / veryfast / high-4:4:4 / Quality 0.
I then played the mkv file with mpv, vlc and ffplay and recorded a screenshot in each.
Here is what I observed : 
Original image == mpv == vlc != ffplay .

The recording is perfect when played with mpv and vlc, but not when played with ffplay.

This is the screenshot with mpv (identical to vlc and the original):
![vokoscreenNG x264_q0_high mpv](https://user-images.githubusercontent.com/10148399/90956567-c1067380-e455-11ea-9816-625369353675.png)

And this is the screenshot with ffplay:
![vokoscreenNG x264_q0_high ffplay](https://user-images.githubusercontent.com/10148399/90956576-cfed2600-e455-11ea-9282-0525de7472bf.png)

Clearly, there is a colorspace misidentification when using ffplay. This is a problem for me as I use ffmpeg (via kdenlive) to edit my clips and they still all show wrong colors. Now, is this
- a bug in ffmpeg ?
- a bug in gstreamer (incorrect colorspace tagging) ?
- a bug in vokoscreenNG (incomplete colorspace tagging) ?

Here are some additional info:

_ffplay / ffprobe_
Stream #0:0(eng): Video: h264 (High 4:4:4 Predictive), yuv444p(**tv**, bt470bg/smpte170m/bt709, progressive), 480x300 [SAR 1:1 DAR 8:5], 30 fps, 30 tbr, 1k tbn, 60 tbc (default)
color_range=**tv**
color_space=bt470bg
color_transfer=bt709
color_primaries=smpte170m

_mpv_
[vf] [in] 480x300 yuv444p bt.601/bt.601-525/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [out] 480x300 yuv444p bt.601/bt.601-525/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264

_vlc_
![Selection_090](https://user-images.githubusercontent.com/10148399/90956749-548c7400-e457-11ea-95a4-47adc85af4c2.png)

The color_range=tv shown by ffprobe looks very strange to me. Shouldn't it be pc ? Is there any flag that can be added while recording in vokoscreenNG so that the correct colorspace will be identified by ffmpeg ?

Thank you

**Comment by vkohaupt** [comment]
I close this issue. I don't have time to search for ffplay the problem. Please understand.

**Comment by ValZapod** [comment]
> * a bug in ffmpeg

It is a bug in ffplay: SDLv2 does not support 4:4:4. Use ffplay -vf scale=in_color_matrix=auto,format=gbrp.

**Comment by ValZapod** [comment]
> ffmpeg -f x11grab -s 480x300 -r 30 -i :0.0 -c:v libx264rgb -crf 0 ffmpeg.x264rgb.mkv

This command will not tag RGB as full range but insted tag full as limited which is wrong. Was fixed in https://github.com/FFmpeg/FFmpeg/commit/7ca71b79f2b3256a0eef1a099b857ac9e4017e36
