### ISSUE TITLE
Timer Not Working Ubuntu 20.04/Windows 10

### ISSUE THREAD

**Issue by quarkrad** [vkohaupt/vokoscreenNG#98]
I have install 3.0.2 on ubuntu 20.04 and windows 10 and it is working fine in manual mode.  However, I cannot get it to record using the timer.  From what I have read the time function/settings* is initiated by ticking the **Start the timer**  check box under the clock tab. * Assume you have to tick both the **Start the timer** and **Stop recording after** tick boxes

**Comment by vkohaupt** [comment]
> I have install 3.0.2 on ubuntu 20.04 and windows 10 and it is working fine in manual mode. However, I cannot get it to record using the timer. From what I have read the time function/settings* is initiated by ticking the **Start the timer** check box under the clock tab.

That´s right.
Example:
The current Time is 10:30 and we want recording at 10:32. We set the hour on 10 and the minute on 32 and start the timer.
The recording must beginning on 10:32
Try it and tell

**Comment by quarkrad** [comment]
Thank you - I was setting the timer from the current time. So I setting 2minutes instead of 20:52 (if the current time was 20:50).  One issue I do have is the central graphic and baorder graphics on recordings.  Attached example of a youtube video recording of my Desktop.  I cannot see an option not to have the central text i.e. 1159 x 651 and the 1/4, 1/2 circles on the edges.
![Screenshot at 2020-08-03 21-06-03](https://user-images.githubusercontent.com/29422032/89222582-31e00b80-d5cd-11ea-9ec7-38f94babe1f6.png)
