### ISSUE TITLE
Graphics on Screen

### ISSUE THREAD

**Issue by quarkrad** [vkohaupt/vokoscreenNG#99]
I have successfully captured a screen record on Ubuntu 20.04 but I have some graphics on the recording that I cannot see an option 'not to have'.  In the centre of the screen there is the size of the recording area i.e. 1159 x 651 and the 1/4, 1/2 circles on the edges. 
![shot](https://user-images.githubusercontent.com/29422032/89329758-27824800-d687-11ea-81d4-5829df51dcb8.jpg)

**Comment by vkohaupt** [comment]
Please install the latest version 3.0.5
Installation instructions for Ubuntu can be found here:
https://linuxecke.volkoh.de/vokoscreen/vokoscreen-install.html

And the download for Windows here:
https://linuxecke.volkoh.de/vokoscreen/vokoscreen-download.html
